/* =====================================================================
   dungeon-skin.js — runtime for the Blender-authored cutscene characters.

   js/dungeon-models.js (generated by tools/blender/build-dungeon-models.py)
   holds quantised skinned meshes, bone rest poses, rigid weapon meshes and
   sampled Blender actions. This turns them into THREE.SkinnedMesh +
   THREE.Skeleton + THREE.AnimationClip and drives them with an
   AnimationMixer:

     const a = DungeonSkin.create('kael', { height: 15 });
     a.pose([['idle', t, 1], ['dash_slash', t2, w]]);   // scrubbed (cutscenes)
     a.play('walk', 0.25); a.update(dt);                 // real time, cross-faded
     a.setWeapon('crossbow');  a.tint({ shirt: '#f00' });

   This file is lazy-loaded by dungeon3d.js after login, so neither the
   login screen nor the town pays for it. No dependency beyond the
   vendored three.min.js (r148).

   ---------------------------------------------------------------------
   LOADER API — per-character split packs (read this if you add a boss)
   ---------------------------------------------------------------------
   The Blender pack is split into one self-contained file per character:
   js/dungeon-models/<id>.js (mesh, skeleton, materials, clips; 'hero' also
   carries every weapon), listed with a content hash + size in
   js/dungeon-models/index.js. Each file merges itself into
   globalThis.DungeonModels when it runs, so any load order works and a
   cutscene only downloads the characters it actually shows (a mini + the
   party hero is ~0.5 MB instead of the old 2.2 MB monolith).

     DungeonSkin.setBase(url)        directory URL holding <id>.js + index.js
                                     (dungeon3d.js sets it from its own URL)
     DungeonSkin.load(ids)           -> Promise<boolean>: true when every id is
                                     in memory. Fetches only missing files,
                                     de-duplicated; a failed file can retry later.
     DungeonSkin.prefetch(ids)       the same at low fetch priority; never rejects
     DungeonSkin.state(id)           'absent' | 'loading' | 'ready' | 'failed'
     DungeonSkin.has(id)             in memory and creatable right now
     DungeonSkin.available(id)       a file exists for it (index) or it is loaded
     DungeonSkin.onArrive(fn)        fn(ids) each time characters land
     DungeonSkin.stats()             [{id, bytes, ms, ok}] per fetched file

   To add a character: build it with tools/blender/build-dungeon-models.py
   (which writes js/dungeon-models/<id>.js + index.js), then name it in the
   boss's cast in dungeon3d.js (SKINNED) — DungeonGL.prefetch(bossId) and the
   cutscene itself call load() for exactly that cast. Rebuilt with an old
   script into one js/dungeon-models.js? `node tools/split-dungeon-models.cjs
   js/dungeon-models.js --only <ids>` converts it.
   See docs/sundered-crown/CUTSCENE-PERF.md.
   ===================================================================== */
(function () {
  "use strict";
  const G = typeof globalThis !== "undefined" ? globalThis : window;
  if (typeof THREE === "undefined") { G.DungeonSkin = { ready: () => false, has: () => false, load: () => Promise.resolve(false), prefetch: () => Promise.resolve(false), state: () => "failed", available: () => false }; return; }

  const lib = () => G.DungeonModels || null;
  // ---- the split-pack loader
  const files = {};            // id -> { promise, state, bytes, ms }
  const arriveFns = [];
  let base = "";
  const inMemory = (id) => { const L = lib(); return !!(L && L.characters && L.characters[id]); };
  function fetchScript(url, low) {
    return new Promise((ok, no) => {
      if (typeof document === "undefined" || !document.head) { no(new Error("no document")); return; }
      const el = document.createElement("script"); el.src = url; el.async = true;
      if (low) { try { el.fetchPriority = "low"; } catch (e) {} }
      el.onload = ok; el.onerror = () => { el.remove(); no(new Error("could not load " + url)); };
      document.head.appendChild(el);
    });
  }
  function loadOne(id, low) {
    if (inMemory(id)) return Promise.resolve(true);
    const f = files[id];
    if (f && f.promise && f.state !== "failed") return f.promise;
    const idx = (G.DungeonModelIndex || {})[id];
    if (!base) return Promise.resolve(false);
    if (G.DungeonModelIndex && !idx) { files[id] = { state: "failed", promise: Promise.resolve(false) }; return files[id].promise; }
    const t0 = (typeof performance !== "undefined" ? performance.now() : Date.now());
    const rec = files[id] = { state: "loading", bytes: idx ? idx.bytes : 0, ms: 0 };
    rec.promise = fetchScript(base + id + ".js" + (idx ? "?v=" + idx.v : ""), low).then(() => {
      rec.ms = (typeof performance !== "undefined" ? performance.now() : Date.now()) - t0;
      rec.state = inMemory(id) ? "ready" : "failed"; return rec.state === "ready";
    }, (e) => { rec.state = "failed"; rec.promise = null; console.warn("Dungeon model " + id + " unavailable", e); return false; });
    return rec.promise;
  }
  function load(ids, low) {
    const list = (Array.isArray(ids) ? ids : [ids]).filter(Boolean);
    return Promise.all(list.map((id) => loadOne(id, low))).then((r) => r.every(Boolean));
  }
  function stateOf(id) { if (inMemory(id)) return "ready"; const f = files[id]; return f ? f.state : "absent"; }
  const decoded = {};          // per mesh key -> typed arrays (kept for rebuilding geometry)
  const clipCache = {};        // per character id + clip -> THREE.AnimationClip

  function bytes(s) {
    if (typeof atob === "function") { const b = atob(s), u = new Uint8Array(b.length); for (let i = 0; i < b.length; i++) u[i] = b.charCodeAt(i); return u; }
    const B = G.Buffer.from(s, "base64"); return new Uint8Array(B.buffer, B.byteOffset, B.length).slice();
  }
  const u16 = (s) => { const b = bytes(s); return new Uint16Array(b.buffer, b.byteOffset, b.byteLength >> 1); };
  const i16 = (s) => { const b = bytes(s); return new Int16Array(b.buffer, b.byteOffset, b.byteLength >> 1); };
  const u32 = (s) => { const b = bytes(s); return new Uint32Array(b.buffer, b.byteOffset, b.byteLength >> 2); };
  const i8 = (s) => { const b = bytes(s); return new Int8Array(b.buffer, b.byteOffset, b.byteLength); };

  function decodeMesh(key, m) {
    if (decoded[key]) return decoded[key];
    const q = u16(m.p), n = m.vc, pos = new Float32Array(n * 3), b = m.b;
    for (let i = 0; i < n; i++) for (let a = 0; a < 3; a++) pos[i * 3 + a] = b[a] + (b[a + 3] - b[a]) * q[i * 3 + a] / 65535;
    const out = { pos, nrm: m.n ? i8(m.n) : null, idx: m.w === 4 ? u32(m.i) : u16(m.i), groups: m.g };
    if (!out.nrm) {
      // normals are not shipped: hard edges are split vertices, so per-index averaging rebuilds them
      const g = new THREE.BufferGeometry(); g.setAttribute("position", new THREE.BufferAttribute(pos, 3)); g.setIndex(new THREE.BufferAttribute(out.idx, 1));
      g.computeVertexNormals(); out.nrm = g.getAttribute("normal").array; g.dispose();
    }
    if (m.j) { const j = bytes(m.j); out.skinIndex = new Uint16Array(j.length); for (let i = 0; i < j.length; i++) out.skinIndex[i] = j[i]; out.skinWeight = bytes(m.k); }
    return (decoded[key] = out);
  }
  function geometry(key, m) {
    const d = decodeMesh(key, m), g = new THREE.BufferGeometry();
    g.setAttribute("position", new THREE.BufferAttribute(d.pos, 3));
    g.setAttribute("normal", d.nrm instanceof Float32Array ? new THREE.BufferAttribute(d.nrm, 3) : new THREE.BufferAttribute(d.nrm, 3, true));
    if (d.skinIndex) { g.setAttribute("skinIndex", new THREE.BufferAttribute(d.skinIndex, 4)); g.setAttribute("skinWeight", new THREE.BufferAttribute(d.skinWeight, 4, true)); }
    g.setIndex(new THREE.BufferAttribute(d.idx, 1));
    d.groups.forEach((gr, i) => g.addGroup(gr[1], gr[2], i));
    g.computeBoundingSphere();
    return g;
  }
  function material(name, overrides) {
    const s = (lib().materials || {})[name] || { color: "#888888", roughness: 0.8, metalness: 0 };
    // no environment map in the dungeon scenes: fully metallic surfaces would read black, so metals keep some diffuse
    const o = { color: new THREE.Color(s.color), roughness: s.roughness, metalness: Math.min(0.55, s.metalness) };
    if (s.emissive) { o.emissive = new THREE.Color(s.emissive); o.emissiveIntensity = s.ei || 1; }
    if (s.side === 2) o.side = THREE.DoubleSide;
    if (s.opacity != null && s.opacity < 1) { o.transparent = true; o.opacity = s.opacity; o.depthWrite = false; }
    if (s.additive) { o.transparent = true; o.blending = THREE.AdditiveBlending; o.depthWrite = false; o.side = THREE.DoubleSide; }
    const m = new THREE.MeshStandardMaterial(Object.assign(o, overrides || {}));
    m.name = name; m.userData.tint = s.tint || null; m.userData.baseColor = m.color.clone(); m.userData.baseOpacity = m.opacity;
    return m;
  }

  // ---- clips: basis tracks -> local tracks for this character's rest pose
  // 'walk|noarms' / 'ready_pole|arms': the clip restricted to (or without) the arm chains, so a
  // locomotion layer and a weapon-hold layer can run at full weight on disjoint bones.
  const ARM = /^(shoulder|upper_arm|forearm|hand|grip)\./;
  function clipFor(cid, name) {
    const key = cid + "|" + name;
    if (clipCache[key]) return clipCache[key];
    const bar = name.indexOf("|");
    if (bar > 0) {
      const base = clipFor(cid, name.slice(0, bar)), mask = name.slice(bar + 1); if (!base) return null;
      const keep = (t) => { const arm = ARM.test(t.name.split(".").slice(0, -1).join(".")); return mask === "arms" ? arm : !arm; };
      const c = new THREE.AnimationClip(name, base.duration, base.tracks.filter(keep)); c.userData = base.userData;
      return (clipCache[key] = c);
    }
    const L = lib(), ch = L.characters[cid], ref = ch.clips[name];
    if (ref == null) return null;
    const c = L.clips[ref], names = L.skeletons[ch.skel].bones, rest = ch.rest, fps = c.f || 30, unit = ch.u;
    const tracks = [], rq = new THREE.Quaternion(), bq = new THREE.Quaternion(), v = new THREE.Vector3();
    for (const tr of c.t) {
      const bi = tr[0], R = rest[bi], bone = names[bi];
      rq.set(R[3], R[4], R[5], R[6]);
      if (tr.length === 1) { tracks.push(new THREE.QuaternionKeyframeTrack(bone + ".quaternion", [0], [R[3], R[4], R[5], R[6]])); continue; }
      const fr = u16(tr[1]), qs = i16(tr[2]), times = new Float32Array(fr.length), vals = new Float32Array(fr.length * 4);
      for (let i = 0; i < fr.length; i++) {
        times[i] = fr[i] / fps;
        bq.set(qs[i * 4] / 32767, qs[i * 4 + 1] / 32767, qs[i * 4 + 2] / 32767, qs[i * 4 + 3] / 32767).normalize();
        bq.premultiply(rq);
        vals[i * 4] = bq.x; vals[i * 4 + 1] = bq.y; vals[i * 4 + 2] = bq.z; vals[i * 4 + 3] = bq.w;
      }
      tracks.push(new THREE.QuaternionKeyframeTrack(bone + ".quaternion", times, vals));
      if (tr.length > 3) {
        const pf = u16(tr[3]), ps = i16(tr[4]), pt = new Float32Array(pf.length), pv = new Float32Array(pf.length * 3);
        for (let i = 0; i < pf.length; i++) {
          pt[i] = pf[i] / fps;
          v.set(ps[i * 3], ps[i * 3 + 1], ps[i * 3 + 2]).multiplyScalar(unit / 4096).applyQuaternion(rq);
          pv[i * 3] = R[0] + v.x; pv[i * 3 + 1] = R[1] + v.y; pv[i * 3 + 2] = R[2] + v.z;
        }
        tracks.push(new THREE.VectorKeyframeTrack(bone + ".position", pt, pv));
      }
    }
    const clip = new THREE.AnimationClip(name, c.d, tracks);
    clip.userData = { loop: !!c.l };
    return (clipCache[key] = clip);
  }

  function create(cid, opts) {
    opts = opts || {};
    const L = lib(), ch = L && L.characters[cid];
    if (!ch) return null;
    const names = L.skeletons[ch.skel].bones, parents = L.skeletons[ch.skel].parents;
    const root = new THREE.Group(); root.name = "skin:" + cid;
    const body = new THREE.Group(); root.add(body);
    const scale = opts.height ? opts.height / ch.h : (opts.scale || 1);
    body.scale.setScalar(scale);
    const bones = names.map((n, i) => { const b = new THREE.Bone(); b.name = n; const R = ch.rest[i]; b.position.set(R[0], R[1], R[2]); b.quaternion.set(R[3], R[4], R[5], R[6]); return b; });
    bones.forEach((b, i) => { if (parents[i] < 0) body.add(b); else bones[parents[i]].add(b); });
    const mats = {};
    const matFor = (name) => mats[name] || (mats[name] = material(name, opts.materials && opts.materials[name]));
    const geo = geometry(cid, ch.mesh);
    const mesh = new THREE.SkinnedMesh(geo, ch.mesh.g.map((g) => matFor(g[0])));
    mesh.frustumCulled = false; mesh.castShadow = opts.shadows !== false; mesh.receiveShadow = true;
    body.add(mesh);
    root.updateMatrixWorld(true);
    const skeleton = new THREE.Skeleton(bones);
    mesh.bind(skeleton);
    const byName = {}; bones.forEach((b) => { byName[b.name] = b; });
    // rigid attachments authored with the character (shields, scepters, the boss weapons)
    const attached = [];
    for (const a of ch.attach || []) {
      const m = new THREE.Mesh(geometry(cid + "#" + a.name, a.mesh), a.mesh.g.map((g) => matFor(g[0])));
      m.name = a.name; m.castShadow = opts.shadows !== false; byName[a.bone].add(m); attached.push(m);
    }
    const mixer = new THREE.AnimationMixer(body);
    const actions = {};
    const action = (n) => {
      if (actions[n]) return actions[n];
      const c = clipFor(cid, n); if (!c) return null;
      const a = mixer.clipAction(c); a.play(); a.enabled = false; a.setEffectiveWeight(0);
      return (actions[n] = a);
    };
    let current = null, weapon = null;
    const actor = {
      id: cid, root, body, mesh, bones: byName, skeleton, mixer, mats, scale, attached,
      height: ch.h * scale, clips: Object.keys(ch.clips),
      has: (n) => ch.clips[n] != null,
      duration: (n) => { const c = clipFor(cid, n); return c ? c.duration : 0; },
      // Scrubbed pose for timeline-driven cutscenes: layers [[clip, seconds, weight], ...]. Looping clips
      // wrap, one-shots clamp. Weights are normalised to 1 so the blend never sags towards the bind pose.
      // Weights are used as given: layers on the same bones should sum to 1 (cross-fades).
      pose(layers) {
        for (const k in actions) { actions[k].enabled = false; actions[k].setEffectiveWeight(0); }
        for (const l of layers) {
          if (!l || !(l[2] > 0)) continue;
          const a = action(l[0]); if (!a) continue;
          const d = a.getClip().duration, loop = a.getClip().userData.loop;
          let t = l[1] || 0; t = loop ? ((t % d) + d) % d : Math.max(0, Math.min(d - 1e-4, t));
          a.enabled = true; a.setEffectiveWeight(Math.min(1, l[2])); a.time = t;
        }
        mixer.update(0);
        current = null;
        return actor;
      },
      // Real-time playback with cross-fades (review page, anything not scrubbed).
      play(n, fade, opts2) {
        const a = action(n); if (!a) return null;
        const loop = a.getClip().userData.loop;
        a.enabled = true; a.setLoop(loop ? THREE.LoopRepeat : THREE.LoopOnce, Infinity); a.clampWhenFinished = !loop;
        a.time = 0; a.setEffectiveTimeScale((opts2 && opts2.speed) || 1); a.setEffectiveWeight(1);
        if (current && current !== a && fade > 0) { current.enabled = true; current.crossFadeTo(a, fade, false); }
        else for (const k in actions) if (actions[k] !== a) { actions[k].enabled = false; actions[k].setEffectiveWeight(0); }
        a.paused = false; current = a; return a;
      },
      update(dt) { mixer.update(dt); },
      setWeapon(kind, bone) {
        if (weapon) { weapon.removeFromParent(); weapon.geometry.dispose(); weapon = null; }
        const w = L.weapons && L.weapons[kind]; if (!w) return null;
        const m = new THREE.Mesh(geometry("weapon:" + kind, w.mesh), w.mesh.g.map((g) => matFor(g[0])));
        m.name = "weapon:" + kind; m.castShadow = opts.shadows !== false;
        (byName[bone || w.bone || "grip.R"] || byName["grip.R"]).add(m);
        weapon = m; actor.weaponKind = kind; return m;
      },
      tint(app) {
        app = app || {};
        for (const k in mats) {
          const m = mats[k], t = m.userData.tint; if (!t) continue;
          const v = app[t]; try { m.color.set(v && v !== "none" ? v : m.userData.baseColor); } catch (e) { m.color.copy(m.userData.baseColor); }
        }
      },
      socket(name) {
        const s = ch.sockets && ch.sockets[name]; if (!s) return null;
        const o = new THREE.Object3D(); o.name = "socket:" + name; o.position.set(s[1], s[2], s[3]); byName[names[s[0]]].add(o); return o;
      },
      socketNames: () => Object.keys(ch.sockets || {}),
      dispose() {
        mixer.stopAllAction(); mixer.uncacheRoot(body);
        root.traverse((o) => { if (o.geometry) o.geometry.dispose(); });
        for (const k in mats) mats[k].dispose();
        root.removeFromParent();
      },
    };
    if (ch.clips.idle != null) actor.pose([["idle", 0, 1]]);
    return actor;
  }

  G.DungeonSkin = {
    // the runtime is here (it always is once this file ran); characters arrive per file
    ready: () => true,
    has: inMemory,
    setBase(url) { base = url && !/\/$/.test(url) ? url + "/" : (url || ""); },
    base: () => base,
    load: (ids) => load(ids, false),
    prefetch: (ids) => load(ids, true).catch(() => false),
    state: stateOf,
    available: (id) => inMemory(id) || !!(G.DungeonModelIndex && G.DungeonModelIndex[id]),
    onArrive(fn) { if (typeof fn === "function") arriveFns.push(fn); },
    _arrived(ids) { for (const fn of arriveFns) { try { fn(ids); } catch (e) { console.warn(e); } } },
    stats: () => Object.keys(files).map((id) => ({ id, bytes: files[id].bytes || 0, ms: Math.round(files[id].ms || 0), ok: files[id].state === "ready" })),
    characters: () => (lib() ? Object.keys(lib().characters) : []),
    weaponKinds: () => (lib() && lib().weapons ? Object.keys(lib().weapons) : []),
    weaponInfo: (k) => (lib() && lib().weapons ? lib().weapons[k] || null : null),
    meta: (id) => (lib() && lib().characters[id]) || null,
    create,
    clip: clipFor,
  };
})();
