'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),THREE=require('./vendor/three.min'),race=require('./race');
const painter=new Proxy({},{get:()=>()=>{}}),env={THREE,document:{createElement:()=>({getContext:()=>painter})}};vm.createContext(env);vm.runInContext(fs.readFileSync(require.resolve('./race-art'),'utf8'),env);
const art=env.RaceArt.create(),car=art.car();let totalInstances=0;
for(let i=0;i<12;i++){const track=race.generate(()=>i/13),circuit=art.circuit(track);circuit.updateMatrixWorld(true);circuit.traverse(m=>{assert([...m.matrixWorld.elements].every(Number.isFinite));if(m.isInstancedMesh){totalInstances+=m.count;assert([...m.instanceMatrix.array].every(Number.isFinite));}if(m.geometry?.attributes.position)assert([...m.geometry.attributes.position.array].every(Number.isFinite));});for(let t=0;t<30;t++){art.poseCar(car,race.sample(track,t*75),t,75);assert([...car.position.toArray(),...car.quaternion.toArray()].every(Number.isFinite));}art.disposeGroup(circuit);assert.equal(art.metrics().textures,0);assert.equal(art.metrics().geometries,3,'Track meshes and signs are released on a new circuit');}
assert(totalInstances>2000);art.dispose();assert.equal(art.metrics().materials,0);console.log('PASS finite detailed racing models, instanced track furniture, spline sampling and bounded geometry/material/texture lifetime across 12 circuits');
const endlessArt=env.RaceArt.create(),endlessTrack=race.generate(()=>.73,{mode:'endless',difficulty:'hard'});
for(let i=0;i<16;i++){race.extend(endlessTrack);const g=endlessArt.circuit(endlessTrack);g.traverse(m=>{if(m.geometry?.attributes.position)assert([...m.geometry.attributes.position.array].every(Number.isFinite));});endlessArt.disposeGroup(g);assert.equal(endlessArt.metrics().geometries,3);assert.equal(endlessArt.metrics().textures,0);}endlessArt.dispose();console.log('PASS endless geometry and resources remain bounded through streamed sections');
const experimentalArt=env.RaceArt.create();
for(const mode of ['short','long','endless']){const t=race.generate(()=>.46,{mode,generation:2});for(let j=0;j<8;j++){if(t.open)race.extend(t);const g=experimentalArt.circuit(t);g.updateMatrixWorld(true);g.traverse(m=>{assert([...m.matrixWorld.elements].every(Number.isFinite));if(m.geometry?.attributes.position)assert([...m.geometry.attributes.position.array].every(Number.isFinite));});const c=race.spawn(t,t.points.findIndex(p=>Math.abs(p.bank)>1.56)),model=experimentalArt.car();experimentalArt.poseCar(model,c,1,45);const up=new THREE.Vector3(0,1,0).applyQuaternion(model.quaternion);assert(Math.abs(up.y)<.03);assert(up.dot(new THREE.Vector3(c.normal.x,c.normal.y,c.normal.z))>.999);experimentalArt.disposeGroup(g);assert.equal(experimentalArt.metrics().textures,0);assert.equal(experimentalArt.metrics().geometries,3);}}experimentalArt.dispose();console.log('PASS experimental wall meshes, car surface orientation, and bounded GPU resources through 24 rebuilds');
