/* A client-only scenic time trial. No network, entry fee, prizes or payouts. */
(function(root){'use strict';
 const TAU=Math.PI*2;
 const node=typeof module==='object'&&module.exports,world=node?require('./race-world'):root.RaceWorld,classic=node?require('./race-classic'):root.RaceClassic,gen2=node?require('./race-gen2'):root.RaceGen2;
 function rebuildClassic(t){t.segments=t.points.slice(0,t.open?-1:undefined).map((p,i)=>{const q=t.points[(i+1)%t.points.length],dx=q.x-p.x,dz=q.z-p.z;return{p,q,dx,dz,len:Math.hypot(dx,dz)};});t.length=t.segments.reduce((sum,s)=>sum+s.len,0);return world.populate(t);}
 function generate(random=Math.random,options={}){const generation=Number(options.generation)||1;if(generation>=2){const t=gen2.generate(random,options);t.generation=generation;return t;}
  const mode=options.mode||'short',difficulty=options.difficulty||'medium';if(mode==='endless'){const t={seed:(random()*0xffffffff)>>>0,generation:1,mode,difficulty,theme:0,width:12,name:'Classic Endless',points:[],segments:[],open:true,nextId:0,heading:0};return extend(t,300);}
  const t=classic.generate(random);Object.assign(t,{generation:1,mode,difficulty,theme:0,width:12,name:'Original Skyline Circuit'});if(mode==='long')for(const p of t.points){p.x*=1.7;p.z*=1.7;}t.points.forEach((p,i)=>{p.bank=0;p.id=i;});return rebuildClassic(t);
 }
 function extend(t,count=60){if(t.generation>=2)return gen2.extend(t,count);for(let i=0;i<count;i++){const id=t.nextId++,previous=t.points.at(-1)||{x:0,z:0};t.heading=Math.sin(id*.018+t.seed*.0001)*(t.difficulty==='easy'?.3:t.difficulty==='hard'?.8:.55);t.points.push({x:previous.x+Math.sin(t.heading)*5,z:previous.z+Math.cos(t.heading)*5,y:8+3*Math.sin(id*.045),id,bank:0});}if(t.points.length>360)t.points.splice(0,t.points.length-360);return rebuildClassic(t);}
 function nearest(t,x,z,y){if(t.generation>=2)return gen2.nearest(t,x,z,y);return{...classic.nearest(t,x,z),bank:0};}
 function spawn(t,index=0){return t.generation>=2?gen2.spawn(t,index):classic.spawn(t,index);}
 function step(car,t,input,dt){if(t.generation>=2)return gen2.step(car,t,input,dt);const previous={...car};const hit=classic.step(car,t,input,dt);return world.collide(car,previous,t)?nearest(t,car.x,car.z):hit;}
 function sample(t,distance){if(t.generation>=2){const f=gen2.surface(t,distance);return{...f,yaw:Math.atan2(f.tangent.x,f.tangent.z),pitch:-Math.asin(f.tangent.y),roll:f.bank};}const count=t.segments.length,raw=distance/t.length*count,index=t.open?Math.max(0,Math.min(count-.00001,raw)):((raw%count)+count)%count,i=Math.floor(index),f=index-i,s=t.segments[i];return{x:s.p.x+s.dx*f,y:s.p.y+(s.q.y-s.p.y)*f,z:s.p.z+s.dz*f,yaw:Math.atan2(s.dx,s.dz),pitch:0,roll:0,index:i};}
 const api={generate,nearest,spawn,step,sample,extend,active:false};
 if(typeof module==='object'&&module.exports){module.exports=api;return;}
 root.gameRace=api;
 api.start=function(){
  if(api.active)return;
  if(typeof THREE==='undefined'||!root.RaceArt){toast('3D renderer is unavailable. Reload and try again.');return;}
  closeMenu();document.exitPointerLock?.();
  const host=document.createElement('section');host.className='race-overlay';host.innerHTML=`<div class="race-top"><div><small>APEX / FREE TIME TRIAL</small><h2>Skyline Circuit</h2></div><label>Length <select class="race-mode" aria-label="Track length"><option value="short">Short</option><option value="long">Long</option><option value="endless">Endless</option></select></label><label>Generation <select class="race-generation" aria-label="Generation"><option value="1">Generation 1 · Classic</option><option value="2">Generation 2 · Stuntworks</option><option value="3" selected>Generation 3 · Blender</option></select></label><label>Difficulty <select class="race-difficulty" aria-label="Difficulty"><option value="easy">Easy</option><option value="medium" selected>Medium</option><option value="hard">Hard</option></select></label><button data-race="exit">Exit · Esc</button></div><div class="race-view"><canvas class="race-map" width="180" height="130" aria-label="Track map and next checkpoint"></canvas></div><div class="race-dashboard"><strong class="race-time">0:00.000</strong><span class="race-speed">0 km/h</span><span class="race-progress">Checkpoint 0 / 8</span><span class="race-stunts" hidden></span></div><div class="race-bottom"><span>WASD / arrows drive · Space drift / brake · R recover<br>Yellow strips boost · Wide asphalt roads & scenic bends · No payouts.</span><button data-race="sound">Sound: on</button><button data-race="retry">Retry track</button><button data-race="new">New random track</button></div><div class="race-touch"><button data-key="left" aria-label="Steer left">◀</button><button data-key="right" aria-label="Steer right">▶</button><button data-key="down" aria-label="Brake">Brake</button><button data-key="up" aria-label="Accelerate">Gas</button></div>`;document.body.append(host);
  let renderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){host.remove();toast('Racing needs WebGL. Enable hardware acceleration.');return;}
  api.active=true;const abort=new AbortController(),signal=abort.signal;
  const view=host.querySelector('.race-view');view.append(renderer.domElement);renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;
  let art=RaceArt.create(),scene=art.scene({theme:2}),artGeneration=3;art.configure(renderer);
  let effects=root.RaceEffects.create(scene);
  const camera=new THREE.PerspectiveCamera(62,1,.1,1200);
  let track,trackGroup,car,checkpoint=0,elapsed=0,started=false,finished=false,last=0,acc=0,raf=0;
  const input={};let carModel=art.car('#294b65');scene.add(carModel);
  const map=host.querySelector('.race-map'),mapCtx=map.getContext('2d'),mapStatic=document.createElement('canvas');mapStatic.width=180;mapStatic.height=130;let mapScale=1,mapX=0,mapZ=0;
  const timeText=host.querySelector('.race-time'),speedText=host.querySelector('.race-speed'),progressText=host.querySelector('.race-progress');
  function road(){
   if(artGeneration!==track.generation){art.disposeGroup(trackGroup);trackGroup=null;effects.dispose();art.dispose();renderer.renderLists.dispose();artGeneration=track.generation;art=(artGeneration===1?root.RaceClassicArt:artGeneration===2?root.RaceSportArt:root.RaceArt).create();scene=art.scene(track);art.configure(renderer);effects=root.RaceEffects.create(scene);host.querySelector('[data-race="sound"]').textContent='Sound: on';carModel=art.car(artGeneration===2?'#ef7046':'#294b65');scene.add(carModel);}
   art.disposeGroup(trackGroup);trackGroup=art.circuit(track);scene.add(trackGroup);
   if(track.generation!==1){scene.background.set(RaceArt.palettes[track.theme].sky);scene.fog.color.copy(scene.background);}
   const xs=track.points.map(p=>p.x),zs=track.points.map(p=>p.z),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs);mapScale=Math.min(156/(maxX-minX),106/(maxZ-minZ));mapX=90-(minX+maxX)*mapScale/2;mapZ=65-(minZ+maxZ)*mapScale/2;
   const m=mapStatic.getContext('2d');m.clearRect(0,0,180,130);m.fillStyle='#102637e6';m.fillRect(0,0,180,130);m.strokeStyle='#a6bac3';m.lineWidth=4;m.beginPath();track.points.forEach((p,i)=>i?m.lineTo(p.x*mapScale+mapX,p.z*mapScale+mapZ):m.moveTo(p.x*mapScale+mapX,p.z*mapScale+mapZ));if(!track.open)m.closePath();m.stroke();if(track.generation>=2){m.strokeStyle='#27d5ea';m.lineWidth=4;for(let i=0;i<track.segments.length;i++){const seg=track.segments[i];if(Math.abs(seg.p.bank)<.3&&!seg.p.hyper)continue;m.strokeStyle=seg.p.twist?'#bd8cff':seg.p.hyper?'#ffcd48':'#27d5ea';m.beginPath();m.moveTo(seg.p.x*mapScale+mapX,seg.p.z*mapScale+mapZ);m.lineTo(seg.q.x*mapScale+mapX,seg.q.z*mapScale+mapZ);m.stroke();}}
  }
  function reset(fresh){if(host.querySelector('.race-generation').value==='3'&&!root.ApexModels){host.querySelector('.race-generation').value='2';toast('Blender assets could not load. Generation 2 is available; reload to retry Generation 3.');}if(!fresh&&track?.open&&track.generation>=2){const seed=track.seed;track=generate(()=>(seed+.1)/0xffffffff,{mode:track.mode,difficulty:track.difficulty,generation:track.generation});road();}if(fresh||!track){track=generate(Math.random,{mode:host.querySelector('.race-mode').value,difficulty:host.querySelector('.race-difficulty').value,generation:host.querySelector('.race-generation').value});road();host.querySelector('h2').textContent=track.name;}effects.reset();car=spawn(track);checkpoint=0;elapsed=0;started=false;finished=false;acc=0;progressText.textContent='Checkpoint 0 / 8';host.querySelector('.race-bottom span').innerHTML=track.generation>=2?'WASD / arrows steer · Space brake · R recover<br>Banked sweepers · Rolling crests · Gold hyper boosts · No payouts.':'WASD / arrows drive · Space brake · R recover<br>Original elevated circuit · No payouts.';cameraAnchor.set(car.x,car.y,car.z);camera.up.set(0,1,0);camera.position.set(car.x-Math.sin(car.yaw)*12,car.y+7,car.z-Math.cos(car.yaw)*12);}
  function recover(){const stats=track.generation>=2?{topSpeed:car.topSpeed,airtime:car.airtime}:{};const index=track.open?Math.max(0,track.points.findIndex(p=>p.id===checkpoint*30)):(checkpoint%8)*30;car=spawn(track,Math.min(index,track.segments.length-1));Object.assign(car,stats);if(started)elapsed+=3;}
  api.inspect=()=>({generation:track.generation||1,mode:track.mode,speed:car.speed,grounded:car.grounded,yaw:car.yaw,position:{x:car.x,y:car.y,z:car.z},fov:camera.fov,cameraDistance:camera.position.distanceTo(cameraAnchor),effects:effects.metrics(),resources:art.metrics(),blender:!!carModel.userData.blender,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles});
  function stop(){api.inspect=null;api.active=false;cancelAnimationFrame(raf);abort.abort();observer.disconnect();effects.dispose();art.disposeGroup(trackGroup);art.dispose();renderer.dispose();renderer.forceContextLoss();host.remove();for(const k of Object.keys(keys))keys[k]=false;}
  const controls={w:'up',arrowup:'up',s:'down',arrowdown:'down',a:'left',arrowleft:'left',d:'right',arrowright:'right',' ':'handbrake'};
  function key(e){const k=e.key.toLowerCase();if(e.target?.tagName==='SELECT'){e.stopImmediatePropagation();if(k!=='escape')return;}if(k==='tab'||k==='enter'||k==='f11'){e.stopImmediatePropagation();return;}if(e.type==='keydown'&&k==='escape'){e.preventDefault();e.stopImmediatePropagation();stop();return;}if(controls[k])input[controls[k]]=e.type==='keydown';if(e.type==='keydown'&&controls[k]==='up')effects.startAudio();if(e.type==='keydown'&&!e.repeat&&k==='r')recover();e.preventDefault();e.stopImmediatePropagation();}
  document.addEventListener('keydown',key,{capture:true,signal});document.addEventListener('keyup',key,{capture:true,signal});
  const clear=()=>{effects.pause();for(const k in input)input[k]=false;last=0;acc=0;};window.addEventListener('blur',clear,{signal});document.addEventListener('visibilitychange',clear,{signal});
  host.querySelector('.race-mode').onchange=host.querySelector('.race-generation').onchange=host.querySelector('.race-difficulty').onchange=e=>{reset(true);e.currentTarget.blur();};host.querySelector('[data-race="exit"]').onclick=stop;host.querySelector('[data-race="sound"]').onclick=e=>e.currentTarget.textContent=effects.toggle()?'Sound: off':'Sound: on';host.querySelector('[data-race="retry"]').onclick=()=>reset(false);host.querySelector('[data-race="new"]').onclick=()=>reset(true);
  for(const b of host.querySelectorAll('[data-key]')){b.onpointerdown=e=>{input[b.dataset.key]=true;effects.startAudio();b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>input[b.dataset.key]=false;}
  const observer=new ResizeObserver(()=>{const w=view.clientWidth,h=view.clientHeight;if(w&&h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}});observer.observe(view);
  const target=new THREE.Vector3(),surfaceUp=new THREE.Vector3(),cameraAnchor=new THREE.Vector3();reset(true);
  function frame(now){if(!api.active)return;raf=requestAnimationFrame(frame);if(document.hidden){last=0;return;}const dt=last?Math.min((now-last)/1000,.1):0;last=now;acc+=dt;
   while(acc>=1/120){if(input.up&&!finished)started=true;if(started&&!finished){elapsed+=1/120;const hit=step(car,track,input,1/120);if(track.open){if(car.grounded&&hit.distance<(track.width||12)/2)checkpoint=Math.max(checkpoint,Math.floor(track.points[hit.index].id/30));if(hit.index>180){extend(track);road();}}const next=((checkpoint+1)%8)*30;if(!track.open&&hit.distance<(track.width||12)/2&&Math.abs(hit.index-next)<=2&&car.grounded&&car.speed>0){checkpoint++;if(checkpoint===8){finished=true;car.speed=0;}}if(car.y< -8||hit.distance>65)recover();}acc-=1/120;}
   const under=nearest(track,car.x,car.z,car.y),segment=track.segments[under.index];if(track.generation>=2)art.poseCar(carModel,car,elapsed,car.speed,input);else art.poseCar(carModel,{...car,y:car.y-.55,roll:car.grounded?-under.bank:0,pitch:car.grounded?-Math.atan2(segment.q.y-segment.p.y,segment.len):-.06},elapsed,car.speed,input);
   mapCtx.drawImage(mapStatic,0,0);const gate=track.open?(track.points.find(p=>p.id===(checkpoint+1)*30)||track.points.at(-1)):track.points[((checkpoint+1)%8)*30];for(const [p,color,r]of [[gate,'#ffd275',4],[car,'#ffffff',3]]){mapCtx.fillStyle=color;mapCtx.beginPath();mapCtx.arc(p.x*mapScale+mapX,p.z*mapScale+mapZ,r,0,TAU);mapCtx.fill();}
   camera.position.x+=car.x-cameraAnchor.x;camera.position.y+=car.y-cameraAnchor.y;camera.position.z+=car.z-cameraAnchor.z;cameraAnchor.set(car.x,car.y,car.z);
   const chase=track.generation===1?10:7.2+Math.min(Math.abs(car.speed)/140,1)*.55;camera.fov=track.generation===1?65:58+Math.min(Math.abs(car.speed)/140,1)*4;camera.updateProjectionMatrix();if(track.generation>=2){const n=car.normal,f=car.forward;target.set(car.x-f.x*chase+n.x*2.8,car.y-f.y*chase+n.y*2.8,car.z-f.z*chase+n.z*2.8);camera.position.lerp(target,1-Math.exp(-8*dt));camera.up.copy(surfaceUp.set(n.x,n.y,n.z));camera.lookAt(car.x+f.x*7+n.x*.7,car.y+f.y*7+n.y*.7,car.z+f.z*7+n.z*.7);}else{camera.up.set(0,1,0);target.set(car.x-Math.sin(car.yaw)*chase,car.y+2.7,car.z-Math.cos(car.yaw)*chase);camera.position.lerp(target,1-Math.exp(-6*dt));camera.lookAt(car.x+Math.sin(car.yaw)*8,car.y+1,car.z+Math.cos(car.yaw)*8);}const cameraRoad=nearest(track,camera.position.x,camera.position.z,camera.position.y);if(cameraRoad.distance<track.width/2+2&&camera.position.y<cameraRoad.y+1.3)camera.position.y=cameraRoad.y+1.3;if(track.generation>=2)effects.update(car,input,dt);art.updateLighting(scene,car,elapsed);renderer.render(scene,camera);
   host.querySelector('.race-top small').textContent=track.generation>=2?'APEX / GENERATION '+track.generation+(track.generation===3?' · BLENDER':' · STUNTWORKS'):'APEX / FREE TIME TRIAL';const stuntText=host.querySelector('.race-stunts');stuntText.hidden=track.generation<2;if(track.generation>=2)stuntText.textContent=`Airtime ${car.airtime.toFixed(1)}s · Top ${Math.round(car.topSpeed*3.6)} km/h`;timeText.textContent=Math.floor(elapsed/60)+':'+(elapsed%60).toFixed(3).padStart(6,'0');speedText.textContent=Math.round(Math.abs(car.speed)*3.6)+' km/h'+(car.hyper?' · HYPER BOOST':car.boost?' · BOOST':track.generation>=2&&!car.grounded?' · AIR':track.generation>=2&&car.normal.y<-.5?' · AIR':track.generation>=2&&Math.abs(car.normal.y)<.95?' · BANKED TURN':'');progressText.textContent=finished?'FINISHED · Try another circuit!':!started?'Press W or Gas to start':track.open?`Endless · ${(track.points[under.index].id*5/1000).toFixed(2)} km · ${checkpoint} checkpoints`:`Checkpoint ${checkpoint} / 8 · Recovery +3s`;
  }raf=requestAnimationFrame(frame);
 };
})(globalThis);
