/* A pooled 3D naval scene: moonlit sailing, broadsides and an island approach. */
(function(){'use strict';const canvas=document.getElementById('titleBg'),login=document.getElementById('loginScreen');if(!canvas||!login)return;let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});}catch{canvas.style.background='linear-gradient(#0d1928,#12526b)';window.titleBg={start(){}};return;}
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.setClearColor(0x132637);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x132637,.008);const camera=new THREE.PerspectiveCamera(48,1,.1,400);scene.add(new THREE.HemisphereLight(0xa6d8ee,0x172228,1.7));const sun=new THREE.DirectionalLight(0xffd39c,2.1);sun.position.set(-35,60,-40);scene.add(sun);
const wood=new THREE.MeshStandardMaterial({color:0x603d2b,roughness:.9}),gold=new THREE.MeshStandardMaterial({color:0xb69554,metalness:.35,roughness:.6}),iron=new THREE.MeshStandardMaterial({color:0x29363e,metalness:.7,roughness:.4});
function box(g,w,h,d,mat,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);g.add(m);return m;}
function ship(pirate){const g=new THREE.Group();const shape=new THREE.Shape();shape.moveTo(-11,-3);shape.lineTo(7,-3.5);shape.quadraticCurveTo(12,-2,14,0);shape.quadraticCurveTo(12,2,7,3.5);shape.lineTo(-11,3);shape.closePath();const hull=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:2.5,bevelEnabled:true,bevelThickness:.6,bevelSize:.6,bevelSegments:2,steps:1}),wood);hull.rotation.x=Math.PI/2;hull.position.y=2.4;g.add(hull);box(g,22,.5,6.5,wood,0,2.5,0);box(g,5,3,5,wood,-7,4,0);box(g,5.6,.35,5.6,gold,-7,5.6,0);
 for(const side of [-1,1]){box(g,22,.4,.35,gold,0,3.2,side*3.1);for(let i=0;i<5;i++){const cannon=new THREE.Mesh(new THREE.CylinderGeometry(.35,.5,2.4,10),iron);cannon.rotation.x=Math.PI/2;cannon.position.set(-8+i*3.7,3,side*3.7);g.add(cannon);}}
 const sails=[];for(const x of [-3,5]){const mast=new THREE.Mesh(new THREE.CylinderGeometry(.2,.32,15,10),wood);mast.position.set(x,9,0);g.add(mast);box(g,.25,.25,11,wood,x,14,0);const sail=new THREE.Mesh(new THREE.PlaneGeometry(10,10,8,8),new THREE.MeshStandardMaterial({color:pirate?0x303542:0xe9ddbd,side:THREE.DoubleSide,roughness:1}));sail.rotation.y=Math.PI/2;sail.position.set(x,9.5,0);g.add(sail);sails.push(sail);const flag=new THREE.Mesh(new THREE.PlaneGeometry(3,1.4),new THREE.MeshBasicMaterial({color:pirate?0xc15750:0xd5ad50,side:THREE.DoubleSide}));flag.position.set(x+1.4,16,0);g.add(flag);}
 for(let i=0;i<5;i++){const body=new THREE.Mesh(new THREE.CapsuleGeometry(.3,.7,3,6),new THREE.MeshStandardMaterial({color:pirate?0x603c3c:0x355c70}));body.position.set(-6+i*3,3.4,i%2?1.7:-1.7);g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.3,8,6),new THREE.MeshStandardMaterial({color:0xc79269}));head.position.copy(body.position);head.position.y+=.8;g.add(head);}
 scene.add(g);return{g,sails};}
const hero=ship(false),enemy=ship(true);
const waterGeo=new THREE.PlaneGeometry(500,500,64,64);waterGeo.rotateX(-Math.PI/2);const water=new THREE.Mesh(waterGeo,new THREE.MeshStandardMaterial({color:0x1b657c,metalness:.55,roughness:.27}));scene.add(water);const positions=waterGeo.attributes.position;
const island=new THREE.Group();scene.add(island);island.position.set(65,-1,-45);const sand=new THREE.Mesh(new THREE.CylinderGeometry(22,27,4,24),new THREE.MeshStandardMaterial({color:0x9c9167}));island.add(sand);const grass=new THREE.Mesh(new THREE.CylinderGeometry(18,22,3,20),new THREE.MeshStandardMaterial({color:0x325d47}));grass.position.y=2;island.add(grass);for(let i=0;i<10;i++){const a=i*2.399,r=5+i%4*3;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.4,.7,8,6),wood);trunk.position.set(Math.cos(a)*r,6,Math.sin(a)*r);island.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(3.5,7,7),new THREE.MeshStandardMaterial({color:0x234c3e}));crown.position.copy(trunk.position);crown.position.y+=5;island.add(crown);}box(island,18,.5,4,wood,-25,2,8);
const flashes=[];for(let i=0;i<6;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),new THREE.MeshBasicMaterial({color:0xffba63,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false}));scene.add(m);flashes.push(m);}
const moon=new THREE.Mesh(new THREE.SphereGeometry(10,24,16),new THREE.MeshBasicMaterial({color:0xf4dab0}));moon.position.set(-95,72,-140);scene.add(moon);
let raf=0,last=0,time=0,lost=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
function resize(){const w=canvas.clientWidth||innerWidth,h=canvas.clientHeight||innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
function frame(stamp){raf=0;if(login.classList.contains('hidden')||document.hidden||lost){last=0;return;}if(last)time+=Math.min(.05,(stamp-last)/1000);last=stamp;const t=reduced.matches?7:time,a=t*Math.PI/30;
 hero.g.position.set(Math.sin(a)*24,Math.sin(t*1.4)*.3,Math.cos(a)*15);hero.g.rotation.set(Math.sin(t*1.1)*.025,-a+.3,Math.sin(t*.8)*.035);
 enemy.g.position.set(Math.sin(a+.5)*30,Math.sin(t*1.4+1)*.35,Math.cos(a+.5)*18-25);enemy.g.rotation.set(0,-a+.1,Math.sin(t)*.04);
 for(const boat of [hero,enemy])for(const sail of boat.sails){const p=sail.geometry.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);p.setZ(i,Math.sin((x+5)/10*Math.PI)*(.6+Math.sin(t*1.8+y*.2)*.15));}p.needsUpdate=true;}
 for(let i=0;i<positions.count;i++){const x=positions.getX(i),z=positions.getZ(i);positions.setY(i,Math.sin(x*.1+t)*.75+Math.sin(z*.13-t*1.2)*.55);}positions.needsUpdate=true;waterGeo.computeVertexNormals();
 const battle=(t%60)<25;for(let i=0;i<flashes.length;i++){const m=flashes[i],phase=(t*1.2+i*.14)%3;m.visible=battle&&phase<.5&&!reduced.matches;if(m.visible){const u=phase/.5;m.position.lerpVectors(hero.g.position,enemy.g.position,u);m.position.x+=(i-3)*2;m.position.y+=3+Math.sin(u*Math.PI)*3;m.scale.setScalar(.3+(1-u)*.45);}}
 camera.position.set(hero.g.position.x+36,24,hero.g.position.z+48);camera.lookAt(hero.g.position.x+23,7,hero.g.position.z-7);renderer.render(scene,camera);if(!reduced.matches)raf=requestAnimationFrame(frame);}
function start(){if(!raf&&!login.classList.contains('hidden')&&!document.hidden&&!lost){last=0;raf=requestAnimationFrame(frame);}}
window.addEventListener('resize',()=>{resize();start();});document.addEventListener('visibilitychange',start);new MutationObserver(start).observe(login,{attributes:true,attributeFilter:['class']});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;});canvas.addEventListener('webglcontextrestored',()=>{lost=false;start();});reduced.addEventListener('change',start);resize();window.titleBg={start};start();
})();
