'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),THREE={...require('./vendor/three.min')},S=require('./shared/sea');let scene,frame,hidden=false,clock=0;
THREE.WebGLRenderer=class{constructor(){this.domElement={addEventListener(){}};}setPixelRatio(){}setSize(w,h){this.domElement.width=w;this.domElement.height=h;}render(s,c){scene=s;s.updateMatrixWorld(true);c.updateMatrixWorld(true);}};
const canvas={clientWidth:1440,clientHeight:900,addEventListener(){}},login={classList:{contains:()=>hidden}},env={THREE,DARK_SEA:S,console,devicePixelRatio:1,innerWidth:1440,innerHeight:900,performance:{now:()=>clock},state:{area:'login'},keys:{},canvas,window:{addEventListener(){}},document:{hidden:false,getElementById:id=>id==='titleBg'?canvas:login,addEventListener(){},activeElement:{tagName:'BODY'}},matchMedia:()=>({matches:false,addEventListener(){}}),MutationObserver:class{observe(){}},requestAnimationFrame:f=>{frame=f;return 1;}};
env.atob=atob;env.window.DarkSeaLegendary={};const kitEnv={window:env.window};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../assets/dark-sea/legendary-models.js'),'utf8'),kitEnv);vm.createContext(env);for(const file of ['../assets/dark-sea/blender-animations.js','sea-animation.js'])vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,file),'utf8'),env);vm.runInContext(fs.readFileSync(path.join(__dirname,"../assets/dark-sea/blender-meshes.js"),"utf8"),env);vm.runInContext(fs.readFileSync(path.join(__dirname,'sea3d.js'),'utf8'),env);env.SeaGL=env.window.SeaGL;vm.runInContext(fs.readFileSync(path.join(__dirname,'sea-title.js'),'utf8'),env);let count;
for(let i=0;i<8;i++){clock+=120;frame(clock);const ship=scene.children.find(g=>g.userData.shipType==='brig'),beast=scene.children.find(g=>g.userData.great);assert(ship&&beast);assert.equal(ship.userData.sails.length,3);assert.equal(beast.userData.tentacles.length,24);assert.equal(beast.scale.x,S.KRAKEN_SCALE*3);assert(ship.position.x<0&&beast.position.x>0);count??=scene.children.length;assert.equal(scene.children.length,count);scene.traverse(o=>{if(o.geometry)assert([...o.geometry.attributes.position.array].every(Number.isFinite));});}
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),mark=html.match(/<svg class="seaWordmark"[\s\S]*?<\/svg>/)[0];assert(!mark.includes('<text'));assert((mark.match(/<path/g)||[]).length>=10);assert(html.includes('>PART 2<'));assert.equal((html.match(/src="js\/sea3d.js/g)||[]).length,1);assert(html.indexOf('src="js/sea3d.js')<html.indexOf('src="js/sea-title.js'));
console.log('PASS login reuses game brig and 24-arm Great model, animated finite geometry, bounded scene and original SVG title outlines');
const titleSource=fs.readFileSync(path.join(__dirname,'sea-title.js'),'utf8');assert(titleSource.includes('posing:true'));assert(!titleSource.includes('attack:{'));assert(!titleSource.includes('shells='));const boat=scene.children.find(g=>g.userData.shipType==='brig'),beast=scene.children.find(g=>g.userData.great);assert(beast.userData.greatArmor.length>=14);assert(Math.abs(boat.rotation.y+.6)<.001);for(const mount of boat.userData.cannons.filter(m=>m.userData.side===-1)){const base=mount.getWorldPosition(new THREE.Vector3()),tip=mount.localToWorld(new THREE.Vector3(0,0,1.4)),target=beast.position.clone().add(new THREE.Vector3(0,24,0)).sub(base).normalize();assert(tip.sub(base).normalize().dot(target)>.999);assert(boat.userData.gunPorts.includes(mount.position.x));}assert(html.includes('seaDepthsCrest'));assert(!html.includes('<div class="seaSigil"'));assert(html.includes('scrollDetails'));console.log('PASS staggered login feint pose, correct broadside gun aim, open gun ports, unique Great armor and aged parchment artwork');

// Follow every tube vertex through animation, including changes of Frenet seed axis.
let sawSpray=false,sawFeint=false;
let previous=beast.userData.tentacles.map(m=>Float32Array.from(m.geometry.attributes.position.array));
for(let step=0;step<180;step++){clock+=50;frame(clock);sawSpray ||= scene.children.some(o=>o.isInstancedMesh&&o.count>0);sawFeint ||= beast.userData.tentacles.some(m=>m.userData.titleImpact);beast.userData.tentacles.forEach((m,i)=>{assert(m.visible);const a=m.geometry.attributes.position.array;let jump=0;for(let k=0;k<a.length;k+=3)jump=Math.max(jump,Math.hypot(a[k]-previous[i][k],a[k+1]-previous[i][k+1],a[k+2]-previous[i][k+2]));assert(jump<.45,'Tentacle surface must move continuously, without frame flips');previous[i]=Float32Array.from(a);if(m.userData.claw)assert(m.userData.claw.visible);});}
assert(sawSpray&&sawFeint,'Title feints produce pooled water spray');
assert(html.includes('tentacles encircle a broken sail'));
console.log('PASS continuous tentacle surfaces and visible claws across nine seconds; nautical ship crest');

assert(beast.userData.mantle.geometry.userData.blenderAsset,'Login must use the Blender creature shell');assert(boat.userData.cannons.every(m=>m.children.some(c=>c.geometry?.userData.blenderAsset)),'Every cannon mount must contain Blender-authored geometry');

assert(boat.userData.legendaryShip,'Title must use the redesigned hull');assert(beast.userData.legendaryArmor,'Title must use the layered hero armor');assert(beast.userData.tentacles.filter(m=>m.userData.claw).every(m=>m.userData.claw.children.some(c=>c.userData.legendary==='talon')),'Every claw uses the serrated Blender talon');

for(const name of ['title-crest','title-wordmark','title-scroll']){const png=fs.readFileSync(path.join(__dirname,'../assets/dark-sea/'+name+'.png'));assert.equal(png.subarray(1,4).toString(),'PNG');assert.equal(png[25],6,'Rendered title art keeps RGBA transparency');assert(png.readUInt32BE(16)>=640);}
assert(html.includes('class="seaBlenderCrest"')&&html.includes('class="seaBlenderWordmark"'));
assert(fs.readFileSync(path.join(__dirname,'../style.css'),'utf8').includes('assets/dark-sea/title-scroll.png'));
console.log('PASS Blender rendered transparent title assets integrated into login');

const sail=boat.userData.sails[0],pos=sail.geometry.attributes.position;assert.equal(sail.position.y+sail.geometry.parameters.height/2,14,'Canvas head attaches to its yard');for(let i=0;i<pos.count;i++)if(Math.abs(pos.getY(i)-sail.geometry.parameters.height/2)<1e-6)assert(Math.abs(pos.getZ(i))<1e-6,'Billowing never detaches the canvas from the yard');assert.equal(boat.userData.flags.length,3);assert(boat.userData.lanterns.length===4);assert(!sail.children.some(o=>o.isLineSegments),'No rigid sail outline floats behind the moving cloth');
console.log('PASS attached sail heads, flexible pennants, hanging lanterns and no detached rigid outlines');
const beforeFrames=env.window.titleBg.metrics().frames;
for(let i=0;i<144;i++){clock+=1000/144;frame(clock);}
const metrics=env.window.titleBg.metrics();assert(metrics.frames-beforeFrames<=31,'High-refresh screens do not over-render the login');assert(metrics.frames-beforeFrames>=25,'Animation continues at cinematic cadence');assert(metrics.width<=1280&&metrics.height<=900,'Background render size is bounded');
hidden=true;const stopped=metrics.frames;clock+=100;frame(clock);assert.equal(env.window.titleBg.metrics().frames,stopped,'Login does no rendering after entering the game');hidden=false;
console.log('PASS bounded title resolution, 144Hz frame pacing and hidden-login suspension');
