/* Timestamped presentation snapshots. All aboard transforms share one interpolated ship pose. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.SeaMotion=factory();})(typeof globalThis==='undefined'?this:globalThis,function(){
'use strict';
function create(){let frames=[],lastClock=0;const lerp=(a,b,t)=>a+(b-a)*t,angle=(a,b,t)=>a+Math.atan2(Math.sin(b-a),Math.cos(b-a))*t;
 function push(v,at){if(!v?.multiplayer)return;const prior=frames.at(-1);if(prior&&prior.v.room===v.room&&((v.simTime??v.serverNow)<prior.stamp||(v.me?.bodyRevision||0)<(prior.v.me?.bodyRevision||0)))return;if(frames.length&&(v.room!==frames.at(-1).v.room||['place','boarded','bodyRevision','cave'].some(k=>v.me?.[k]!==frames.at(-1).v.me?.[k]))){frames=[];lastClock=0;}const stamp=v.simTime??v.serverNow;if(frames.length&&stamp<frames.at(-1).stamp)return;const frame={v,at,stamp};if(frames.at(-1)?.stamp===stamp)frames[frames.length-1]=frame;else frames.push(frame);frames=frames.slice(-6);}
 function sample(at){if(!frames.length)return null;const latest=frames.at(-1),clock=latest.stamp+Math.min(150,Math.max(0,at-latest.at))-100;lastClock=Math.max(lastClock,clock);let a=frames[0],b=latest;for(let i=1;i<frames.length;i++)if(frames[i].stamp>=lastClock){a=frames[i-1];b=frames[i];break;}const t=Math.max(0,Math.min(1,(lastClock-a.stamp)/Math.max(1,b.stamp-a.stamp))),v={...latest.v};
 const blend=(old,next,fields=['x','y','a'])=>{const out={...next};if(!old)return out;for(const k of fields)if(Number.isFinite(old[k])&&Number.isFinite(next[k]))out[k]=/A$|^a$/.test(k)?angle(old[k],next[k],t):lerp(old[k],next[k],t);return out;};
 const pose=blend(a.v,b.v,['shipX','shipY','shipA','a','speed']);for(const k of ['shipX','shipY','shipA','a','speed'])v[k]=pose[k];v.me={...latest.v.me};v.receivedAt=latest.at;v.serverNow=latest.v.serverNow;v.entities=latest.v.entities.map(e=>{const aa=a.v.entities.find(x=>x.id===e.id),bb=b.v.entities.find(x=>x.id===e.id)||e;const pose=blend(aa,bb);return {...e,x:pose.x,y:pose.y,a:pose.a};});
 const shipFor=p=>p.boarded?v.entities.find(e=>e.id===p.boarded):p.room===v.room?{x:v.shipX,y:v.shipY,a:v.shipA}:v.entities.find(e=>e.id===p.room);
 v.crew=latest.v.crew.map(p=>{const aa=a.v.crew.find(q=>q.user===p.user),bb=b.v.crew.find(q=>q.user===p.user)||p;const q=aa&&['place','boarded','bodyRevision','cave'].every(k=>aa[k]===p[k]&&bb[k]===p[k])?{...p,...blend(aa,bb)}:{...p};const ship=shipFor(q);if(ship&&q.place!=='island'){q.worldX=ship.x+2*(Math.cos(ship.a)*q.x-Math.sin(ship.a)*q.y);q.worldY=ship.y+2*(Math.sin(ship.a)*q.x+Math.cos(ship.a)*q.y);q.shipA=ship.a;}else if(q.place==='island'){q.worldX=q.x;q.worldY=q.y;}return q;});
 v.companions=(latest.v.companions||[]).map(p=>{const old=(a.v.companions||[]).find(q=>q.user===p.user),next=(b.v.companions||[]).find(q=>q.user===p.user)||p,q=old&&['place','boarded','cave'].every(k=>old[k]===p[k]&&next[k]===p[k])?{...p,...blend(old,next)}:{...p},ship=shipFor(q);if(ship&&q.place!=='island'){q.worldX=ship.x+2*(Math.cos(ship.a)*q.x-Math.sin(ship.a)*q.y);q.worldY=ship.y+2*(Math.sin(ship.a)*q.x+Math.cos(ship.a)*q.y);}else{q.worldX=q.x;q.worldY=q.y;}return q;});
 v.defenders=(latest.v.defenders||[]).map(g=>{const old=(a.v.defenders||[]).find(q=>q.id===g.id),next=(b.v.defenders||[]).find(q=>q.id===g.id)||g,body=v.entities.find(e=>e.id===g.shipId);return {...g,...blend(old,next),...(body?{shipX:body.x,shipY:body.y,shipA:body.a}:{})};});
 const me=v.crew.find(p=>p.user===v.self);if(me&&me.place===v.me.place&&me.role===v.me.role)Object.assign(v.me,me);const body=shipFor(v.me)||{x:v.shipX,y:v.shipY,a:v.shipA};v.interior={...v.interior,x:body.x,y:body.y,a:body.a};v.a=v.shipA;v.x=v.me.role==='captain'?v.shipX:v.me.worldX??v.x;v.y=v.me.role==='captain'?v.shipY:v.me.worldY??v.y;return v;
 }
 return{push,sample,reset(){frames=[];lastClock=0;}};
}return{create};});
