/* A pooled 3D naval scene: moonlit sailing, broadsides and an island approach. */
(function(){'use strict';const canvas=document.getElementById('titleBg'),login=document.getElementById('loginScreen');if(!canvas||!login)return;let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});}catch{canvas.style.background='linear-gradient(#0d1928,#12526b)';window.titleBg={start(){}};return;}
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.setClearColor(0x081c2c);
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x12384a,.0045);const camera=new THREE.PerspectiveCamera(48,1,.1,400);scene.add(new THREE.HemisphereLight(0x849cce,0x101b27,.65));const sun=new THREE.DirectionalLight(0x91a7d0,.85);sun.position.set(-35,60,-40);scene.add(sun);
const wood=new THREE.MeshStandardMaterial({color:0x603d2b,roughness:.9}),gold=new THREE.MeshStandardMaterial({color:0xb69554,metalness:.35,roughness:.6}),iron=new THREE.MeshStandardMaterial({color:0x29363e,metalness:.7,roughness:.4});
const plankCanvas=document.createElement('canvas');plankCanvas.width=256;plankCanvas.height=256;const plankCtx=plankCanvas.getContext('2d');plankCtx.fillStyle='#96704a';plankCtx.fillRect(0,0,256,256);for(let y=0;y<256;y+=32){plankCtx.fillStyle=y%64?'#a57a4c':'#89623e';plankCtx.fillRect(0,y,256,31);plankCtx.fillStyle='#382b23';plankCtx.fillRect(0,y,256,1);plankCtx.fillRect(y%64?80:180,y,1,32);}for(let i=0;i<500;i++){plankCtx.fillStyle='rgba(48,29,17,.08)';plankCtx.fillRect((i*73)%256,(i*113)%256,10+i%27,1);}const plankTex=new THREE.CanvasTexture(plankCanvas);plankTex.wrapS=plankTex.wrapT=THREE.RepeatWrapping;plankTex.repeat.set(3,2);wood.map=plankTex;wood.color.setHex(0xba9970);
function line(g,a,b){const m=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,a.distanceTo(b),5),iron);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());g.add(m);}
function box(g,w,h,d,mat,x,y,z){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);g.add(m);return m;}
function ship(pirate){const g=new THREE.Group();const shape=new THREE.Shape();shape.moveTo(-11,-3);shape.lineTo(7,-3.5);shape.quadraticCurveTo(12,-2,14,0);shape.quadraticCurveTo(12,2,7,3.5);shape.lineTo(-11,3);shape.closePath();const hull=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:2.5,bevelEnabled:true,bevelThickness:.6,bevelSize:.6,bevelSegments:2,steps:1}),wood);hull.rotation.x=Math.PI/2;hull.position.y=2.4;g.add(hull);box(g,22,.5,6.5,wood,0,2.5,0);box(g,3,.08,2.5,iron,0,2.83,0);box(g,.3,1.8,.3,wood,-8,3.5,0);const wheel=new THREE.Mesh(new THREE.TorusGeometry(.75,.12,6,14),gold);wheel.position.set(-8,4,0);wheel.rotation.y=Math.PI/2;g.add(wheel);
 for(const side of [-1,1]){box(g,22,.4,.35,gold,0,3.2,side*3.1);for(let i=0;i<5;i++){const cannon=new THREE.Mesh(new THREE.CylinderGeometry(.35,.5,2.4,10),iron);cannon.rotation.x=Math.PI/2;cannon.position.set(-8+i*3.7,3,side*3.7);g.add(cannon);}}
 for(const side of [-1,1]){for(let x=-10;x<11;x+=2.5)box(g,.12,.8,.12,gold,x,3.35,side*3.2);for(const mastX of [-3,5])for(const footX of [-10,10])line(g,new THREE.Vector3(mastX,15,0),new THREE.Vector3(footX,3,side*3));box(g,3,.12,.12,gold,0,2.95,side*1.3);box(g,.12,.12,2.6,gold,side*1.5,2.95,0);}
 const crew=[];const sails=[];for(const x of [-3,5]){const mast=new THREE.Mesh(new THREE.CylinderGeometry(.2,.32,15,10),wood);mast.position.set(x,9,0);g.add(mast);box(g,.25,.25,11,wood,x,14,0);const sail=new THREE.Mesh(new THREE.PlaneGeometry(10,10,8,8),new THREE.MeshStandardMaterial({color:pirate?0x303542:0xe9ddbd,side:THREE.DoubleSide,roughness:1}));sail.rotation.y=Math.PI/2;sail.position.set(x,9.5,0);g.add(sail);sails.push(sail);const flag=new THREE.Mesh(new THREE.PlaneGeometry(3,1.4),new THREE.MeshBasicMaterial({color:pirate?0xc15750:0xd5ad50,side:THREE.DoubleSide}));flag.position.set(x+1.4,16,0);g.add(flag);}
 for(let i=0;i<4;i++){const person=new THREE.Group();g.add(person);const uniform=new THREE.MeshStandardMaterial({color:pirate?0x9b4c48:0x457d92});const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.18,.5,3,6),uniform);torso.position.y=.7;person.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.18,8,6),new THREE.MeshStandardMaterial({color:0xd2ae7e}));head.position.y=1.2;person.add(head);for(const side of [-1,1])box(person,.15,.4,.18,iron,side*.12,.2,0);person.position.set(-8+i*4,2.8,i%2?1.5:-1.5);crew.push(person);}
 scene.add(g);return{g,sails,crew};}
const hero=ship(false),enemy=ship(true);
const waterGeo=new THREE.PlaneGeometry(500,500,64,64);waterGeo.rotateX(-Math.PI/2);const water=new THREE.Mesh(waterGeo,new THREE.MeshStandardMaterial({color:0x092a3b,metalness:.3,roughness:.44}));scene.add(water);const positions=waterGeo.attributes.position;
const island=new THREE.Group();scene.add(island);island.position.set(105,-1,-85);island.scale.set(2.2,1,2.2);const sand=new THREE.Mesh(new THREE.CylinderGeometry(22,27,4,24),new THREE.MeshStandardMaterial({color:0x9c9167}));island.add(sand);const grass=new THREE.Mesh(new THREE.CylinderGeometry(18,22,3,20),new THREE.MeshStandardMaterial({color:0x325d47}));grass.position.y=2;island.add(grass);for(let i=0;i<10;i++){const a=i*2.399,r=5+i%4*3;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.4,.7,8,6),wood);trunk.position.set(Math.cos(a)*r,6,Math.sin(a)*r);island.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(3.5,7,7),new THREE.MeshStandardMaterial({color:0x234c3e}));crown.position.copy(trunk.position);crown.position.y+=5;island.add(crown);}box(island,18,.5,4,wood,-25,2,8);
const mountains=new THREE.Group();scene.add(mountains);for(let i=0;i<7;i++){const peak=new THREE.Mesh(new THREE.ConeGeometry(17+i%3*4,28+i%4*9,9),new THREE.MeshStandardMaterial({color:0x263944,roughness:1}));peak.position.set(75+i*12,14+i%4*4,-105-i%2*18);mountains.add(peak);}const rainGeo=new THREE.BufferGeometry(),rainPoints=[];for(let i=0;i<400;i++)rainPoints.push(Math.sin(i*27)*150,Math.random()*85,Math.cos(i*31)*150);rainGeo.setAttribute('position',new THREE.Float32BufferAttribute(rainPoints,3));const rain=new THREE.Points(rainGeo,new THREE.PointsMaterial({color:0xb0c4df,size:.22,transparent:true,opacity:.45}));scene.add(rain);
const flashes=[];for(let i=0;i<6;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),new THREE.MeshBasicMaterial({color:0xffba63,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false}));scene.add(m);flashes.push(m);}
const moon=new THREE.Mesh(new THREE.SphereGeometry(10,24,16),new THREE.MeshBasicMaterial({color:0xf4dab0}));moon.position.set(-95,72,-140);scene.add(moon);
// Stars, distant surfacing arms, and lighthouse silhouette frame the naval battle.
const starsGeo=new THREE.BufferGeometry(),stars=[];for(let i=0;i<220;i++){const a=i*2.399,el=.2+(i%37)/37;stars.push(Math.cos(a)*220,35+el*130,Math.sin(a)*220);}starsGeo.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));scene.add(new THREE.Points(starsGeo,new THREE.PointsMaterial({color:0xc9e8ed,size:.3,transparent:true,opacity:.8})));
box(island,3,14,3,wood,0,10,0);box(island,4,.5,4,gold,0,17,0);const beacon=new THREE.PointLight(0xffd38b,5,90);beacon.position.set(105,17,-85);scene.add(beacon);
const arms=[];for(let i=0;i<8;i++){const a=i*Math.PI/4,points=[];for(let j=0;j<=16;j++){const u=j/16;points.push(new THREE.Vector3(Math.cos(a)*(4+u*12),Math.sin(u*Math.PI)*(8+i%3),Math.sin(a)*(4+u*12)));}const arm=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),40,.7,7,false),new THREE.MeshStandardMaterial({color:0x225765,roughness:.6}));arm.position.set(-30,-1,-90);arm.userData.rest=new Float32Array(arm.geometry.attributes.position.array);scene.add(arm);arms.push(arm);}
const leviHead=new THREE.Group();scene.add(leviHead);leviHead.position.set(-30,2,-90);const leviHide=new THREE.MeshStandardMaterial({color:0x194957,roughness:.5}),leviLight=new THREE.MeshBasicMaterial({color:0x72e6eb});const hood=new THREE.Mesh(new THREE.SphereGeometry(1,24,16),leviHide);hood.position.y=4;hood.scale.set(5,4.5,6);leviHead.add(hood);for(const side of [-1,1])for(let i=0;i<4;i++){const mark=new THREE.Mesh(new THREE.SphereGeometry(.22,8,6),leviLight);mark.position.set(side*(.7+i*.6),7-i*.6,3.8);leviHead.add(mark);}
const impacts=[];for(let i=0;i<6;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(1,10,8),new THREE.MeshBasicMaterial({color:0xffc586,transparent:true,opacity:0,depthWrite:false}));scene.add(m);impacts.push(m);}
let raf=0,last=0,time=0,lost=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
function resize(){const w=canvas.clientWidth||innerWidth,h=canvas.clientHeight||innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
function frame(stamp){raf=0;if(login.classList.contains('hidden')||document.hidden||lost){last=0;return;}if(last)time+=Math.min(.05,(stamp-last)/1000);last=stamp;const t=reduced.matches?7:time,a=t*Math.PI/30;
 const drops=rainGeo.attributes.position;for(let i=0;i<drops.count;i++)drops.setY(i,((85+i*.71-t*32)%85+85)%85);drops.needsUpdate=true;const course=t*.022,px=Math.sin(course)*35,pz=Math.cos(course)*12,heading=Math.atan2(-Math.sin(course)*12,Math.cos(course)*35);
 hero.g.position.set(px,Math.sin(t*1.2)*.12,pz);hero.g.rotation.set(Math.sin(t*1.2)*.018,-heading,Math.sin(t*.8)*.012,'YXZ');
 enemy.g.position.set(px+34,Math.sin(t*1.2+1)*.12,pz-44);enemy.g.rotation.set(0,-heading,Math.sin(t+.3)*.012);
 for(const [bi,boat] of [hero,enemy].entries())boat.crew.forEach((p,i)=>{p.position.x=-8+i*4+Math.sin(t*.7+i)*1.2;p.position.z=(i%2?1:-1)*(1.3+Math.sin(t+i)*.25);p.position.y=2.8+Math.abs(Math.sin(t*5+i))*.025;});
 leviHead.position.y=2+Math.sin(t*.8)*.4;leviHead.rotation.y=Math.sin(t*.3)*.1;for(const [i,arm] of arms.entries()){const p=arm.geometry.attributes.position,rest=arm.userData.rest;for(let j=0;j<p.count;j++){const x=rest[j*3],y=rest[j*3+1],z=rest[j*3+2],weight=Math.max(0,(Math.hypot(x,z)-4)/12);p.setXYZ(j,x+Math.sin(t*.8-weight*5+i)*weight,y+Math.sin(t*1.2-weight*6+i)*weight*.8,z);}p.needsUpdate=true;arm.geometry.computeVertexNormals();}
 for(const boat of [hero,enemy])for(const sail of boat.sails){const p=sail.geometry.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);p.setZ(i,Math.sin((x+5)/10*Math.PI)*(.6+Math.sin(t*1.8+y*.2)*.15));}p.needsUpdate=true;}
 for(let i=0;i<positions.count;i++){const x=positions.getX(i),z=positions.getZ(i);positions.setY(i,Math.sin(x*.1+t)*.75+Math.sin(z*.13-t*1.2)*.55);}positions.needsUpdate=true;waterGeo.computeVertexNormals();
 hero.g.updateMatrixWorld(true);enemy.g.updateMatrixWorld(true);for(let i=0;i<flashes.length;i++){const m=flashes[i],impact=impacts[i],phase=(t+i*.17)%4,source=i<3?hero:enemy,target=i<3?enemy:hero,from=new THREE.Vector3(-5+(i%3)*4,3,i<3?-4:4).applyMatrix4(source.g.matrixWorld),to=new THREE.Vector3(-5+(i%3)*4,2,i<3?3:-3).applyMatrix4(target.g.matrixWorld);m.visible=phase<.9&&!reduced.matches;impact.visible=phase>=.9&&phase<1.65&&!reduced.matches;if(m.visible){const u=phase/.9;m.position.lerpVectors(from,to,u);m.position.y+=Math.sin(u*Math.PI)*2.8;m.scale.setScalar(.2);}if(impact.visible){const u=(phase-.9)/.75;impact.position.copy(to);impact.position.y+=u*2;impact.scale.setScalar(.3+u*2.6);impact.material.color.setHex(u<.35?0xffd38c:0x455057);impact.material.opacity=(1-u)*.8;}}
 camera.position.set(hero.g.position.x+32+Math.sin(t*.04)*4,24,hero.g.position.z+48);camera.lookAt(hero.g.position.x+14,5,hero.g.position.z-18);renderer.render(scene,camera);if(!reduced.matches)raf=requestAnimationFrame(frame);}
function start(){if(!raf&&!login.classList.contains('hidden')&&!document.hidden&&!lost){last=0;raf=requestAnimationFrame(frame);}}
window.addEventListener('resize',()=>{resize();start();});document.addEventListener('visibilitychange',start);new MutationObserver(start).observe(login,{attributes:true,attributeFilter:['class']});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;});canvas.addEventListener('webglcontextrestored',()=>{lost=false;start();});reduced.addEventListener('change',start);resize();window.titleBg={start};start();
})();
