/* Dark Sea sailing client: sends controls, never positions or reward amounts. */
(function(){'use strict';
const S=DARK_SEA;let data=null,pending=false,next=0,previous=null,lastNotice='',hud=null,active=false,inputPending=false,lastControls='';
const fmt=n=>Math.round(n||0).toLocaleString();
function ensureHud(){if(hud)return;hud=document.createElement('div');hud.id='seaHud';document.getElementById('stage').appendChild(hud);hud.innerHTML='<div id="seaReadout"></div><div class="seaActions"><button data-sea="fire">Sword [Space / click]</button><button data-sea="port">Port [Q]</button><button data-sea="starboard">Starboard [E]</button><button data-sea="recruit">Rescue recruit [G]</button><button data-sea="interact">Land / loot / board [F]</button><button data-sea="repair">Repair · 500 coins [R]</button><button data-sea="auto">Crew auto-fire [C]</button><button data-sea="return">Unload at home [H]</button><button data-sea="rescue">Abandon cargo & return</button></div>';
hud.querySelectorAll('button').forEach(b=>b.onclick=()=>act(b.dataset.sea));}
function adopt(result){data=result;if(result.voyage)result.voyage.receivedAt=performance.now();if(state.data&&result.money!=null){state.data.money=result.money;updateHUD();}
 if(result.ended||active&&!result.voyage){active=false;window.SeaGL?.reset();if(previous){state.area=previous.area;state.pos={...previous.pos};}else state.area='neighborhood';if(hud)hud.hidden=true;toast(result.reason||'Your voyage ended. Unbanked cargo is lost.',5000);return;}
 if(result.voyage){const v=result.voyage;if(v.notice&&v.notice!==lastNotice){lastNotice=v.notice;toast(v.notice,3500);}ensureHud();hud.hidden=false;hud.querySelectorAll('[data-sea]').forEach(b=>{b.hidden=b.dataset.sea==='fire'?!v.onFoot:['port','starboard','auto','repair'].includes(b.dataset.sea)?!!v.onFoot:false;});document.getElementById('seaReadout').innerHTML=`<b>THE DARK SEA · ${S.SHIPS[v.ship].name}</b><div class="seaVitals"><label>HULL <b>${fmt(v.hp)} / ${fmt(v.stats.durability)}</b><i style="--fill:${Math.max(0,Math.min(100,v.hp/v.stats.durability*100))}%"></i></label><label>BOOST <b>${fmt(v.magic)} / ${fmt(v.stats.magicStorage)}</b><i style="--fill:${Math.max(0,Math.min(100,v.magic/v.stats.magicStorage*100))}%"></i></label><label>HOLD <b>${v.cargo.length} / ${v.stats.cargo}</b></label></div><span>Gems ${fmt(result.profile.gems)} · Reputation ${fmt(result.profile.reputation)} · ${S.RECRUITS[v.crewId]?.name||'Solo captain'} ${v.auto?'· AUTO':''} · ${Math.ceil(v.remaining/60000)} min left</span><small class="seaReload">PORT ${v.reloadLeft?.port>0?(v.reloadLeft.port/1000).toFixed(1)+'s':'READY'} · STARBOARD ${v.reloadLeft?.starboard>0?(v.reloadLeft.starboard/1000).toFixed(1)+'s':'READY'}</small><small>Hold right mouse: locked-cursor look · Arrow keys: look · Release / Esc: free cursor · ${v.onFoot?'WASD: camera-relative walk · Space / click: sword · dodge red tells · F: loot / board':'W/S: sails · A/D: rudder · Shift: ram speed · Q/E: port/starboard · first-person deck view · align the aim lanes'}</small>`;}}
async function act(action,extra={}){if(action==='fire'&&!data?.voyage?.onFoot)return;if(pending)return;pending=true;try{const result=await netSea({action:['port','starboard'].includes(action)?'fire':action,...(action==='port'?{side:-1}:action==='starboard'?{side:1}:{}),...extra});adopt(result);if(['buy','crew_equip','upgrade','equip'].includes(action))await renderHarbor(result);}catch(e){toast(e.message,2500);if(active&&/No active voyage/.test(e.message))adopt({ended:true,reason:'Voyage ended or disconnected. Unbanked cargo was lost.'});}finally{pending=false;}}
async function harbor(){if(state.area!=='neighborhood'||!(gameWorld.buildingAtPlayer()?.type==='shipwright'||gameWorld.activityAtPlayer()?.type==='shipwright')){toast('Visit the Shipwright at the east harbor. Use Town Map for directions.');return;}if(state.area==='dungeon'||state.area==='duel'){toast('Finish your current fight before visiting the Shipwright.');return;}if(active){toast('Follow the home compass to unload, or use Abandon cargo & return.');return;}try{data=await netSea({action:'status'});await renderHarbor(data);}catch(e){toast(e.message);}}
async function renderHarbor(r){const p=r.profile;openMenu('THE DARK SEA · SHIPWRIGHT',`<div class="seaHarbor"><p class="seaEyebrow">NEIGHBORHOOD HARBOR</p><h2>Your next horizon awaits.</h2><p>${fmt(r.money)} coins · <b>${fmt(p.gems)} gems</b> · ${fmt(p.reputation)} sailing reputation</p><p class="muted">Explore islands, fight pirates and Great Krakens. Sealed chests stay in your hold until you sail home and unload. Sinking, disconnecting or abandoning the voyage loses unbanked cargo. Voyages last up to 45 minutes; 90 seconds without updates (including a background tab) also ends the voyage.</p><button class="seaSail" id="seaSail" ${!p.ship?'disabled':''}>SET SAIL</button><div class="seaFleet">${Object.entries(S.SHIPS).map(([id,s])=>`<article><h3>${s.name}${p.ship===id?' · ACTIVE':''}</h3><p>${s.coins?fmt(s.coins)+' coins':fmt(s.gems)+' gems'}</p><p>${s.durability} hull · ${s.cannons} cannons · ${s.cargo} cargo</p><details><summary>All ship stats</summary><dl>${Object.entries(S.STATS).map(([key,label])=>`<div><dt>${label}</dt><dd>${p.ship===id?S.stats(p)[key]:s[key]}</dd></div>`).join('')}</dl></details><button data-action="${p.owned.includes(id)?'equip':'buy'}" data-ship="${id}" ${p.ship===id?'disabled':''}>${p.ship===id?'Active ship':p.owned.includes(id)?'Select ship':'Buy ship'}</button></article>`).join('')}</div><h3>Fleet refits</h3><p>Refits apply to your active ship. Five levels each.</p><div class="seaRefits">${['hull','sails','cannons'].map(slot=>`<button data-action="upgrade" data-slot="${slot}" ${(p.upgrades[slot]||0)>=5?'disabled':''}>${slot} ${p.upgrades[slot]||0}/5 · ${35*((p.upgrades[slot]||0)+1)} gems</button>`).join('')}</div><h3>Your rescued crew</h3><p>Rare signal camps appear on islands. Defeat their defenders, approach the recruit and press G. Recruits stay permanently in your roster. Assign one specialist here; every recruited specialist can man the cannons.</p><p>Assigned: <b>${S.RECRUITS[p.activeCrew]?.name||'Solo captain'}</b></p><div class="seaCrewRoster">${(p.roster||[]).map(id=>{const c=S.RECRUITS[id];return `<article class="seaCrew tier${c.tier}"><small>${S.CREW_TIERS[c.tier-1]}</small><h3>${c.name}</h3><p>${c.description}</p><button data-action="crew_equip" data-crew="${id}" ${id===p.activeCrew?'disabled':''}>${id===p.activeCrew?'Assigned':'Assign specialist'}</button></article>`;}).join('')||'<p class="muted">No recruits yet. Watch the chart for gold camp markers while exploring.</p>'}</div><hr><p>Home is always marked on your compass. Rough seas intensify farther out; stability protects your hull. Wind affects speed; resilience helps. Shift uses boost reserves for ramming. Q fires port, E fires starboard, and only one broadside fires at a time. Cannonballs travel straight out from the hull; the aim lanes show their path. Repairs cost 500 coins.</p></div>`,true);
document.querySelectorAll('.seaHarbor [data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action,{ship:b.dataset.ship,slot:b.dataset.slot,crew:b.dataset.crew}));document.getElementById('seaSail').onclick=async()=>{if(pending)return;pending=true;try{const r=await netSea({action:'sail'});previous={area:state.area,pos:{...state.pos}};active=true;window.SeaGL?.reset();state.area='sea';state.buildMode=false;document.getElementById('tutorial')?.classList.add('hidden');closeMenu();if(typeof setPhone==='function')setPhone(false);adopt(r);}catch(e){toast(e.message);}finally{pending=false;}};}
function key(e){if(['input','textarea'].includes(document.activeElement.tagName.toLowerCase()))return;e.preventDefault();if(e.repeat)return;const map={' ':'fire',q:'port',e:'starboard',g:'recruit',f:'interact',r:'repair',c:'auto',h:'return'};if(map[e.key.toLowerCase()])act(map[e.key.toLowerCase()]);}
function controls(){const typing=['input','textarea'].includes(document.activeElement.tagName.toLowerCase());return{forward:!typing&&!!keys.w,back:!typing&&!!keys.s,left:!typing&&!!keys.a,right:!typing&&!!keys.d,boost:!typing&&!!keys.shift,walkAngle:(window.SeaGL?.getYaw?.()??Math.PI/2)+Math.PI};}
function update(){if(!active||inputPending)return;const input=controls(),signature=JSON.stringify(input);if(Date.now()<next&&signature===lastControls)return;next=Date.now()+100;lastControls=signature;inputPending=true;
 // Movement has its own request lane: firing and looting cannot swallow a key change.
 netSea({action:'input',input}).then(r=>{if(active)adopt(r);}).catch(e=>{if(active&&/No active voyage/.test(e.message))adopt({ended:true,reason:'Voyage ended or disconnected.'});}).finally(()=>{inputPending=false;});}
function visualVoyage(v){if(!v.stats||v.simTime==null)return v;const copy={...v},dt=Math.min(.2,Math.max(0,((v.serverNow-v.simTime)+performance.now()-v.receivedAt)/1000));
 if(v.onFoot){const island=v.entities.find(e=>e.id===v.onFoot);if(island)S.moveFoot(copy,controls(),dt,island);}else{S.moveShip(copy,controls(),dt);S.clearWater(copy,S.hullRadius(copy.ship),S.obstacles(v.entities));}return copy;
}
function ship(x,y,a,type,pirate=false){const s=S.SHIPS[type]||S.SHIPS.sailboat,scale=.75+s.cannons*.025;ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.scale(scale,scale);ctx.fillStyle='#071a22';ctx.beginPath();ctx.ellipse(0,8,47,24,0,0,Math.PI*2);ctx.fill();const g=ctx.createLinearGradient(0,-24,0,24);g.addColorStop(0,pirate?'#562f34':'#976239');g.addColorStop(.5,pirate?'#9b5450':'#d6a15e');g.addColorStop(1,'#452d27');ctx.fillStyle=g;ctx.strokeStyle='#211c20';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(52,0);ctx.quadraticCurveTo(12,-29,-39,-21);ctx.lineTo(-43,21);ctx.quadraticCurveTo(12,29,52,0);ctx.fill();ctx.stroke();for(let i=0;i<s.cannons/2;i++)for(const side of [-1,1]){ctx.fillStyle='#202b32';ctx.fillRect(-28+i*50/Math.ceil(s.cannons/2),side*20-4,9,12);}for(let i=0;i<(type==='sailboat'?1:2);i++){const xx=i*27-8;ctx.strokeStyle='#4b3024';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(xx,-21);ctx.lineTo(xx,21);ctx.stroke();ctx.fillStyle=pirate?'#292936':'#e8d3a4';ctx.beginPath();ctx.moveTo(xx,-19);ctx.quadraticCurveTo(xx+23,0,xx,19);ctx.closePath();ctx.fill();}ctx.restore();}
function draw(){const raw=data?.voyage;if(!raw)return;const v=visualVoyage(raw);const w=canvas.width,h=canvas.height,t=Date.now(),zoom=v.onFoot?1.15:.85;
 const rendered3D=window.SeaGL?.draw(ctx,v,w,h);if(!rendered3D){ctx.fillStyle='#122132';ctx.fillRect(0,0,w,h);ctx.fillStyle='#eaf2f8';ctx.font='20px sans-serif';ctx.textAlign='center';ctx.fillText('3D needs WebGL. Enable hardware acceleration and reload.',w/2,h/2);return;}
 // Compass and local chart never expose undiscovered distant world sectors.
 const mx=w-120,my=145;ctx.fillStyle='rgba(4,17,29,.8)';ctx.beginPath();ctx.arc(mx,my,82,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#a99970';ctx.stroke();ctx.save();ctx.beginPath();ctx.arc(mx,my,76,0,Math.PI*2);ctx.clip();for(const e of v.entities){ctx.fillStyle=e.kind==='island'?'#8dae77':e.kind==='pirate'?'#ef9a6b':'#c0a0de';ctx.fillRect(mx+(e.x-v.x)/15-3,my+(e.y-v.y)/15-3,6,6);if(e.recruit&&!e.recruit.recruited){ctx.fillStyle='#ffe79a';ctx.beginPath();ctx.arc(mx+(e.x-v.x)/15,my+(e.y-v.y)/15,5,0,Math.PI*2);ctx.strokeStyle='#ffe79a';ctx.stroke();}}ctx.restore();ctx.fillStyle='#fff0ac';ctx.beginPath();ctx.arc(mx,my,4,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(mx,my);ctx.rotate(v.a);ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-5,-6);ctx.lineTo(-5,6);ctx.closePath();ctx.fill();ctx.restore();ctx.font='12px Georgia';ctx.fillText('N',mx,my-65);const bearing=Math.atan2(-v.y,-v.x);ctx.save();ctx.translate(mx,my);ctx.rotate(bearing);ctx.fillStyle='#f0cc70';ctx.beginPath();ctx.moveTo(67,0);ctx.lineTo(54,-6);ctx.lineTo(54,6);ctx.fill();ctx.restore();ctx.font='14px Georgia';ctx.textAlign='center';ctx.fillText('HOME '+fmt(Math.hypot(v.x,v.y))+' m',mx,my+108);ctx.fillText(v.storm>.4?'ROUGH SEAS':'COASTAL WATERS',mx,my+128);
}
window.gameSea={harbor,act,key,update,draw};
})();
