const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const THREE={...require('./vendor/three.min.js')},S=require('./shared/sea');
let scene,camera,time=1000,disposed=0;const listeners={};
THREE.WebGLRenderer=class{constructor(){this.domElement={width:0,height:0,addEventListener(){}};}setPixelRatio(){}setSize(w,h){this.domElement.width=w;this.domElement.height=h;}render(s,c){scene=s;camera=c;c.updateMatrixWorld();}};
const env={THREE,DARK_SEA:S,console,performance:{now:()=>time},window:{addEventListener:(name,fn)=>listeners[name]=fn},document:{activeElement:{tagName:'BODY'},addEventListener:(name,fn)=>listeners[name]=fn},state:{area:'sea'},keys:{},canvas:{}};
env.atob=atob;env.window.DarkSeaLegendary={};const kitEnv={window:env.window};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../assets/dark-sea/legendary-models.js'),'utf8'),kitEnv);vm.createContext(env);for(const file of ['../assets/dark-sea/blender-animations.js','sea-animation.js'])vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,file),'utf8'),env);vm.runInContext(fs.readFileSync(require('node:path').join(__dirname,'../assets/dark-sea/blender-meshes.js'),'utf8'),env);vm.runInContext(fs.readFileSync(path.join(__dirname,'sea3d.js'),'utf8'),env);
const ctx=new Proxy({},{get:(_,key)=>()=>{}}),gl=env.window.SeaGL;
const v={x:120,y:120,a:0,ship:'sailboat',storm:0,entities:[],fx:[],onFoot:null};
const frame=()=>{time+=40;assert.equal(gl.draw(ctx,v,1280,800),true);};
frame();const start=camera.position.clone();const arrowYaw=gl.getYaw();env.keys.arrowleft=true;frame();assert.ok(camera.position.distanceTo(start)>.1);assert(gl.getYaw()<arrowYaw,'Left arrow now decreases yaw');env.keys.arrowleft=false;
const beforeDrag=camera.position.clone();listeners.pointerdown({button:2,target:env.canvas,clientX:0,clientY:0,preventDefault(){}});listeners.pointermove({buttons:2,clientX:150,clientY:40});frame();assert.ok(camera.position.distanceTo(beforeDrag)>5);assert.ok(Math.sin(Math.atan2(camera.position.z-12,camera.position.x-12)-Math.atan2(beforeDrag.z-12,beforeDrag.x-12))>0,'Right drag must increase yaw after horizontal inversion');
listeners.pointerup();const stopped=camera.position.clone();listeners.pointermove({buttons:2,clientX:300,clientY:400});frame();assert.ok(camera.position.distanceTo(stopped)<.001);
env.keys.arrowup=true;for(let i=0;i<60;i++)frame();assert.ok(camera.position.y>5,'Camera must remain above the sea');env.keys.arrowup=false;
// Chunks are actually removed and their GPU geometry disposed on eviction.
const baseline=scene.children.length;
for(let i=0;i<30;i++){v.entities=[{id:String(i),kind:'kraken',x:250,y:250,hp:100,maxHp:100}];frame();assert.equal(scene.children.length,baseline+1);const group=scene.children.at(-1);group.traverse(o=>o.geometry?.addEventListener('dispose',()=>disposed++));}
v.entities=[];frame();assert.equal(scene.children.length,baseline);assert.ok(disposed>=30*10);
let lockRequests=0,exits=0;env.canvas.requestPointerLock=()=>{lockRequests++;env.document.pointerLockElement=env.canvas;listeners.pointerlockchange();};env.document.exitPointerLock=()=>{exits++;env.document.pointerLockElement=null;listeners.pointerlockchange();};
listeners.pointerdown({button:2,target:env.canvas,clientX:40,clientY:40,preventDefault(){}});assert.equal(lockRequests,1);const lockedStart=camera.position.clone();listeners.mousemove({movementX:100,movementY:0});frame();assert.ok(camera.position.distanceTo(lockedStart)>1);listeners.pointerup({button:2});assert.equal(exits,0);assert.equal(env.document.pointerLockElement,env.canvas,'Cursor stays locked after releasing mouse');listeners.pointerdown({button:0,target:{}});assert.equal(exits,1);assert.equal(env.document.pointerLockElement,null);
// Escape/loss of lock cancels dragging, even while the right button remains down.
listeners.pointerdown({button:2,target:env.canvas,clientX:40,clientY:40,preventDefault(){}});env.document.pointerLockElement=null;listeners.pointerlockchange();const escaped=camera.position.clone(),escapedYaw=gl.getYaw();listeners.mousemove({movementX:100,movementY:0});frame();assert.equal(gl.getYaw(),escapedYaw);
// Unsupported/denied pointer lock keeps ordinary dragging available.
env.canvas.requestPointerLock=()=>{throw Error('Denied');};listeners.pointerdown({button:2,target:env.canvas,clientX:0,clientY:0,preventDefault(){}});listeners.pointermove({buttons:2,clientX:100,clientY:0});frame();assert.ok(camera.position.distanceTo(escaped)>1);
gl.reset();frame();assert.ok(Number.isFinite(camera.position.x));
// Close framing and smooth shortest-path yaw across snapshot updates.
v.entities=[];v.a=0;gl.reset();frame();const vessel=scene.children.find(g=>g.userData.sails);assert(vessel);const yawBefore=vessel.rotation.y;v.a=1;frame();assert(Math.abs(vessel.rotation.y-yawBefore)>0&&Math.abs(vessel.rotation.y-yawBefore)<.6);assert(camera.position.distanceTo(new THREE.Vector3(12,1,12))<30);
// The attacking arm must physically reach the server's marked point at impact.
v.entities=[{id:'strike',kind:'kraken',x:500,y:120,hp:100,maxHp:100,attack:{start:3000,impact:5000,end:5900,target:{x:120,y:120},arm:1}}];v.serverNow=5000;frame();const monster=scene.children.at(-1);assert.equal(monster.scale.x,S.KRAKEN_SCALE);assert(monster.userData.strike.visible);scene.updateMatrixWorld(true);function armTip(){const mesh=monster.userData.strikeTube,p=mesh.geometry.attributes.position,tip=new THREE.Vector3();for(let i=0;i<8;i++)tip.add(new THREE.Vector3().fromBufferAttribute(p,32*9+i));return tip.multiplyScalar(1/8).applyMatrix4(mesh.matrixWorld);}const tip=armTip();assert(tip.distanceTo(new THREE.Vector3(12,1,12))<.15,'Arm tip reaches the marked boat position at impact');const geo=monster.userData.strikeTube.geometry,ring=new THREE.Vector3();for(let i=0;i<8;i++)ring.add(new THREE.Vector3().fromBufferAttribute(geo.attributes.position,16*9+i));ring.multiplyScalar(1/8);const radial=new THREE.Vector3().fromBufferAttribute(geo.attributes.position,16*9).sub(ring),normal=new THREE.Vector3().fromBufferAttribute(geo.attributes.normal,16*9);assert(radial.dot(normal)>0,'Animated tube faces must point outward');
v.serverNow=4400;frame();scene.updateMatrixWorld(true);const raised=armTip();assert(raised.y>10,'Windup raises the arm well above the boat');v.serverNow=6000;frame();assert.equal(monster.userData.strike.visible,false);
console.log('PASS inverted right-drag, pointer lock/release/Escape/denial, arrow camera, pitch bounds, reset, close framing, smooth yaw, giant Kraken arm timing and geometry eviction');

v.serverNow=5000;v.entities[0].attack={start:3000,impact:5000,end:6600,type:'cross',arm:1,target:{x:120,y:120},targets:[{x:100,y:120},{x:140,y:120}]};frame();assert(monster.userData.secondStrike.visible);scene.updateMatrixWorld(true);const second=monster.userData.secondTube,points=second.geometry.attributes.position,tip2=new THREE.Vector3();for(let i=0;i<8;i++)tip2.add(new THREE.Vector3().fromBufferAttribute(points,32*9+i));tip2.multiplyScalar(1/8).applyMatrix4(second.matrixWorld);assert(tip2.distanceTo(new THREE.Vector3(14,1,12))<.15,'Second arm reaches its own damage marker');
v.onFoot='isle';v.boat={x:350,y:300};v.x=500;v.y=500;v.walkA=0;v.walkSpeed=140;v.entities=[{id:'isle',kind:'island',x:500,y:500,r:180,guards:[],looted:false}];frame();const avatar=scene.children.find(g=>g.userData.legs);assert(avatar);assert(Math.abs(avatar.userData.legs[0].rotation.x)>.01,'Walking animates limbs');v.walkSpeed=0;v.swing={start:4800,impact:5000,end:5300,a:0};frame();assert(avatar.userData.trail.visible,'A sword slash is visible at impact');assert(avatar.userData.moveBlend>0,'Stopping blends out the stride instead of snapping');for(let i=0;i<20;i++)frame();assert(Math.abs(avatar.userData.legs[0].rotation.x)<.001,'Stride settles into idle');console.log('PASS paired Kraken contact geometry and animated player walk/sword rigs');
// Multiplayer camera and crew bodies remain independent of the ship transform.
gl.reset();Object.assign(v,{multiplayer:true,onFoot:null,entities:[],self:'alice',room:'ROOM',shipX:500,shipY:500,shipA:0,x:490,y:500,a:0,flood:20,holes:[{x:0,y:9}],boarding:[],defenders:[],me:{role:'crew',place:'deck',x:-10,y:0},crew:[{user:'alice',room:'ROOM',place:'deck',worldX:490,worldY:500,a:0,moving:true}]});
for(let i=0;i<90;i++)frame();const closeDistance=camera.position.distanceTo(new THREE.Vector3(49,2,50));const crewBody=scene.children.find(g=>g.userData.chest&&g.userData.legs);assert(crewBody);const attached=()=>{vessel.updateMatrixWorld(true);const local=vessel.worldToLocal(crewBody.position.clone());assert(Math.abs(local.x+1/vessel.scale.x)<1e-8);assert(Math.abs(local.y-2.88)<1e-8);assert(Math.abs(local.z)<1e-8);};attached();assert.equal(vessel.position.x,50);
v.me.role='captain';v.x=500;for(let i=0;i<90;i++)frame();assert(camera.position.distanceTo(new THREE.Vector3(50,2,50))>closeDistance+10);attached();
v.me.role='crew';v.me.place='hold';v.crew[0].place='hold';for(let i=0;i<60;i++)frame();const hold=scene.children.find(g=>g.userData.leaks);assert(hold.visible);assert(!vessel.visible);assert(hold.userData.flood.visible);assert(hold.userData.leaks[0].visible);assert.equal(crewBody.position.y,.48);assert(Number.isFinite(camera.position.x));
gl.reset();assert(!scene.children.includes(crewBody),'crew meshes are disposed on reset');console.log('PASS independent crew transforms, captain zoom, 3D hold/flood/leaks and multiplayer cleanup');
// A crew camera remains fixed relative to a translating ship, then enters cannon aiming mode.
Object.assign(v,{me:{role:'crew',place:'deck',x:-10,y:0},crew:[{user:'alice',room:'ROOM',place:'deck',x:-10,y:0,worldX:480,worldY:500,a:0}],shipX:500,shipY:500,x:480,y:500,shipA:0,a:0});gl.reset();for(let i=0;i<100;i++)frame();const stationary=vessel.position.clone().project(camera);v.shipX+=100;v.x+=100;v.crew[0].worldX+=100;frame();const translated=vessel.position.clone().project(camera);assert(stationary.distanceTo(translated)<.03,'ship and camera translate together while collision clearance follows hull rocking');const walkingYaw=gl.getYaw();v.shipA+=.4;frame();assert.equal(gl.getYaw(),walkingYaw,'Crew camera orbits independently of ship steering');v.shipA=0;
v.me.role='starboard';v.me.x=6;v.me.y=10;frame();const cannonDirection=new THREE.Vector3();camera.getWorldDirection(cannonDirection);assert(cannonDirection.z>.8,'starboard first-person camera faces outboard');env.keys.arrowleft=true;for(let i=0;i<15;i++)frame();env.keys.arrowleft=false;assert(Math.abs(gl.getCannonAim().aim)>.1);assert(Math.abs(gl.getCannonAim().aim)<=.95);v.me.role='crew';v.me.place='hold';v.crew[0].place='hold';v.interior={x:v.shipX,y:v.shipY,a:0,room:'ROOM',cargo:Array.from({length:23},()=>({rarity:'Ironbound'}))};frame();assert.equal(hold.userData.cargo.filter(g=>g.visible).length,23,'physical crate stacks mirror cargo');console.log('PASS deck-relative camera, cannon aiming and physical cargo pile count');

v.me.role='starboard';v.me.place='deck';v.crew[0].place='deck';v.interior=null;frame();const turnAim=gl.getCannonAim().aim;v.shipA+=.4;frame();assert(Math.abs(gl.getCannonAim().aim-turnAim)<1e-6,'turning hull must not move cannon aim within its mount');
// Up/down arrows and mouse vertical movement use explicit cannon directions.
v.me.cannon='1:0';frame();let aimBefore=gl.getCannonAim().elevation;env.keys.arrowup=true;for(let i=0;i<3;i++)frame();env.keys.arrowup=false;assert(gl.getCannonAim().elevation<aimBefore,'up arrow lowers cannon after inversion');aimBefore=gl.getCannonAim().elevation;env.keys.arrowdown=true;for(let i=0;i<3;i++)frame();env.keys.arrowdown=false;assert(gl.getCannonAim().elevation>aimBefore,'down arrow elevates cannon after inversion');
listeners.pointerdown({button:2,target:env.canvas,clientX:0,clientY:0,preventDefault(){}});aimBefore=gl.getCannonAim().elevation;listeners.pointermove({buttons:2,clientX:0,clientY:-10});frame();assert(gl.getCannonAim().elevation>aimBefore,'mouse upward elevates cannon');listeners.pointerup({button:2});assert.equal(vessel.userData.cannons.length,2);assert(vessel.userData.cannons.every(m=>m.children.length>0),'real cannon meshes survive batching');assert(!scene.children.some(g=>g.userData.chest&&g.userData.legs&&g.visible),'own body cannot clip first-person sights');
console.log('PASS actual cannon pivots, upward/downward aiming, inverted vertical mouse and hidden first-person body');

// The full Leviathan body must be renderable before its first hit, and its face performs the windup.
v.me.role='captain';v.entities=[{id:'leviathan-new',kind:'kraken',name:'Leviathan',x:v.shipX+350,y:v.shipY+150,hp:1800,maxHp:1800}];v.serverNow=10000;frame();const levi=scene.children.find(g=>g.userData.mantle);scene.updateMatrixWorld(true);assert(levi.userData.body.matrixWorld.elements.every(Number.isFinite),'undamaged Leviathan body transform must be finite');assert.equal(levi.userData.feeders.length,6);assert.equal(levi.userData.tentacles.filter(t=>t.userData.claw).length,4);const mouthBefore=levi.userData.mouth.scale.y;v.entities[0].attack={start:10000,impact:12100,end:13700,type:'slap',arm:0,target:{x:v.shipX,y:v.shipY}};v.serverNow=11050;frame();assert(levi.userData.mouth.scale.y>mouthBefore);v.serverNow=12500;frame();assert(levi.userData.ripples[0].visible);assert(levi.userData.ripples[0].material.opacity>0);console.log('PASS finite Leviathan body, four hooked limbs, feeding tendrils, roar windup and impact wake');

// Multiplayer presentation may never independently push a model away from its crew.
v.me.role='crew';v.me.place='deck';v.onFoot=null;v.ship='brig';v.shipX=500;v.shipY=710;v.shipA=0;v.x=480;v.y=710;v.entities=[{id:'shore-regression',kind:'island',x:500,y:500,r:160,guards:[],looted:false}];frame();const docked=scene.children.find(g=>g.userData.shipType==='brig');assert(docked.visible);assert.equal(docked.position.x,50);assert.equal(docked.position.z,71,'Old renderer-only circle would displace the visible hull');
v.me.place='hold';v.interior={x:500,y:710,a:0,room:'ROOM',cargo:[]};frame();assert(!docked.visible);v.me.place='island';v.onFoot='shore-regression';v.x=500;v.y=500;frame();assert(docked.visible);v.me.place='deck';v.onFoot=null;v.x=480;v.y=710;frame();assert(docked.visible);assert.equal(docked.position.z,71);
console.log('PASS visible hull remains exactly aligned through hold, landing and respawn transitions');

// Freeing the mouse survives ordinary canvas clicks until explicitly locked again.
env.canvas.requestPointerLock=()=>{lockRequests++;env.document.pointerLockElement=env.canvas;listeners.pointerlockchange();};gl.freeMouse();const freeRequests=lockRequests;listeners.pointerdown({button:0,target:env.canvas,clientX:10,clientY:10,preventDefault(){}});assert.equal(lockRequests,freeRequests);gl.toggleMouse();assert.equal(lockRequests,freeRequests+1);gl.freeMouse();
v.siege=true;v.me.role='mortar';v.ammo={heavy:6};v.mortarShots=[];frame();assert(docked.userData.mortar.visible);let aim=gl.getMortarAim();assert(Math.abs(Math.hypot(aim.x-v.shipX,aim.y-v.shipY)-550)<.01);listeners.wheel({target:env.canvas,deltaY:10000,preventDefault(){}});frame();aim=gl.getMortarAim();assert(Math.abs(Math.hypot(aim.x-v.shipX,aim.y-v.shipY)-1100)<.01);assert(camera.position.y>=60,'Mortar has an elevated sightline');
v.mortarShots=[{born:v.serverNow-1500,impact:v.serverNow+500,x0:v.shipX,y0:v.shipY,tx:aim.x,ty:aim.y,radius:85,enemy:true}];frame();assert(scene.children.some(g=>g.visible&&g.geometry?.type==='SphereGeometry'&&g.position.y>20&&g.position.y<50),'Mortar shell rises in a real 3D arc');v.me.place='hold';frame();assert(!docked.visible);console.log('PASS explicit mouse release, bounded mortar targeting, physical siege model, elevated aim camera and 3D shell arc');

v.me.place='deck';v.turnVelocity=.4;frame();assert(docked.rotation.x>0,'Right turn banks the starboard side downward');v.turnVelocity=-.4;frame();assert(docked.rotation.x<0);v.turnVelocity=0;v.fx=[{kind:'mortarImpact',x:v.shipX,y:v.shipY,radius:115,born:v.serverNow-200,until:v.serverNow+2000}];frame();assert(scene.children.some(g=>g.isInstancedMesh&&g.geometry.type==='PlaneGeometry'&&g.count===6),'Impact smoke is rendered');assert(scene.children.some(g=>g.isInstancedMesh&&g.geometry.type==='BoxGeometry'&&g.count===6),'Impact debris is rendered');assert(scene.children.some(g=>g.isInstancedMesh&&g.geometry.type==='RingGeometry'&&g.count===1),'Blast shockwave is rendered');console.log('PASS turn-direction banking and bounded pooled smoke, debris and shockwave effects');
// Horizontal aiming reverses both input paths while vertical aim stays unchanged.
gl.reset();Object.assign(v,{onFoot:null,entities:[],fx:[],mortarShots:[],ship:'sailboat',shipX:500,shipY:500,x:500,y:500,shipA:0,me:{role:'starboard',place:'deck',cannon:'1:0'},crew:[]});frame();let horizontal=gl.getCannonAim().aim;env.keys.arrowright=true;frame();env.keys.arrowright=false;assert(gl.getCannonAim().aim>horizontal,'Right arrow reverses the former cannon direction');horizontal=gl.getCannonAim().aim;listeners.pointerdown({button:2,target:env.canvas,clientX:0,clientY:0,preventDefault(){}});listeners.mousemove({movementX:10,movementY:0});frame();listeners.pointerup();assert(gl.getCannonAim().aim>horizontal,'Mouse right uses the same inverted direction as arrow right');
const expedition=S.expeditionIsland({id:'render-highlands',kind:'island',x:2400,y:120,r:1800,tier:1,phase:Math.PI,lobes:4,guards:[],recruits:[],biome:'ruins',looted:false},S.random('render-highlands'));
gl.reset();v.entities=[expedition];v.onFoot=expedition.id;v.me={role:'crew',place:'island',groundHeight:130};v.x=1800;v.y=120;v.crew=[{user:'alice',room:v.room,place:'island',worldX:1800,worldY:120,groundHeight:130,a:0}];frame();const terrain=scene.children.find(g=>g.userData.caches&&g.userData.camps);assert(terrain);const ground=terrain.children.find(m=>m.geometry?.attributes.color);assert(ground.geometry.attributes.position.count>5000);assert(ground.geometry.attributes.uv);assert([...ground.geometry.attributes.normal.array].every(Number.isFinite));assert(ground.geometry.attributes.normal.getY(140)>0,'Terrain normals face upward');assert(scene.children.some(g=>g.userData.legs&&g.position.y>=13),'Avatar stands on the hillside');
const c=expedition.caves[0];v.me.cave=c.id;v.me.groundHeight=5;v.x=c.x;v.y=c.y;v.crew[0].cave=c.id;v.crew[0].groundHeight=5;v.crew[0].worldX=c.x;v.crew[0].worldY=c.y;frame();assert(!terrain.visible);const cavern=scene.children.find(g=>g.userData.caches&&g.userData.guards&&!g.userData.camps);assert(cavern?.visible);scene.updateMatrixWorld(true);cavern.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite)));v.me.cave=null;v.crew[0].cave=null;frame();assert(terrain.visible&&!cavern.visible);gl.reset();assert(!scene.children.includes(cavern),'Cave GPU objects are disposed on reset');
console.log('PASS inverted horizontal mouse/arrow cannon aim, elevated terrain normals, hillside avatar height, cave visibility and cave disposal');
const fortIsland=S.expeditionIsland({id:'fort-render',kind:'island',x:2400,y:120,r:1800,tier:1,phase:Math.PI,lobes:4,guards:[],recruits:[],biome:'ruins',looted:false},S.random('fort-render'));S.addFort(fortIsland,S.random('fort'));Object.assign(v,{entities:[fortIsland],onFoot:fortIsland.id,x:fortIsland.fort.x,y:fortIsland.fort.y,landShots:[]});v.me={role:'crew',place:'island',weapon:'gun',groundHeight:fortIsland.fort.height};v.crew=[{user:'alice',room:v.room,place:'island',worldX:v.x,worldY:v.y,a:0,weapon:'gun',groundHeight:fortIsland.fort.height}];frame();const armed=scene.children.find(g=>g.userData.legs&&g.userData.weapon==='gun');assert(armed?.userData.gun.visible);assert(!armed.userData.sword.visible);const fortScene=scene.children.find(g=>g.userData.camps&&g.userData.caches);assert(fortScene.userData.caches.length>=9);assert(fortScene.userData.guards.length>=16);env.keys.arrowdown=true;for(let i=0;i<45;i++)frame();env.keys.arrowdown=false;assert(camera.position.y-v.me.groundHeight*.1<10,'Foot camera lowers to a forward view instead of the old high-angle minimum');gl.reset();console.log('PASS modeled flintlock, fort troops/treasure, and lower forward-facing foot camera');

// The authoritative muzzle must match the actual barrel tip, including ship roll and pitch.
for(const ship of Object.keys(S.SHIPS))for(const side of [-1,1]){
 gl.reset();Object.assign(v,{ship,shipX:500,shipY:700,shipA:.7,a:.7,x:500,y:700,turnVelocity:.3,multiplayer:true,room:'R',self:'alice',onFoot:null,entities:[],recruits:[],companions:[],defenders:[],projectiles:[],fx:[],holes:[],cargo:[],serverNow:123456});
 v.me={role:side<0?'port':'starboard',place:'deck',cannon:side+':0',user:'alice',room:'R',x:0,y:side*10};v.crew=[{...v.me,worldX:500,worldY:700}];v.receivedAt=time+40;frame();env.keys.arrowleft=true;env.keys.arrowdown=true;for(let i=0;i<10;i++){v.receivedAt=time+40;frame();}env.keys.arrowleft=env.keys.arrowdown=false;
 const body=scene.children.find(g=>g.userData.cannons),mount=body.userData.cannons.find(m=>m.userData.key===v.me.cannon);body.updateMatrixWorld(true);const tip=mount.localToWorld(new THREE.Vector3(0,0,1.4)),aim=gl.getCannonAim(),ray=S.cannonRays({ship,x:500,y:700,a:.7},side)[0],expected=S.cannonMuzzle({ship,x:500,y:700,a:.7,turnVelocity:.3},ray,aim.aim,aim.elevation,v.serverNow);
 assert(tip.distanceTo(new THREE.Vector3(expected.x*.1,expected.height*.1,expected.y*.1))<1e-5,ship+' barrel tip matches server muzzle');
 const dir=new THREE.Vector3();camera.getWorldDirection(dir);const actual=new THREE.Vector3(expected.dx*Math.cos(expected.elevation),Math.sin(expected.elevation),expected.dy*Math.cos(expected.elevation));assert(dir.distanceTo(actual)<1e-5,'Sight follows barrel direction through banking');assert(camera.position.clone().sub(tip).dot(actual)>.2,'Camera clears the muzzle instead of sitting inside the gun');assert(camera.position.y>tip.y+.4,'Raised sights clear cannon fittings');assert.equal(camera.fov,70,'Wide cannon field of view');
}
gl.reset();console.log('PASS all four ship types and both broadsides: exact barrel-tip launch and sight direction including aim and ship banking');

// An actual occluder stays opaque; it must never shorten the selected orbit distance.
gl.reset();Object.assign(v,{ship:'brig',shipX:500,shipY:700,shipA:0,x:450,y:700,a:0,entities:[],onFoot:null,fx:[],crew:[],turnVelocity:0,me:{role:'crew',place:'deck',x:-25,y:0},interior:null});frame();
const orbitHead=new THREE.Vector3(45,.25+2.88*(.36+S.SHIPS.brig.cannons*.013)*2+.85,70);assert(Math.abs(camera.position.distanceTo(orbitHead)-12)<1e-6,'Default crew orbit keeps 12 units');
const hull=scene.children.find(g=>g.userData.shipType==='brig'),blocker=new THREE.Mesh(new THREE.BoxGeometry(3,3,3),new THREE.MeshStandardMaterial({color:0xabcdef})),opaque=blocker.material;hull.updateMatrixWorld(true);blocker.position.copy(hull.worldToLocal(orbitHead.clone().lerp(camera.position,.5)));hull.add(blocker);frame();assert(Math.abs(camera.position.distanceTo(orbitHead)-12)<1e-6,'Occlusion never pushes the camera into the player');assert.equal(blocker.material.opacity,1,'Ship geometry remains opaque');assert.equal(blocker.material,opaque);assert.equal(opaque.opacity,1,'Shared originals stay opaque');
v.me.role='starboard';v.me.cannon='1:0';frame();assert.equal(blocker.material,opaque,'Leaving third person restores the original material');
v.me={role:'crew',place:'hold',x:0,y:0};v.interior={x:500,y:700,a:0,room:v.room,cargo:[]};v.x=500;frame();assert(Math.abs(camera.position.distanceTo(new THREE.Vector3(50,1.1,70))-12)<1e-6,'The hold also preserves orbit distance');gl.reset();
console.log('PASS fixed orbit through real occlusion, opaque ship materials and unchanged hold distance');
