const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const THREE={...require('./vendor/three.min.js')},S=require('./shared/sea');
let scene,camera,time=1000,disposed=0;const listeners={};
THREE.WebGLRenderer=class{constructor(){this.domElement={width:0,height:0,addEventListener(){}};}setPixelRatio(){}setSize(w,h){this.domElement.width=w;this.domElement.height=h;}render(s,c){scene=s;camera=c;c.updateMatrixWorld();}};
const env={THREE,DARK_SEA:S,console,performance:{now:()=>time},window:{addEventListener:(name,fn)=>listeners[name]=fn},document:{activeElement:{tagName:'BODY'},addEventListener:(name,fn)=>listeners[name]=fn},state:{area:'sea'},keys:{},canvas:{}};
vm.createContext(env);vm.runInContext(fs.readFileSync(path.join(__dirname,'sea3d.js'),'utf8'),env);
const ctx=new Proxy({},{get:(_,key)=>()=>{}}),gl=env.window.SeaGL;
const v={x:120,y:120,a:0,ship:'sailboat',storm:0,entities:[],fx:[],onFoot:null};
const frame=()=>{time+=40;assert.equal(gl.draw(ctx,v,1280,800),true);};
frame();assert(Math.abs(camera.position.x-12)<.001&&Math.abs(camera.position.z-12)<.001,'First-person view stays on the vessel');const start=camera.quaternion.clone();env.keys.arrowleft=true;frame();assert.ok(camera.quaternion.angleTo(start)>.01);env.keys.arrowleft=false;
const beforeDrag=camera.quaternion.clone(),yawBeforeDrag=gl.getYaw();listeners.pointerdown({button:2,target:env.canvas,clientX:0,clientY:0,preventDefault(){}});listeners.pointermove({buttons:2,clientX:150,clientY:40});frame();assert.ok(camera.quaternion.angleTo(beforeDrag)>.1);assert.ok(gl.getYaw()>yawBeforeDrag,'Right drag must increase yaw after horizontal inversion');
listeners.pointerup();const stopped=camera.position.clone();listeners.pointermove({buttons:2,clientX:300,clientY:400});frame();assert.ok(camera.position.distanceTo(stopped)<.001);
env.keys.arrowup=true;for(let i=0;i<60;i++)frame();assert.ok(camera.position.y>=5,'Camera must remain above the sea');env.keys.arrowup=false;
// Chunks are actually removed and their GPU geometry disposed on eviction.
const baseline=scene.children.length;
for(let i=0;i<30;i++){v.entities=[{id:String(i),kind:'kraken',x:250,y:250,hp:100,maxHp:100}];frame();assert.equal(scene.children.length,baseline+1);const group=scene.children.at(-1);group.traverse(o=>o.geometry?.addEventListener('dispose',()=>disposed++));}
v.entities=[];frame();assert.equal(scene.children.length,baseline);assert.ok(disposed>=30*10);
let lockRequests=0,exits=0;env.canvas.requestPointerLock=()=>{lockRequests++;env.document.pointerLockElement=env.canvas;listeners.pointerlockchange();};env.document.exitPointerLock=()=>{exits++;env.document.pointerLockElement=null;listeners.pointerlockchange();};
listeners.pointerdown({button:2,target:env.canvas,clientX:40,clientY:40,preventDefault(){}});assert.equal(lockRequests,1);const lockedStart=camera.quaternion.clone();listeners.mousemove({movementX:100,movementY:0});frame();assert.ok(camera.quaternion.angleTo(lockedStart)>.1);listeners.pointerup({button:2});assert.equal(exits,1);assert.equal(env.document.pointerLockElement,null);
// Escape/loss of lock cancels dragging, even while the right button remains down.
listeners.pointerdown({button:2,target:env.canvas,clientX:40,clientY:40,preventDefault(){}});env.document.pointerLockElement=null;listeners.pointerlockchange();const escaped=camera.quaternion.clone(),escapedYaw=gl.getYaw();listeners.mousemove({movementX:100,movementY:0});frame();assert.equal(gl.getYaw(),escapedYaw);
// Unsupported/denied pointer lock keeps ordinary dragging available.
env.canvas.requestPointerLock=()=>{throw Error('Denied');};listeners.pointerdown({button:2,target:env.canvas,clientX:0,clientY:0,preventDefault(){}});listeners.pointermove({buttons:2,clientX:100,clientY:0});frame();assert.ok(camera.quaternion.angleTo(escaped)>.1);
gl.reset();frame();assert.ok(Number.isFinite(camera.position.x));
// Close framing and smooth shortest-path yaw across snapshot updates.
v.entities=[];v.a=0;gl.reset();frame();const vessel=scene.children.find(g=>g.userData.sails);assert(vessel);const yawBefore=vessel.rotation.y;v.a=1;frame();assert(Math.abs(vessel.rotation.y-yawBefore)>0&&Math.abs(vessel.rotation.y-yawBefore)<.6);assert(camera.position.distanceTo(new THREE.Vector3(12,1,12))<30);
// The attacking arm must physically reach the server's marked point at impact.
v.entities=[{id:'strike',kind:'kraken',x:500,y:120,hp:100,maxHp:100,attack:{start:3000,impact:5000,end:5900,target:{x:120,y:120},arm:1}}];v.serverNow=5000;frame();const monster=scene.children.at(-1);assert.equal(monster.scale.x,S.KRAKEN_SCALE);assert(monster.userData.strike.visible);scene.updateMatrixWorld(true);function armTip(){const mesh=monster.userData.strikeTube,p=mesh.geometry.attributes.position,tip=new THREE.Vector3();for(let i=0;i<8;i++)tip.add(new THREE.Vector3().fromBufferAttribute(p,32*9+i));return tip.multiplyScalar(1/8).applyMatrix4(mesh.matrixWorld);}const tip=armTip();assert(tip.distanceTo(new THREE.Vector3(12,1,12))<.15,'Arm tip reaches the marked boat position at impact');const geo=monster.userData.strikeTube.geometry,ring=new THREE.Vector3();for(let i=0;i<8;i++)ring.add(new THREE.Vector3().fromBufferAttribute(geo.attributes.position,16*9+i));ring.multiplyScalar(1/8);const radial=new THREE.Vector3().fromBufferAttribute(geo.attributes.position,16*9).sub(ring),normal=new THREE.Vector3().fromBufferAttribute(geo.attributes.normal,16*9);assert(radial.dot(normal)>0,'Animated tube faces must point outward');
v.serverNow=4400;frame();scene.updateMatrixWorld(true);const raised=armTip();assert(raised.y>10,'Windup raises the arm well above the boat');v.serverNow=6000;frame();assert.equal(monster.userData.strike.visible,false);
console.log('PASS inverted right-drag, pointer lock/release/Escape/denial, arrow camera, pitch bounds, reset, close framing, smooth yaw, giant Kraken arm timing and geometry eviction');

v.serverNow=5000;v.entities[0].attack={start:3000,impact:5000,end:6600,type:'cross',arm:1,target:{x:120,y:120},targets:[{x:100,y:120},{x:140,y:120}]};frame();assert(monster.userData.secondStrike.visible);scene.updateMatrixWorld(true);const second=monster.userData.secondTube,points=second.geometry.attributes.position,tip2=new THREE.Vector3();for(let i=0;i<8;i++)tip2.add(new THREE.Vector3().fromBufferAttribute(points,32*9+i));tip2.multiplyScalar(1/8).applyMatrix4(second.matrixWorld);assert(tip2.distanceTo(new THREE.Vector3(14,1,12))<.15,'Second arm reaches its own damage marker');
v.onFoot='isle';v.boat={x:350,y:300};v.x=500;v.y=500;v.walkA=0;v.walkSpeed=140;v.entities=[{id:'isle',kind:'island',x:500,y:500,r:180,guards:[],looted:false}];frame();const avatar=scene.children.find(g=>g.userData.legs);assert(avatar);assert(Math.abs(avatar.userData.legs[0].rotation.x)>.01,'Walking animates limbs');v.walkSpeed=0;v.swing={start:4800,impact:5000,end:5300,a:0};frame();assert(avatar.userData.trail.visible,'A sword slash is visible at impact');assert(Math.abs(avatar.userData.legs[0].rotation.x)<1e-8);console.log('PASS paired Kraken contact geometry and animated player walk/sword rigs');
