/* Server-authoritative crews. Ship simulation remains independent of every walking body. */
'use strict';
const crypto=require('node:crypto'),wire=require('../js/shared/sea-wire'),request=require('./sea-request');
module.exports=function createCrewSea(options){
 const S=options.rules,now=options.now||Date.now,players=new Map(),rooms=new Map(),world=new Map(),spent=new Set(),islandProgress=new Map();
 const companions=require('./sea-companions')(S),mechanics=require('./sea-mechanic')(S),ordnance=require('./sea-ordnance')(S);
 const worldDuration=2*60*60*1000,seedRoot=(options.seed||(()=>crypto.randomBytes(12).toString('hex')))();
 let generation=0,oceanSeed=seedRoot,worldResetsAt=now()+worldDuration;
 const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
 // All ships see the same mutable islands and enemies. Keep only occupied sectors.
 const base=require('./sea')({...options,seed:()=>oceanSeed,rules:{...S,MAX_VOYAGE_MS:worldDuration,sector:(seed,x,y)=>{
  const key=x+':'+y;if(!world.has(key))world.set(key,S.sector(seed,x,y).map(e=>{if(spent.has(e.id)){if(e.kind==='island'){e.looted=true;S.treasureCaches(e).forEach(c=>c.taken=true);e.guards.forEach(g=>g.hp=0);}else e.hp=0;}const progress=islandProgress.get(e.id);if(progress&&e.kind==='island'){S.treasureCaches(e).forEach((c,i)=>{if(progress.chests&(1n<<BigInt(i)))S.takeCache(e,c);});S.recruitCamps(e).forEach((c,i)=>{if(progress.recruits&(1n<<BigInt(i)))c.recruited=true;});}return e;}));return world.get(key);
 }},externalTargets:v=>[...rooms.values()].map(r=>base.raw(r.owner)).filter(b=>b&&b!==v)});
 function roomFor(p){return rooms.get(p.room);}
 function shipFor(p){return base.raw(roomFor(p)?.owner);}
 function all(v){return [...v.sectors.values()].flat();}
 function deck(p){return p.place==='deck'||p.place==='hold';}
 function bodyShip(p){return p.boarded?(rooms.has(p.boarded)?base.raw(rooms.get(p.boarded).owner):all(shipFor(p)).find(e=>e.id===p.boarded)):shipFor(p);}
 function position(p){if(!deck(p))return{x:p.x,y:p.y};const b=bodyShip(p)||shipFor(p);return{x:b.x+2*(Math.cos(b.a)*p.x-Math.sin(b.a)*p.y),y:b.y+2*(Math.sin(b.a)*p.x+Math.cos(b.a)*p.y)};}
 function station(p,x,y,r=12){return dist(p,{x,y})<=r;}
 function reset(p){Object.assign(p,{bodyRevision:(p.bodyRevision||0)+1,weapon:'sword',gunAt:0,cave:null,hopAt:0,island:null,swing:null,hurtAt:0,dodgeUntil:0,sailorTalk:false,deckA:0,place:'deck',x:-10,y:0,role:'crew',cannon:null,boarded:null,map:false,hp:100,input:{},carrying:null,repair:null});}
 function add(user,r){const p={user,room:r.code,last:now(),attackAt:0};reset(p);players.set(user,p);r.members.add(user);return p;}
 function remove(user){const p=players.get(user);if(!p)return;const r=roomFor(p);if(r){r.members.delete(user);if(r.captain===user)r.captain=null;if(!r.members.size){base.disconnect(r.owner);rooms.delete(r.code);}}players.delete(user);}
 function end(r,reason){for(const user of r.members){const p=players.get(user);if(p)p.ended=reason;}base.disconnect(r.owner);rooms.delete(r.code);}
 function view(user){const p=players.get(user);if(!p)return base.handle(user,{action:'status'});if(p.ended){players.delete(user);return{...base.handle(user,{action:'status'}),ended:true,reason:p.ended};}
  const r=roomFor(p),v=base.raw(r.owner);if(!v){remove(user);return{...base.handle(user,{action:'status'}),ended:true,reason:'Voyage ended.'};}
  companions.sync(r,v);const result=base.handle(r.owner,{action:'status'});if(result.ended){end(r,result.reason);return view(user);}
  const out=result.voyage,pos=position(p);out.canUnload=user===r.owner||p.role==='captain';out.multiplayer=true;out.capacity=v.stats.cannons+1;out.cannonReload=Object.fromEntries(Object.entries(v.fireCannons||{}).map(([k,t])=>[k,Math.max(0,t-now())]));out.room=r.code;out.captain=r.captain;out.self=user;out.shipX=v.x;out.shipY=v.y;out.shipA=v.a;
  const interiorShip=bodyShip(p)||v;out.interior={x:interiorShip.x,y:interiorShip.y,a:interiorShip.a,room:p.boarded||p.room,cargo:(interiorShip.cargo||[]).map(c=>({rarity:c.rarity})),ship:interiorShip.ship,holes:p.boarded?(rooms.get(p.boarded)?.holes||[]):r.holes,flood:p.boarded?(rooms.get(p.boarded)?.flood||0):r.flood};out.me={...publicPlayer(p),map:p.map};out.crew=[...players.values()].filter(q=>!q.ended&&dist(position(q),pos)<2200).map(publicPlayer);
  out.companions=[...(r.helpers||[]),...(r.mechanic?[r.mechanic]:[])].map(h=>({...publicPlayer(h),name:h.name,rosterIndex:h.rosterIndex,kind:h.kind,state:h.state,maxHp:h.maxHp,bed:h.bed,load:h.load.length,tier:h.tier}));out.roster=v.roster.slice();out.specialists=[v.crewId,...(v.extraCrew||[])].filter(Boolean);out.assignments=S.cannonAssignments(v);out.recruits=v.roster.map((id,rosterIndex)=>({id,rosterIndex})).filter(({id})=>!['fighter','looter','mechanic'].includes(S.RECRUITS[id]?.role)).map(({id,rosterIndex})=>({id,rosterIndex,name:S.RECRUITS[id]?.name||id,x:S.cannonAssignments(v).find(n=>n.rosterIndex===rosterIndex)?.x??-18,y:S.cannonAssignments(v).find(n=>n.rosterIndex===rosterIndex)?.y??0,active:id===v.crewId||v.extraCrew?.includes(id)})).filter(n=>!out.crew.some(p=>p.room===r.code&&p.cannon===out.assignments.find(a=>a.rosterIndex===n.rosterIndex)?.cannon&&p.cannon));out.holes=r.holes.map(h=>({...h}));out.flood=r.flood;out.boarding=r.links.map(l=>({...l}));out.defenders=[];
  for(const e of all(v)){prepareEnemy(e);}for(const e of all(v))for(const g of e.boarders||[])out.defenders.push({...g,shipId:e.id,ship:e.ship,shipX:e.x,shipY:e.y,shipA:e.a});
  out.entities=out.entities.concat([...rooms.values()].filter(other=>other!==r).map(other=>{const b=base.raw(other.owner);return b&&{id:other.code,kind:'pirate',playerShip:true,name:'Crew '+other.code,ship:b.ship,x:b.x,y:b.y,a:b.a,hp:b.hp,maxHp:b.stats.durability,siege:b.siege,mortarTier:b.mortarTier,turnVelocity:b.turnVelocity};}).filter(e=>e&&dist(e,v)<2200));
  out.landShots=[...rooms.values()].flatMap(q=>q.landShots||[]).filter(f=>f.until>now()&&dist(f,pos)<1500).slice(-48);out.fx=[...rooms.values()].flatMap(other=>base.raw(other.owner)?.fx||[]).filter(f=>dist(f,v)<2200).slice(-12);out.notice=p.notice||v.notice;out.boat={x:v.x,y:v.y};out.onFoot=p.place==='island'?p.island:null;
  out.x=p.role==='captain'?v.x:pos.x;out.y=p.role==='captain'?v.y:pos.y;out.walkA=p.a;out.walkSpeed=p.moving?100:0;out.swing=p.swing;
  out.projectiles=[...[...rooms.values()].flatMap(other=>(base.raw(other.owner)?.projectiles||[]).map(({damage,...shot})=>({...shot,id:other.code+':'+shot.id}))),...all(v).flatMap(e=>e.shots||[]).map(({damage,...shot})=>shot)].filter(shot=>dist(shot,v)<2200).slice(0,80);
  const own=options.getUser(user);result.profile=own.sea||base.handle(user,{action:'status'}).profile;result.money=own.money;return result;
 }
 function publicPlayer(p){const b=bodyShip(p),pos=position(p);return{msgs:(p.msgs||[]).filter(m=>now()-m.ts<9000),bodyRevision:p.bodyRevision||0,sailorTalk:!!p.sailorTalk,user:p.user,room:p.room,place:p.place,x:p.x,y:p.y,worldX:pos.x,worldY:pos.y,role:p.role,weapon:p.weapon||'sword',gunReload:Math.max(0,(p.gunAt||0)-now()),cave:p.cave||null,groundHeight:p.place==='island'?S.terrainHeight(all(shipFor(p)).find(e=>e.id===p.island),p.x,p.y,p.cave):0,hopAt:p.hopAt||0,cannon:p.cannon,aim:p.aim||0,elevation:p.elevation??.18,boarded:p.boarded,hp:p.hp,hurtAt:p.hurtAt,blocking:!!p.input?.block,dodgeUntil:p.dodgeUntil,a:deck(p)?(b?.a||0)+(p.deckA||0):p.a||0,moving:p.moving,swing:p.swing,carrying:p.carrying?{rarity:p.carrying.rarity}:null,repair:p.repair,shipA:b?.a||0,ship:b?.ship};}
 function damagePlayer(p,n){if(p.companion){companions.hurt(p,n,now());return;}if(now()<(p.dodgeUntil||0))return;if(p.input?.block)n*=.2;p.hurtAt=now();p.hp=Math.max(0,p.hp-Math.round(n));if(p.hp<=0){if(roomFor(p)?.captain===p.user){roomFor(p).captain=null;shipFor(p).input={};}reset(p);p.notice='You were knocked out and recovered aboard. Your carried chest was lost.';}}
 function melee(p){const time=now();if(p.role!=='crew'||p.carrying)throw Error('Leave the wheel or stow your chest before fighting.');if(p.input?.block)throw Error('Release guard before swinging.');if(time<p.attackAt)return;p.combo=time-(p.lastSwing||0)<1000?((p.combo||0)+1)%3:0;p.lastSwing=time;p.attackAt=time+(p.combo===2?650:400);p.swing={start:time,impact:time+150,end:time+440,a:deck(p)?(bodyShip(p)?.a||0)+(p.deckA||0):p.a||0,combo:p.combo};}
 function gunTrace(r,from,to,time,enemy,island,cave){r.landShots=(r.landShots||[]).filter(f=>f.until>time).slice(-47);r.landShots.push({x:from.x,y:from.y,tx:to.x,ty:to.y,born:time,until:time+260,enemy,island,cave:cave||null});}
 function shoot(p){if(p.carrying)throw Error('Stow your chest before firing.');if(p.input?.block)throw Error('Release guard before firing.');const time=now();if(time<(p.gunAt||0))return;p.gunAt=time+1400;p.swing=null;const r=roomFor(p),v=shipFor(p),from=position(p),a=p.input?.walkAngle??p.a??0;p.a=a;if(deck(p))p.deckA=a-bodyShip(p).a;const end={x:from.x+Math.cos(a)*420,y:from.y+Math.sin(a)*420},isle=all(v).find(e=>e.id===p.island),body=bodyShip(p),targets=p.place==='island'?(isle?.guards||[]).filter(g=>g.hp>0&&(g.cave||null)===(p.cave||null)).map(g=>({g,x:g.x,y:g.y})):p.boarded?(body?.boarders||[]).filter(g=>g.hp>0&&(g.place||'deck')===p.place).map(g=>({g,x:body.x+2*(Math.cos(body.a)*g.x-Math.sin(body.a)*g.y),y:body.y+2*(Math.sin(body.a)*g.x+Math.cos(body.a)*g.y)})):[];
  const hit=targets.map(t=>({...t,hit:S.segmentHit(from,end,t,14)})).filter(t=>t.hit!==null&&(!isle||!S.landShotBlocked(isle,from,t,p.cave))).sort((a,b)=>a.hit-b.hit)[0];let to=end;if(hit){hit.g.hp=Math.max(0,hit.g.hp-65);hit.g.hitAt=time;hit.g.stunUntil=time+400;hit.g.attack=null;to=hit;}else if(isle){for(let i=1;i<=28;i++){const point={x:from.x+(end.x-from.x)*i/28,y:from.y+(end.y-from.y)*i/28};if(S.landShotBlocked(isle,from,point,p.cave)){to=point;break;}}}gunTrace(r,from,to,time,false,p.island,p.cave);
 }
 function makeChest(e){const rng=S.random(oceanSeed+'|cargo|'+e.id);return{rarity:['Weathered','Ironbound','Runed','Abyssal'][e.tier||0],coins:Math.floor(350+rng()*550+(e.tier||0)*450),gems:3+Math.floor(rng()*5)+(e.tier||0)*5,rep:12+(e.tier||0)*10};}
 function atCannon(p,v,side){return S.cannonRays({...v,x:0,y:0,a:0},side).some(ray=>station(p,clamp(ray.x/2,-34,34),side*10,9));}
 function interact(p){const r=roomFor(p),v=shipFor(p);p.map=false;p.sailorTalk=false;
  if(p.role==='captain'){r.captain=null;p.role='crew';v.input={};p.notice='Wheel released. Ship coasts while you help the crew.';return;}
  if(p.role==='port'||p.role==='starboard'||p.role==='mortar'){p.role='crew';p.cannon=null;return;}
  if(p.place==='island'){
   const e=all(v).find(e=>e.id===p.island);if(!e){reset(p);return;}
   const cave=p.cave?e.caves?.find(c=>c.id===p.cave):e.caves?.find(c=>dist(p,c)<65);
   if(cave&&dist(p,cave.rooms[0])<65){p.cave=p.cave?null:cave.id;p.x=cave.x;p.y=cave.y;p.bodyRevision=(p.bodyRevision||0)+1;p.notice=p.cave?'Entered cave. Follow the chambers for sealed treasure. F at the entrance exits.':'Returned to the island surface.';return;}
   if(p.carrying)throw Error('Carry this chest to the cargo area below deck first. Press B beside your ship to board.');const cache=S.treasureCaches(e).filter(c=>!c.taken&&(c.cave||null)===(p.cave||null)&&dist(p,c)<65).sort((a,b)=>dist(p,a)-dist(p,b))[0];
   if(cache){if(p.carrying)throw Error('Stow your carried chest in the hold first.');if(e.guards.some(g=>g.hp>0&&(g.cave||null)===(p.cave||null)&&dist(g,cache)<150))throw Error('Defeat the nearby treasure defenders first.');S.takeCache(e,cache);p.carrying=makeChest({...e,id:cache.id,tier:cache.tier});p.notice='Sealed chest recovered. Bring it to your ship cargo hold.';return;}
   throw Error('Approach a sealed chest or cave entrance and press F. B boards beside your ship.');
  }
  if(p.place==='hold'){
   if(p.boarded&&station(p,24,0)&&!p.carrying){steal(p);return;}
   if(station(p,24,0)&&p.carrying){const b=bodyShip(p);if(p.boarded)throw Error('Return the stolen chest to your own cargo hold.');if(b.cargo.length>=b.stats.cargo)throw Error('Cargo hold is full.');b.cargo.push(p.carrying);p.carrying=null;p.notice='Chest secured in cargo. Sail home to bank it.';return;}
   if(station(p,-25,0)){p.map=true;p.notice='Chart open. Move to close it.';return;}
   if(station(p,0,0,7)){p.place='deck';return;}
   throw Error('Hatch: center · Chart: stern · Cargo: bow.');
  }
  const stationId=S.nearestStation(p,v)?.id;
  if(stationId==='hatch'){p.place='hold';return;}
  if(!p.boarded&&stationId==='mortar'){if(p.carrying)throw Error('Stow your chest first.');if([...r.members].some(u=>players.get(u)?.role==='mortar'))throw Error('Mortar occupied.');p.role='mortar';p.x=S.mortarStation(v.ship).x-4;p.y=0;return;}
  if(!p.boarded&&stationId==='sailor'){p.sailorTalk=true;return;}
  if(!p.boarded&&stationId==='wheel'){if(p.carrying)throw Error('Stow the chest first.');if(r.captain&&r.captain!==p.user)throw Error('The wheel is occupied.');v.autopilot=null;r.captain=p.user;p.role='captain';p.x=-29;p.y=0;return;}
  if(!p.boarded){const choices=S.cannonRays({...v,x:0,y:0,a:0}).map(ray=>({...ray,sx:clamp(ray.x/2,-34,34)})).filter(ray=>station(p,ray.sx,ray.side*10,9)).sort((a,b)=>dist(p,{x:a.sx,y:a.side*10})-dist(p,{x:b.sx,y:b.side*10}));const ray=choices.find(ray=>ray.key===stationId);if(ray){if(p.carrying)throw Error('Stow your chest first.');if([...r.members].some(u=>u!==p.user&&players.get(u)?.cannon===ray.key))throw Error('This cannon is occupied.');p.cannon=ray.key;p.x=ray.sx;p.y=ray.side*10;p.role=ray.side===-1?'port':'starboard';return;}}
  throw Error('Walk to the wheel, cannon or hatch and press F. Use B at the rail to land or cross a boarding rope.');
 }
 function board(p){if(p.cave)throw Error('Exit the cave before boarding.');if(p.place==='island'){const v=shipFor(p);if(dist(position(p),v)>S.hullRadius(v.ship)+100+(all(v).find(e=>e.id===p.island)?.r||0)*.07)throw Error('Move closer to your ship at the shore.');p.place='deck';p.x=8;p.y=0;p.island=null;return;}if(p.role!=='crew'||p.place!=='deck')throw Error('Leave your station and stand on deck to board.');const r=roomFor(p),v=shipFor(p);
  if(p.boarded){const b=bodyShip(p);if(!b||dist(b,v)>300)throw Error('Your ship is too far away.');p.boarded=null;p.x=28;p.y=0;return;}
  const link=r.links.find(l=>S.linkActive(l,now()));if(link){const target=rooms.has(link.id)?base.raw(rooms.get(link.id).owner):all(v).find(e=>e.id===link.id);if(target&&target.kind!=='island'&&target.hp>0&&dist(target,v)<300){p.boarded=link.id;p.x=-25;p.y=0;return;}}
  const e=all(v).find(e=>e.kind==='island'&&dist(e,v)<(e.terrain?e.r*.90*S.shoreFactor(e,Math.atan2(v.y-e.y,v.x-e.x)):e.r)+S.hullRadius(v.ship)+85);if(!e)throw Error('Sail beside an island, or lasso a nearby ship first.');r.mission=e.id;const a=Math.atan2(v.y-e.y,v.x-e.x);p.place='island';p.island=e.id;const landing=e.r>250?S.islandAnchor(e,v,.84):{x:e.x+Math.cos(a)*(e.r-25),y:e.y+Math.sin(a)*(e.r-25)};p.x=landing.x;p.y=landing.y;p.notice='1: sword. 2: flintlock. Space attacks. F picks up loot. B boards beside your ship.';
 }
 function lasso(p){if(p.place!=='deck'||p.role!=='crew'||p.carrying)throw Error('A free crew member must throw the boarding rope from deck.');const r=roomFor(p),v=shipFor(p);if(r.links.length){for(const link of r.links){const other=rooms.get(link.id),target=all(v).find(e=>e.id===link.id);if(target)target.tetherUntil=0;if(other)other.links=other.links.filter(l=>l.id!==r.code);}r.links=[];r.mission=null;p.notice='Rope released. Companions returning aboard.';return;}if(p.boarded)return;
  const candidates=[...all(v).filter(e=>(e.kind==='pirate'&&e.hp>0||e.kind==='island'&&dist(e,v)<(e.terrain?e.r*.90*S.shoreFactor(e,Math.atan2(v.y-e.y,v.x-e.x)):e.r)+S.hullRadius(v.ship)+85)),...[...rooms.values()].filter(q=>q!==r).map(q=>{const b=base.raw(q.owner);return b&&{...b,id:q.code};}).filter(Boolean)];
  const anchor=e=>e.kind==='island'?S.islandAnchor(e,v):e;const e=candidates.filter(e=>(e.kind==='island'||dist(e,v)<280)&&!S.blockedSeaLine(v,anchor(e),S.obstacles(all(v)).filter(o=>o.x!==e.x||o.y!==e.y))).sort((a,b)=>dist(anchor(a),v)-dist(anchor(b),v))[0];if(!e)throw Error('Bring another ship within 280 m. Leviathans cannot be boarded.');r.links=[{id:e.id,permanent:e.kind==='island',anchor:e.kind==='island'?S.islandAnchor(e,v):null,until:e.kind==='island'?null:now()+45000}];e.tetherUntil=e.kind==='island'?0:now()+45000;e.warning=0;e.attack=null;v.speed=0;
  r.mission=e.id;const other=rooms.get(e.id);if(other){other.links=[{id:r.code,until:now()+45000}];base.raw(other.owner).speed=0;}else if(e.kind==='pirate'){prepareEnemy(e);}
  p.notice=e.kind==='island'?'Island rope secured until you release it with L. B lands; your crew will follow.':'Rope secured for 45 seconds. B crosses; Space fights; Y steals at the bow. B returns.';
 }
 function steal(p){if(!p.boarded||!['deck','hold'].includes(p.place)||p.carrying||!station(p,25,0,15))throw Error('Reach the enemy cargo area with empty hands to steal a chest.');const b=bodyShip(p);if(!b||b.hp<=0)throw Error('That ship has sunk.');if(b.boarders?.some(g=>g.hp>0&&(g.place||'deck')===p.place&&dist(g,p)<12))throw Error('Fight off nearby defenders first.');if(!b.cargo?.length)throw Error('No unbanked treasure remains aboard.');p.carrying=b.cargo.pop();p.notice='Stolen chest contains gold and gems. Bring it to your own cargo hold.';}
 function handle(user,m={}){request.validate(m);const action=m.action||'status';let p=players.get(user);if(p?.ended)return view(user);
  if(action==='staff_summon'&&!options.isStaff?.(user))throw Error('Staff only.');
  if(action==='status')return view(user);
  if(action==='join'){if([...rooms.values()].some(r=>r.owner===user))throw Error('Rejoin your existing ship with Sail before joining another crew.');if(p)throw Error('Leave your current voyage first.');const r=rooms.get(String(m.code||'').trim().toUpperCase());if(!r)throw Error('Crew code not found on this server.');if(r.members.size>=base.raw(r.owner).stats.cannons+1)throw Error('This ship is full: one crew slot per cannon plus one below deck.');base.handle(user,{action:'status'});add(user,r);return view(user);}
  if(action==='sail'){if(p)return view(user);const existing=[...rooms.values()].find(r=>r.owner===user);if(existing){add(user,existing);return view(user);}base.handle(user,m);let code;do{code=crypto.randomBytes(3).toString('hex').toUpperCase();}while(rooms.has(code));const r={code,owner:user,members:new Set(),captain:null,holes:[],flood:0,links:[],last:now(),lastDamage:now()};rooms.set(code,r);p=add(user,r);const v=base.raw(user);v.playerShip=true;v.id=code;v.maxHp=v.stats.durability;v.auto=false;r.previousHp=v.hp;p.notice='Welcome aboard! Walk aft to the wheel and press F. Share crew code '+code+'.';return view(user);}
  if(!p){if([...rooms.values()].some(r=>r.owner===user))throw Error('Rejoin your ship with Sail before issuing voyage commands.');if(!['buy','equip','upgrade','crew_equip','crew_dismiss','ammo_buy','siege_equip','crew'].includes(action))throw Error('No active crew voyage. Sail or join a ship first.');return base.handle(user,m);}const r=roomFor(p),v=shipFor(p);if(!v||v.sunk||v.hp<=0){end(r,'Your ship sank. Unbanked cargo was lost.');return view(user);}p.last=now();v.lastInput=now();const locationBefore=p.place+':'+p.boarded+':'+p.cave;
  if(action==='staff_summon'){summon(p,m.kind);return view(user);}
  if(action==='chat'){if(options.canChat&&!options.canChat(user))throw Error('You are muted.');if(typeof m.text!=='string')throw Error('Enter a chat message.');const text=m.text.replace(/[\x00-\x1f\x7f]/g,' ').trim().slice(0,80);if(!text)throw Error('Enter a chat message.');if(now()<(p.chatAt||0))throw Error('Please wait before sending another message.');p.chatAt=now()+900;p.msgs=[{text,ts:now()},...(p.msgs||[]).filter(m=>now()-m.ts<9000)].slice(0,3);p.input={};if(p.role==='captain')v.input={};return view(user);}
  if(action==='invite'){if(!options.invite)throw Error('Invitations unavailable.');if(now()<(r.inviteAt||0))throw Error('Wait a few seconds before inviting again.');if(r.members.has(m.to))throw Error('Your friend is already aboard.');if(r.members.size>=v.stats.cannons+1)throw Error('This ship is full.');r.inviteAt=now()+5000;options.invite(m.to,{event:'sea_invite',by:user,code:r.code});p.notice='Invitation sent to '+m.to+'.';return view(user);}
  if(action==='input'){const i=m.input||{};p.input={forward:i.forward===true,back:i.back===true,left:i.left===true,right:i.right===true,boost:i.boost===true,block:i.block===true,walkAngle:Number.isFinite(i.walkAngle)?i.walkAngle:0};p.aim=clamp(Number(i.aim)||0,-.95,.95);p.elevation=clamp(Number(i.elevation)||0,-.2,.8);if(p.role==='crew'&&p.weapon==='gun'){p.a=p.input.walkAngle;if(deck(p))p.deckA=p.a-bodyShip(p).a;}if(p.role==='captain')v.input=p.input;return view(user);}
  if(action==='weapon'){if(!['sword','gun'].includes(m.weapon))throw Error('Choose sword or gun.');p.weapon=m.weapon;return view(user);}
  if(action==='fire'&&p.role==='captain'&&!m.side)return view(user);
  if(action==='dodge'){if(p.role!=='crew'||p.carrying||now()<(p.dodgeAt||0))throw Error('Dodge unavailable.');p.dodgeAt=now()+1300;p.dodgeUntil=now()+300;const a=p.input?.walkAngle??p.a??0;if(deck(p)){p.x=clamp(p.x+Math.cos(a-bodyShip(p).a)*8,-36,36);p.y=clamp(p.y+Math.sin(a-bodyShip(p).a)*8,-10,10);}else{p.x+=Math.cos(a)*35;p.y+=Math.sin(a)*35;const e=all(v).find(e=>e.id===p.island);if(e)S.constrainFoot(p,e);}}
  else if(action==='crew_dismiss'){if(user!==r.owner)throw Error('Only the ship owner dismisses NPC crew.');const index=m.rosterIndex??v.roster.indexOf(m.crew),removed=r.helpers?.find(h=>h.rosterIndex===index);base.handle(r.owner,m);if(removed){r.helpers=r.helpers.filter(h=>h!==removed);for(const h of r.helpers)if(h.recruitId===removed.recruitId&&(h.copy||0)>(removed.copy||0)){h.copy--;h.user=r.code+':helper:'+h.recruitId+(h.copy?':'+h.copy:'');}}}
  else if(action==='sailor'){if(user!==r.owner&&p.role!=='captain')throw Error('Only the owner or captain gives sailing orders.');if(!v.roster.some(id=>S.RECRUITS[id]?.role==='sailor'))throw Error('Rescue a sailor first.');if(!['home','patrol','destination','stop'].includes(m.mode))throw Error('Unknown sailing order.');if(m.mode==='destination'&&(!Number.isFinite(m.x)||!Number.isFinite(m.y)||Math.abs(m.x)>30000||Math.abs(m.y)>30000))throw Error('Choose coordinates within 30,000 m of home.');if(m.mode!=='stop'){if(r.captain){const captain=players.get(r.captain);captain.role='crew';r.captain=null;}v.autopilot={mode:m.mode,goal:m.mode==='home'?{x:120,y:120}:m.mode==='destination'?{x:m.x,y:m.y}:null};v.thinkAt=0;}else v.autopilot=null;}
  else if(action==='interact')interact(p);
  else if(action==='board')board(p);
  else if(action==='lasso')lasso(p);
  else if(action==='steal')steal(p);
  else if(action==='ammo_select'){if(!['port','starboard','crew'].includes(p.role))throw Error('Leave your station to change cannon ammunition.');base.handle(r.owner,m);}
  else if(action==='mortar'){if(p.role!=='mortar'||p.place!=='deck'||p.boarded)throw Error('Use the mortar station on your own deck first.');base.handle(r.owner,m);}
  else if(action==='fire'){if(!m.side&&['port','starboard'].includes(p.role))m={...m,side:p.role==='port'?-1:1};if(m.side){if(p.carrying)throw Error('Stow your chest first.');if(p.role!==(m.side===-1?'port':'starboard'))throw Error('Walk to that cannon and press F first.');if(p.role!=='captain'&&!p.cannon)throw Error('Enter a cannon first.');const aim=clamp(Number(m.aim)||0,-.95,.95),elevation=clamp(Number.isFinite(Number(m.elevation))?Number(m.elevation):.12,-.2,.8);base.handle(r.owner,{action:'fire',side:m.side,aim:p.role==='captain'?0:aim,elevation:p.role==='captain'?.12:elevation,cannonX:p.role==='captain'?null:S.cannonRays({...v,x:0,y:0,a:0}).find(ray=>ray.key===p.cannon)?.x});}else if(p.weapon==='gun'&&p.role==='crew')shoot(p);else melee(p);}
  else if(action==='auto'){if(p.role!=='captain')throw Error('Only the captain controls the rescued gunner.');base.handle(r.owner,m);}
  else if(action==='repair'){if(p.place!=='hold'||p.boarded||p.carrying)throw Error('Go below deck with empty hands to repair a leak.');const h=r.holes.find(h=>dist(h,p)<14);if(!h)throw Error('Move beside a marked hull breach.');p.repair={id:h.id,start:now(),until:now()+(r.members.size===1?2500:4500)};p.input={};}
  else if(action==='recruit'){if(p.place!=='island')throw Error('Find a recruit on an island.');const e=all(v).find(e=>e.id===p.island);if(p.cave||!e||!S.recruitCamps(e).some(c=>!c.recruited&&dist(p,c)<65))throw Error('Approach the recruit above ground and press G. Enemies do not need to be defeated.');const old={x:v.x,y:v.y,onFoot:v.onFoot};try{v.x=p.x;v.y=p.y;v.onFoot=p.island;base.handle(r.owner,{action:'recruit'});}finally{Object.assign(v,old);}p.notice='Specialist rescued for this ship. The captain can enable auto-fire.';}
  else if(action==='return'){if(user!==r.owner&&p.role!=='captain')throw Error('The captain or ship owner unloads at home.');if(Math.hypot(v.x,v.y)>260)throw Error('Sail back to the home harbor.');if([...r.members].some(u=>players.get(u).carrying))throw Error('Stow all carried chests before unloading.');const members=[...r.members],totals=v.cargo.reduce((a,c)=>({coins:a.coins+c.coins,gems:a.gems+c.gems,rep:a.rep+c.rep}),{coins:0,gems:0,rep:0});for(let index=0;index<members.length;index++){const member=members[index],profile=base.handle(member,{action:'status'}).profile,share=key=>Math.floor(totals[key]/members.length)+(index<totals[key]%members.length?1:0);options.pay(member,-share('coins'));profile.gems+=share('gems');profile.reputation+=share('rep');profile.deliveries+=v.cargo.length;profile.kills+=v.kills;const found=ordnance.bank(profile,v.cargo);if(found)r.mortarFound=true;options.save(member,profile);}end(r,'Unloaded '+v.cargo.length+' chests. Gold, gems and reputation were split among '+members.length+' crew members.'+(r.mortarFound?' A mortar was discovered! Check the Shipwright siege tab.':''));return view(user);}
  else if(action==='rescue'){remove(user);return{...base.handle(user,{action:'status'}),voyage:null,ended:true,reason:'You left the crew. Carried loot was abandoned.'};}
  else throw Error('Return to the Shipwright before changing your ship.');if(locationBefore!==p.place+':'+p.boarded+':'+p.cave){p.bodyRevision=(p.bodyRevision||0)+1;p.swing=null;p.repair=null;}return view(user);
 }
 function summon(p,kind){
  if(!['pirate','kraken'].includes(kind))throw Error('Choose a pirate ship or Leviathan.');
  const r=roomFor(p),v=shipFor(p),time=now();
  if(p.boarded||p.place==='island'||p.cave)throw Error('Return to your own ship to summon enemies.');
  if(time<(r.summonAt||0))throw Error('Wait 10 seconds between summons.');
  const loaded=[...world.values()].flat();if(loaded.filter(e=>e.staffSummoned&&e.hp>0).length>=24)throw Error('Too many summoned enemies are active.');
  const land=S.obstacles(loaded),radius=kind==='kraken'?S.KRAKEN_RADIUS:100;let point;
  for(let i=0;i<24;i++){const a=v.a+i*Math.PI/12,d=650+Math.floor(i/12)*250,q={x:v.x+Math.cos(a)*d,y:v.y+Math.sin(a)*d};if(land.some(o=>dist(q,o)<o.r+radius+50)||loaded.some(e=>e.kind!=='island'&&e.hp>0&&dist(q,e)<radius+150)||[...rooms.values()].some(other=>{const b=base.raw(other.owner);return b&&dist(q,b)<radius+150;}))continue;if(!world.has(Math.floor(q.x/S.SECTOR)+':'+Math.floor(q.y/S.SECTOR)))continue;point=q;break;}
  if(!point)throw Error('No clear water nearby. Sail farther from land and try again.');
  const tier=Math.min(3,Math.floor(Math.hypot(Math.floor(v.x/S.SECTOR),Math.floor(v.y/S.SECTOR))/3)),id='summon:'+crypto.randomBytes(12).toString('hex'),e=S.navalEncounter(kind,tier,point.x,point.y,id,S.random(oceanSeed+'|'+id));
  e.staffSummoned=true;e.attackAt=time+3000;const sector=world.get(Math.floor(point.x/S.SECTOR)+':'+Math.floor(point.y/S.SECTOR));
  // Dead summons need no tombstones; their IDs are never generated again.
  for(let i=sector.length-1;i>=0;i--)if(sector[i].staffSummoned&&sector[i].hp<=0)sector.splice(i,1);
  sector.push(e);const key=Math.floor(point.x/S.SECTOR)+':'+Math.floor(point.y/S.SECTOR);for(const room of rooms.values()){const list=base.raw(room.owner)?.sectors.get(key);if(list&&list!==sector){for(let i=list.length-1;i>=0;i--)if(list[i].staffSummoned&&list[i].hp<=0)list.splice(i,1);list.push(e);}}r.summonAt=time+10000;p.notice=e.name+' summoned nearby.';options.audit?.({action:'sea_summon',staff:p.user,kind,id,x:e.x,y:e.y,tier});
 }
 function prepareEnemy(e){if(e.kind!=='pirate'||e.playerShip||e.boarders)return;const tier=e.tier||0;e.boarders=S.cannonRays({...e,x:0,y:0,a:0}).map((ray,i)=>({id:e.id+':gunner:'+i,name:'Gunner',x:clamp(ray.x/2,-34,34),y:ray.side*9,place:'deck',hp:65+tier*30,maxHp:65+tier*30,damage:14+tier*4,attackAt:0,cannon:ray.key}));e.boarders.push({id:e.id+':captain',name:'Captain',captain:true,x:-29,y:0,place:'deck',hp:140+tier*80,maxHp:140+tier*80,damage:24+tier*8,attackAt:0});e.cargo=Array.from({length:2+tier*2},()=>makeChest(e));}
 function resetWorld(){if(now()<worldResetsAt)return;const elapsed=Math.floor((now()-worldResetsAt)/worldDuration)+1;for(const r of [...rooms.values()])end(r,'The Dark Sea has reset. Return to the harbor to sail into the new world. Unbanked cargo was lost.');world.clear();spent.clear();islandProgress.clear();generation+=elapsed;oceanSeed=seedRoot+'|world:'+generation;worldResetsAt+=elapsed*worldDuration;}
 function tick(){resetWorld();const time=now();for(const r of [...rooms.values()]){const v=base.raw(r.owner);if(!v)continue;const dt=Math.min(.25,Math.max(0,(time-r.last)/1000));r.last=time;
  for(const user of [...r.members]){const p=players.get(user);if(time-p.last>90000){remove(user);continue;}v.lastInput=time;
   if(p.boarded&&(!bodyShip(p)||bodyShip(p).hp<=0)){reset(p);p.notice='The boarded ship sank. You recovered aboard.';}
   const i=time-p.last<1000?p.input:{},walk=p.role==='crew';p.moving=walk&&!!(i.forward||i.back||i.left||i.right);if(p.moving){p.map=false;p.repair=null;const forward=(i.forward?1:0)-(i.back?1:0),side=(i.right?1:0)-(i.left?1:0),a=i.walkAngle||0;let dx=Math.cos(a)*forward-Math.sin(a)*side,dy=Math.sin(a)*forward+Math.cos(a)*side;const len=Math.hypot(dx,dy)||1;dx/=len;dy/=len;p.a=Math.atan2(dy,dx);const speed=(deck(p)?(p.carrying?15:25):(p.carrying?65:115))*(i.block?.45:1)*dt;
    if(deck(p)){const b=bodyShip(p);p.deckA=p.a-b.a;p.x=clamp(p.x+(dx*Math.cos(b.a)+dy*Math.sin(b.a))*speed,-36,p.place==='deck'?S.mortarStation(b.ship).x+1:36);p.y=clamp(p.y+(-dx*Math.sin(b.a)+dy*Math.cos(b.a))*speed,p.x>36?-5:-10,p.x>36?5:10);}else{const e=all(v).find(e=>e.id===p.island),oldHeight=S.terrainHeight(e,p.x,p.y,p.cave);p.x+=dx*speed;p.y+=dy*speed;if(e){S.constrainFoot(p,e);if(!p.cave&&S.terrainHeight(e,p.x,p.y)-oldHeight>1&&time>(p.hopAt||0)+420)p.hopAt=time;}}}
   if(p.repair&&time>=p.repair.until){const h=r.holes.find(h=>h.id===p.repair.id);if(h&&p.place==='hold'&&dist(h,p)<14){r.holes=r.holes.filter(q=>q!==h);v.hp=Math.min(v.stats.durability,v.hp+v.stats.durability*.12);r.flood=Math.max(0,r.flood-18);}p.repair=null;}
   if(p.swing&&!p.swing.resolved&&time>=p.swing.impact){p.swing.resolved=true;const pos=position(p),hit=target=>dist(pos,target)<(deck(p)?24:42)&&Math.cos(Math.atan2(target.y-pos.y,target.x-pos.x)-p.swing.a)>-.15;
    if(p.place==='island'){const e=all(v).find(e=>e.id===p.island);for(const g of e?.guards||[])if(g.hp>0&&(g.cave||null)===(p.cave||null)&&hit(g)){g.hp=Math.max(0,g.hp-35);g.hitAt=time;g.stunUntil=time+450;g.attack=null;}}
    if(p.boarded){const b=bodyShip(p);for(const g of b?.boarders||[])if(g.hp>0&&(g.place||'deck')===p.place&&dist(g,p)<10&&Math.cos(Math.atan2(g.y-p.y,g.x-p.x)+bodyShip(p).a-p.swing.a)>-.25){g.hp=Math.max(0,g.hp-(p.combo===2?50:30));g.hitAt=time;g.stunUntil=time+500;g.attack=null;}}
    for(const q of players.values())if(q!==p&&!q.ended&&q.room!==p.room&&q.place===p.place&&(q.cave||null)===(p.cave||null)&&(p.place!=='island'||q.island===p.island)&&hit(position(q)))damagePlayer(q,30);
   }
  }
  v.helmOccupied=!!r.captain;v.occupiedCannons=[...r.members].map(u=>players.get(u)?.cannon).filter(Boolean);v.tethered=r.links.some(l=>S.linkActive(l,time));r.links=r.links.filter(l=>S.linkActive(l,time));if(!r.links.length)r.mission=null;companions.tick(r,v,all(v),time,dt,[...r.members].map(u=>players.get(u)).filter(Boolean));r.landShots=(r.landShots||[]).filter(f=>f.until>time);if(r.links.length){v.input={};v.speed*=.5;}else if(!r.captain)v.input={};
  for(const e of all(v)){prepareEnemy(e);if(e.kind==='island'){const on=[...players.values(),...[...rooms.values()].flatMap(q=>q.helpers||[]).filter(h=>h.state!=='recovering')].filter(p=>!p.ended&&p.place==='island'&&p.island===e.id);for(const g of e.guards)if(g.hp>0&&on.length&&g.crewTick!==time){g.crewTick=time;const targets=on.filter(p=>(p.cave||null)===(g.cave||null));if(!targets.length)continue;const target=targets.sort((a,b)=>dist(a,g)-dist(b,g))[0],d=dist(target,g);g.a=Math.atan2(target.y-g.y,target.x-g.x);g.moving=false;if(g.attack&&time>=g.attack.end)g.attack=null;if(d>420&&!g.attack)continue;
    if(g.attack&&!g.attack.resolved&&time>=g.attack.impact){g.attack.resolved=true;if(g.attack.type==='gun'){const from=g.attack.from,to=g.attack.target;if(!S.landShotBlocked(e,from,to,g.cave)){const hit=targets.map(p=>({p,t:S.segmentHit(from,to,p,13)})).filter(x=>x.t!==null).sort((a,b)=>a.t-b.t)[0];if(hit)damagePlayer(hit.p,22+e.tier*4);}gunTrace(r,from,to,time,true,e.id,g.cave);}else for(const p of targets)if(dist(p,g.attack.target)<40)damagePlayer(p,18+e.tier*4);}
    if(time<(g.stunUntil||0)||g.attack&&time<g.attack.end)continue;
    const rifle=g.weapon==='gun',clear=!S.landShotBlocked(e,g,target,g.cave);if(rifle&&d<=330&&clear){if(time>=(g.attackAt||0)){g.attack={type:'gun',start:time,impact:time+1000,end:time+1400,from:{x:g.x,y:g.y},target:{x:target.x,y:target.y},a:g.a};g.attackAt=time+2800+(e.guards.indexOf(g)%4)*170;}continue;}
    if(d>38){const goal=g.cave?S.caveWaypoint(e,g,target):S.landWaypoint(e,g,target),a=Math.atan2(goal.y-g.y,goal.x-g.x);g.x+=Math.cos(a)*52*dt;g.y+=Math.sin(a)*52*dt;g.moving=true;S.constrainFoot(g,e);}else if(time>=(g.attackAt||0)){g.attack={start:time,impact:time+650,end:time+1100,target:{x:target.x,y:target.y},a:g.a};g.attackAt=time+1600;}}}

   const boarders=[...players.values(),...[...rooms.values()].flatMap(q=>q.helpers||[]).filter(h=>h.state!=='recovering')].filter(p=>!p.ended&&p.boarded===e.id);if(boarders.length){e.boardingActiveUntil=time+1500;e.warning=0;e.attack=null;}
   for(const g of e.boarders||[])if(g.hp>0&&boarders.length&&g.crewTick!==time){g.crewTick=time;g.place=g.place||'deck';const p=boarders.sort((a,b)=>dist(a,g)-dist(b,g))[0];g.moving=false;
    if(g.attack&&!g.attack.resolved&&time>=g.attack.impact){g.attack.resolved=true;if(g.place===p.place&&dist(g.attack.target,p)<11)damagePlayer(p,g.damage||16);}
    if(time<(g.stunUntil||0)||g.attack&&time<g.attack.end)continue;
    let target=p;if(g.place!==p.place){target={x:0,y:0};if(dist(g,target)<6){g.place=p.place;continue;}}
    const d=dist(g,target);g.a=Math.atan2(target.y-g.y,target.x-g.x)+e.a;if(d>(g.place===p.place?8:5)){g.x+=Math.cos(g.a-e.a)*16*dt;g.y+=Math.sin(g.a-e.a)*16*dt;g.moving=true;}
    else if(time>g.attackAt&&g.place===p.place){g.attack={start:time,impact:time+550,end:time+950,target:{x:p.x,y:p.y},a:g.a};g.attackAt=time+1400;}
   }
  }
  if(v.hp<r.previousHp-8&&time-r.lastDamage>1800&&r.holes.length<6){r.lastDamage=time;r.holes.push({id:time+':'+r.holes.length,x:-28+(r.holes.length%3)*28,y:r.holes.length%2?9:-9});}
  mechanics.tick(r,v,time,dt);r.flood=clamp(r.flood+r.holes.length*(r.members.size<=1?.65:1.2)*dt-(r.holes.length?0:3*dt),0,100);v.hp-=r.holes.length*(r.members.size<=1?1.4:2.8)*dt+r.flood*.04*dt;r.previousHp=v.hp;
 }
 base.tick();for(const r of [...rooms.values()]){const v=base.raw(r.owner);if(!v||v.sunk)end(r,'Your ship sank or the voyage expired. Unbanked cargo was lost.');}
 const needed=new Set();for(const r of rooms.values())for(const key of base.raw(r.owner)?.sectors.keys()||[])needed.add(key);for(const key of world.keys())if(!needed.has(key)){for(const e of world.get(key))if(e.looted||e.hp<=0){spent.add(e.id);if(spent.size>4096)spent.delete(spent.values().next().value);}for(const e of world.get(key))if(e.kind==='island'){const chests=S.treasureCaches(e).reduce((bits,c,i)=>c.taken?bits|(1n<<BigInt(i)):bits,0n),recruits=S.recruitCamps(e).reduce((bits,c,i)=>c.recruited?bits|(1n<<BigInt(i)):bits,0n);if(chests||recruits)islandProgress.set(e.id,{chests,recruits});}if(islandProgress.size>4096)islandProgress.delete(islandProgress.keys().next().value);world.delete(key);}
 }
 return{handle:(user,msg)=>{resetWorld();const result=handle(user,msg);result.canSummonSeaEnemies=!!options.isStaff?.(user);result.worldResetsAt=worldResetsAt;result.worldRemaining=Math.max(0,worldResetsAt-now());if(result.voyage){result.voyage.worldResetsAt=worldResetsAt;result.voyage.remaining=result.worldRemaining;}const p=players.get(user),v=p&&shipFor(p);if(v)v.occupiedCannons=[...roomFor(p).members].map(u=>players.get(u)?.cannon).filter(Boolean);return wire.pack(result,msg);},tick,disconnect:remove,sessionCount:()=>rooms.size,diagnostics:user=>({...base.diagnostics(players.get(user)?roomFor(players.get(user))?.owner:user),worldSectors:world.size,progressIslands:islandProgress.size,spentEntities:spent.size}),raw:user=>base.raw(players.get(user)?roomFor(players.get(user))?.owner:user)};
};
