'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const src=fs.readFileSync(require.resolve('./server'),'utf8'),clients=new Set(),areaState=new Map(),roles=new Map(),sent=[];
const env={clients,areaState,guildRunOf:new Map(),roleOf:u=>roles.get(u)||'user',sendRaw:(c,s)=>sent.push({to:c.user,...JSON.parse(s)})};vm.createContext(env);vm.runInContext(src.slice(src.indexOf('function presenceAreaKey('),src.indexOf('setInterval(broadcastPresence')),env);
const a={user:'a',ws:{OPEN:1,readyState:1,bufferedAmount:0},av:1,appearanceStr:'yes',presence:{area:'neighborhood',x:10,y:20,appearance:{shirt:'red'},car:'compact'}},b={...a,user:'b',ws:{...a.ws},presence:{...a.presence,x:30}};clients.add(a);clients.add(b);
const tick=()=>{sent.length=0;vm.runInContext('broadcastPresence()',env);};tick();assert.equal(sent.length,2);assert(sent.every(m=>m.reset&&m.users.a.car==='compact'));tick();assert.equal(sent.length,0);
a.presence={...a.presence,x:11};tick();assert.equal(sent.length,2);assert.equal(sent[0].users.a.x,11);assert(!('appearance' in sent[0].users.a));
b.ws.bufferedAmount=300000;a.presence={...a.presence,x:12};tick();assert(!sent.some(m=>m.to==='b'));assert.equal(b.sentArea,null);
a.presence={...a.presence,x:13};tick();b.ws.bufferedAmount=0;tick();const reset=sent.find(m=>m.to==='b');assert(reset.reset);assert.equal(reset.users.a.x,13);assert.equal(reset.users.a.appearance.shirt,'red');
roles.set('a','admin');tick();assert.equal(sent[0].users.a.role,'admin');clients.delete(a);tick();assert.deepEqual(sent[0].gone,['a']);clients.clear();tick();assert.equal(areaState.size,0);
console.log('PASS idle presence reuse, movement deltas, car replication, bounded slow-socket movement and full recovery, roles, disconnects and empty-area cleanup');
