'use strict';
const assert=require('node:assert/strict'),S=require('../js/shared/sea'),C=require('./sea-companions')(S);
const roster=['fighter_1','fighter_2','fighter_3','musketeer_4','looter_1','looter_2','looter_3','looter_4'];
for(const [ship,looters,fighters] of [['sailboat',2,2],['ketch',3,2],['brig',4,3]]){const r={code:'R',helpers:[]};C.sync(r,{ship,roster});assert.equal(r.helpers.filter(h=>h.kind==='looter').length,looters);assert.equal(r.helpers.filter(h=>h.kind==='fighter').length,fighters);assert.equal(new Set(r.helpers.map(h=>h.bed)).size,r.helpers.length);}
const cave={id:'cave',x:200,y:0,rooms:[{x:200,y:0,r:125},{x:410,y:0,r:125},{x:410,y:210,r:125}]};
const land={id:'isle',kind:'island',x:0,y:0,r:900,tier:0,caves:[cave],guards:[{id:'cave-guard',x:410,y:210,hp:80,cave:'cave',weapon:'sword'}],chests:[{id:'deep-cache',x:410,y:235,cave:'cave',tier:1,taken:false}],recruits:[]};
const v={ship:'brig',x:950,y:0,a:0,roster:['musketeer_4','looter_4'],cargo:[],stats:{cargo:88}},r={code:'R',mission:'isle',links:[{id:'isle',permanent:true}],helpers:[]};C.sync(r,v);r.helpers.forEach(h=>Object.assign(h,{place:'island',island:'isle',x:220,y:20,state:'deployed'}));let time=1000,sawFighter=false,sawLooter=false,sawShot=false;
for(let i=0;i<2500;i++){time+=100;C.tick(r,v,[land],time,.1);sawFighter ||= r.helpers.some(h=>h.kind==='fighter'&&h.cave==='cave');sawLooter ||= r.helpers.some(h=>h.kind==='looter'&&h.cave==='cave');sawShot ||= (r.landShots||[]).length>0;}
assert(sawFighter&&sawLooter,'Both roles physically enter the cave');assert.equal(land.guards[0].hp,0);assert(sawShot,'Musketeer fires with line of sight');assert.equal(v.cargo.length,1,'Deep cave loot returns to the ship exactly once');assert(r.helpers.every(h=>!h.cave&&h.place==='hold'));
const teams={code:'S',mission:'field',links:[{id:'field',permanent:true}],helpers:[]},boat={ship:'brig',x:900,y:0,a:0,roster:['fighter_3','fighter_4'],cargo:[],stats:{cargo:88}},field={id:'field',kind:'island',x:0,y:0,r:900,guards:[{id:'left',x:100,y:0,hp:60},{id:'right',x:-300,y:0,hp:60}],chests:[]};C.sync(teams,boat);teams.helpers.forEach(h=>Object.assign(h,{place:'island',island:'field',x:0,y:0,state:'deployed'}));C.tick(teams,boat,[field],time,.1);assert.equal(new Set(teams.helpers.map(h=>h.targetId)).size,2,'Capable fighters cover separate targets');
const ally=teams.helpers[0];C.hurt(ally,999,time);assert.equal(ally.cave,null);assert.equal(ally.place,'hold');
console.log('PASS ship-specific crew limits, unique beds, musketeer cave combat, connected cave routing, physical cave loot return, separate fighter targets and recovery');
