'use strict';
const assert=require('node:assert/strict'),S=require('../js/shared/sea'),rewards=require('./sea-leviathan-rewards');
for(const great of [false,true]){const r=rewards(),e={kind:'kraken',hp:0,great},a={hp:100},b={hp:100},dead={hp:100};r.record(e,a,30);r.record(e,b,70);r.record(e,dead,900);dead.hp=0;const rows=r.settle(e,[a,b,dead]);assert.equal(rows.reduce((n,x)=>n+x.count,0),great?35:10);assert.equal(rows.find(x=>x.ship===a).count,great?11:3);assert(!rows.some(x=>x.ship===dead));assert.deepEqual(r.settle(e,[a,b]),[]);}
{const r=rewards(),e={kind:'kraken',hp:0},old={hp:100},fresh={hp:100};r.record(e,old,50);assert.deepEqual(r.settle(e,[fresh]),[]);}
// Mortar damage from two live voyages is credited before the killing hit settles.
for(const great of [false,true]){let time=1000;const users={},e={id:'boss',kind:'kraken',name:'Leviathan',great,hp:100,maxHp:100,tier:0,x:1600,y:100,protectedUntil:0,attackAt:1e9,tetherUntil:1e9};const sea=require('./sea')({rules:{...S,sector:(_,x,y)=>x===0&&y===0?[e]:[]},getUser:u=>users[u]??={money:1e7},save:(u,p)=>users[u].sea=p,pay:()=>{},now:()=>time,seed:()=>1});for(const u of ['a','b']){sea.handle(u,{action:'buy',ship:'sailboat'});sea.handle(u,{action:'sail'});}const a=sea.raw('a'),b=sea.raw('b');function hit(v,damage){v.mortarShots=[{impact:time+1,tx:e.x,ty:e.y,radius:500,damage}];time++;sea.tick();}hit(a,30);assert.equal(e.hp,70);hit(b,1000);assert.equal(a.cargo.length,great?11:3);assert.equal(b.cargo.length,great?24:7);assert([...a.cargo,...b.cargo].every(c=>c.coins>0&&c.gems>0));time++;sea.tick();assert.equal(a.cargo.length+b.cargo.length,great?35:10);}
// Predictive strikes use the entire windup, including turning; others aim at current position.
for(const roll of [0,.9]){const ai=require('./sea-tentacles')(S,()=>roll),e={x:0,y:0,hp:1000,great:true},b={id:'s',ship:'brig',x:200,y:100,hp:1000,a:.3,speed:120,turnVelocity:.25};ai.tick(e,[b],[],1000,0,()=>{},()=>{});const a=e.arms.find(q=>q.attack).attack,expected=roll===0?S.predictCourse(b,(a.impact-a.start)/1000):b;assert.equal(a.predictive,roll===0);assert(Math.hypot(a.target.x-expected.x,a.target.y-expected.y)<1e-8);}
console.log('PASS 10/35 chest pools, proportional whole-chest shares, sunk/replaced ship exclusion, one-time settlement, mortar overkill cap and occasional full-windup prediction');
