'use strict';
const assert=require('node:assert/strict'),S=require('../js/shared/sea'),O=require('./sea-ordnance')(S),create=require('./crew-sea');
// Rewards only roll during banking; rates and duplicate compensation are explicit.
const p={gems:0};O.initialize(p);assert.equal(p.ammo.round,120);assert.equal(O.bank(p,[{rarity:'Weathered'}],()=>.031),0);assert.equal(O.bank(p,[{rarity:'Abyssal'}],()=>.159),1);assert(p.siegeOwned);O.bank(p,[{rarity:'Abyssal'}],()=>0);assert.equal(p.gems,20);assert.equal(O.bank(p,[],()=>0),0);
const straight=S.predictCourse({x:0,y:0,a:0,speed:100},3);assert(Math.abs(straight.x-300)<1e-8);const turn=S.predictCourse({x:0,y:0,a:0,speed:100,turnVelocity:.5},3);assert(turn.y>170&&turn.x<220,'Lead must follow the turn, not a straight extrapolation');
let time=1000;const user={money:10000,sea:{crewVersion:2,ship:'brig',owned:['brig'],roster:[],activeCrew:null,extraCrew:[],gems:0,reputation:0,deliveries:0,kills:0,upgrades:{},siegeOwned:true,siegeEquipped:true,ammo:{round:2,chain:2,heavy:6}}};
const sea=create({rules:{...S,sector:()=>[]},getUser:()=>user,save:(_,p)=>user.sea=p,pay:(_,n)=>user.money-=n,now:()=>time,seed:()=>7}),call=(action,extra={})=>sea.handle('a',{action,...extra});
call('ammo_buy',{ammo:'chain'});assert.equal(user.sea.ammo.chain,17);assert.equal(user.money,9930);assert.throws(()=>call('ammo_buy',{ammo:'fake'}),/Unknown/);
call('sail');const v=sea.raw('a');assert.throws(()=>call('mortar',{x:600,y:120}),/station/);
function walk(x,y){for(let i=0;i<150;i++){const p=call('status').voyage.me;if(Math.hypot(x-p.x,y-p.y)<1)break;call('input',{input:{forward:true,walkAngle:Math.atan2(y-p.y,x-p.x)+v.a}});time+=40;sea.tick();}call('input',{input:{}});}
walk(-29,0);call('interact');assert.equal(call('status').voyage.me.role,'captain');assert.throws(()=>call('fire',{side:1}),/cannon/);assert.equal(v.ammo.round,2);call('interact');
walk(S.mortarStation(v.ship).x,0);call('interact');assert.equal(call('status').voyage.me.role,'mortar');assert.throws(()=>call('mortar',{x:NaN,y:0}),/target/);assert.throws(()=>call('mortar',{x:v.x,y:v.y}),/range/);assert.equal(v.ammo.heavy,6);
call('mortar',{x:v.x+500,y:v.y});assert.equal(v.ammo.heavy,3);assert.equal(v.mortarShots.length,1);assert.throws(()=>call('mortar',{x:v.x+500,y:v.y}),/reloading/);assert.equal(v.ammo.heavy,3);
const shot=v.mortarShots[0],target={x:shot.tx,y:shot.ty,hp:1000,ship:'sailboat'},effects=[];O.tick(v,[target],shot.impact-1,()=>{},f=>effects.push(f));assert.equal(target.hp,1000);O.tick(v,[target],shot.impact,()=>{},f=>effects.push(f));assert(target.hp<1000);assert.equal(effects[0].kind,'mortarImpact');assert.equal(v.mortarShots.length,0);
call('interact');const ray=S.cannonAssignments({ship:'brig',roster:['gunner_1']})[0];walk(ray.x,ray.y);call('interact');assert.equal(call('status').voyage.me.role,'port');call('ammo_select',{ammo:'chain'});const before=v.ammo.chain;call('fire');assert.equal(v.ammo.chain,before-1);assert.equal(v.projectiles.at(-1).ammo,'chain');call('fire');assert.equal(v.ammo.chain,before-1,'Cooldown does not consume ammunition');
call('ammo_select',{ammo:'round'});v.ammo.round=0;time+=3000;assert.throws(()=>call('fire'),/Out of/);assert.equal(v.ammo.round,0);
const ownerView=call('status').voyage;assert(ownerView.canUnload,'Owner can unload without occupying the wheel');
sea.disconnect('a');call('sail');assert.equal(sea.raw('a').ammo.heavy,3,'Leaving and relaunching must not replenish ammunition');
// Stronger siege enemies, varied landmarks, identical generated world for a shared seed.
const first=Array.from({length:300},(_,i)=>S.sector('shared',i,2));assert.deepEqual(first,Array.from({length:300},(_,i)=>S.sector('shared',i,2)));const enemies=first.flat().filter(e=>e.kind==='pirate');assert(enemies.some(e=>e.siege));assert(enemies.every(e=>e.maxHp===S.SHIPS[e.ship].durability*1.6));assert(new Set(first.flat().filter(e=>e.kind==='island').map(e=>e.phase)).size>20);
console.log('PASS bank-only mortar discovery, duplicate reward, curved prediction, station authority, captain cannon denial, finite shared ammunition, cooldowns, validated targets, delayed blast damage, persistent supplies and deterministic varied world');

for(const [i,rarity] of ['Weathered','Ironbound','Runed','Abyssal'].entries()){const stash={gems:0,ammo:{round:0,chain:0,heavy:0}};O.bank(stash,[{rarity}],()=>.99);assert.equal(Object.values(stash.ammo).reduce((a,b)=>a+b,0),70+i*15);}
const light={ship:'brig',x:0,y:0,a:0,stats:{damage:70},mortarTier:'light'},heavy={...light,mortarTier:'heavy'};O.launch(light,{x:600,y:0},1000);O.launch(heavy,{x:600,y:0},1000);assert(light.mortarShots[0].x0>100,'Launch origin is the very front of the brig');assert(heavy.mortarShots[0].damage>light.mortarShots[0].damage);assert(heavy.mortarAt>light.mortarAt);assert(heavy.mortarShots[0].radius>light.mortarShots[0].radius);
const aimBody={x:0,y:0,mortarTier:'medium'},moving={x:500,y:0,a:Math.PI/2,speed:80,turnVelocity:.15};const lead=O.intercept(aimBody,moving),seconds=(2200+Math.hypot(lead.x,lead.y)*1.4)/1000,expected=S.predictCourse(moving,seconds);assert(Math.hypot(lead.x-expected.x,lead.y-expected.y)<1,'Prediction accounts for the shell flight time to its future destination');
assert(first.flat().every(e=>S.recruitCamps(e).length<=1));console.log('PASS 70–115 balls per chest, distinct mortar tiers, bow launch origin, flight-time intercept and one recruit per island');

// The real database may return fresh objects on each read; never rely on shared references.
let record=structuredClone(user);record.sea.ammo.heavy=10;record.sea.siegeEquipped=true;record.sea.mortars=['medium'];record.sea.mortarTier='medium';const databaseSea=require('./sea')({rules:{...S,sector:()=>[]},getUser:()=>structuredClone(record),save:(_,p)=>record.sea=structuredClone(p),pay:(_,n)=>record.money-=n,now:()=>time});databaseSea.handle('db',{action:'sail'});databaseSea.handle('db',{action:'mortar',x:620,y:120});databaseSea.disconnect('db');assert.equal(record.sea.ammo.heavy,7);databaseSea.handle('db',{action:'sail'});assert.equal(databaseSea.raw('db').ammo.heavy,7);console.log('PASS ammunition persistence with detached database records');
