'use strict';
const assert=require('node:assert/strict'),S=require('../js/shared/sea'),create=require('./sea');
function fixture(sector,legacy=0){let clock=1000;const user={money:100000,sea:{gems:1000,reputation:9999,ship:'sailboat',owned:['sailboat'],crew:legacy,upgrades:{},deliveries:0,kills:0}};const rules={...S,sector:(seed,x,y)=>x===0&&y===0?sector():[]};const service=create({attackRandom:()=>0,rules,getUser:()=>user,save:(_,p)=>user.sea=p,pay:(_,n)=>user.money-=n,now:()=>clock,seed:()=>1});const call=(action,extra={})=>service.handle('test',{action,...extra});const tick=(n=1,input={})=>{for(let i=0;i<n;i++){call('input',{input});clock+=100;service.tick();}return call('status').voyage;};return{call,tick,user,service};}
// Legacy crews migrate once, retain ownership and cannot be bought again.
const old=fixture(()=>[],3);old.call('status');assert.deepEqual(old.user.sea.roster,['gunner_4']);assert.equal(old.user.sea.activeCrew,'gunner_4');old.call('status');assert.equal(old.user.sea.roster.length,1);assert.throws(()=>old.call('crew',{tier:3}),/rare island/);assert.throws(()=>old.call('crew_equip',{crew:'navigator_4'}),/not owned/);
const island=()=>[{id:'island',kind:'island',name:'Rescue Cay',x:350,y:120,r:160,tier:0,recruit:{id:'navigator_3',tier:3,recruited:false},guards:[{x:300,y:120,hp:35}],looted:false}];
const f=fixture(island);f.call('sail');Object.assign(f.service.raw('test'),{x:120,y:120});assert.throws(()=>f.call('recruit'),/No recruit/);f.call('interact');f.call('recruit');assert(f.call('status').voyage.entities[0].guards.some(g=>g.hp>0),'Recruitment does not require killing nearby enemies');assert.deepEqual(f.user.sea.roster,['navigator_3']);assert.equal(f.user.sea.activeCrew,'navigator_3');assert(f.call('status').voyage.stats.speed>S.SHIPS.sailboat.speed);assert.throws(()=>f.call('recruit'),/No recruit/);f.call('rescue');assert.equal(f.user.sea.roster.length,1,'Rescued people persist even when cargo is abandoned');f.call('crew_equip',{crew:null});assert.equal(f.user.sea.activeCrew,null);f.call('crew_equip',{crew:'navigator_3'});assert.equal(f.user.sea.activeCrew,'navigator_3');
for(const c of Object.values(S.RECRUITS)){const baseline=S.stats({ship:'sailboat'}),buffed=S.stats({ship:'sailboat',activeCrew:c.id});for(const stat of Object.keys(c.buffs))assert(stat==='reload'?buffed[stat]<baseline[stat]:buffed[stat]>baseline[stat]);}
let islands=0,recruits=0;const tiers=new Set();for(let i=0;i<15000;i++){const e=S.sector('recruit-frequency-'+i,1,1)[0];if(e?.kind==='island'){islands++;if(e.recruit){recruits++;tiers.add(e.recruit.tier);}}}assert(recruits/islands>.48&&recruits/islands<.52);assert.equal(tiers.size,4);
// Individual projectiles remain perpendicular; forward targets are never homed onto.
for(const ship of Object.keys(S.SHIPS))for(let i=0;i<36;i++){const a=i*Math.PI/18,rays=S.cannonRays({ship,x:50,y:60,a});assert.equal(rays.length,S.SHIPS[ship].cannons);for(const r of rays)assert(Math.abs(r.dx*Math.cos(a)+r.dy*Math.sin(a))<1e-10);}
const start={ship:'sailboat',x:120,y:120,a:-.7},ray=S.cannonRays(start,1)[0];
const target=()=>({id:'target',kind:'pirate',ship:'sailboat',name:'Target',x:ray.x+ray.dx*250,y:ray.y+ray.dy*250,a:0,hp:38,maxHp:38,tier:0,attackAt:999999});
const combat=fixture(()=>[target()]);combat.call('sail');assert.throws(()=>combat.call('fire',{magic:true}),/removed/);combat.call('fire',{side:1});let v=combat.call('status').voyage;assert.equal(v.entities[0].hp,38,'No instant auto-aim damage');assert.equal(v.projectiles.length,1);const first=v.projectiles[0];combat.call('fire',{side:1});assert.equal(combat.call('status').voyage.projectiles.length,1);combat.call('fire',{side:-1});assert.equal(combat.call('status').voyage.projectiles.length,1,'Cannot fire both sides together');v=combat.tick(8);assert.equal(v.entities[0].hp,0);assert.equal(v.cargo.length,1);combat.tick(30);combat.call('fire',{side:1});combat.tick(10);assert.equal(combat.call('status').voyage.cargo.length,1);
const miss=fixture(()=>[{...target(),x:120+Math.cos(-.7)*300,y:120+Math.sin(-.7)*300,hp:9999}]);miss.call('sail');miss.call('fire',{side:1});v=miss.tick(9);assert.equal(v.entities[0].hp,9999,'Forward target must be missed');assert(v.projectiles.length<=80);
const turn=fixture(()=>[]);turn.call('sail');v=turn.tick(1,{right:true});const initial=v.turnVelocity;assert(initial>0&&initial<S.SHIPS.sailboat.turning*Math.PI/180);v=turn.tick(5,{right:true});assert(v.turnVelocity>initial);const before=v.turnVelocity;v=turn.tick(1,{});assert(v.turnVelocity>0&&v.turnVelocity<before,'Rudder releases smoothly');
const blocking=fixture(()=>[{...target(),x:ray.x+ray.dx*430,y:ray.y+ray.dy*430,hp:9999},{id:'wall',kind:'island',x:ray.x+ray.dx*220,y:ray.y+ray.dy*220,r:80,guards:[],tier:0}]);blocking.call('sail');blocking.call('fire',{side:1});blocking.tick(10);assert.equal(blocking.call('status').voyage.entities[0].hp,9999,'The island intercepts cannonballs');
const beast=()=>[{id:'beast',kind:'kraken',name:'Great Kraken',x:420,y:120,hp:9999,maxHp:9999,tier:0,attackAt:0}];const slam=fixture(beast);slam.call('sail');Object.assign(slam.service.raw('test'),{x:120,y:120});v=slam.tick();const strike=v.entities[0].attack,health=v.hp;assert(strike&&strike.impact-strike.start===2100);v=slam.tick(20);assert.equal(v.hp,health,'No damage during windup');v=slam.tick();assert.equal(v.hp,health-127);assert(v.fx.some(f=>f.kind==='slam'&&f.hit));
const dodge=fixture(beast);dodge.call('sail');Object.assign(dodge.service.raw('test'),{x:120,y:120});dodge.service.raw('test').a=Math.PI;v=dodge.tick();const locked={...v.entities[0].attack.target},beforeHit=v.hp;v=dodge.tick(21,{forward:true});assert.equal(v.hp,beforeHit,'Sailing clear of the marked point dodges the slam');assert.deepEqual(v.entities[0].attack.target,locked,'An attack cannot retarget after windup starts');
console.log('PASS legacy migration, rare tier spawns, rescue persistence, all 12 crew buffs, cannon geometry/travel/cooldowns/misses, removed Arcane Volley and rudder inertia');

// Reject unspecified/both-side firing at the authority boundary.
const single=fixture(()=>[]);single.call('sail');for(const side of [undefined,0,2,'1'])assert.throws(()=>single.call('fire',{side}),/Choose Q/);
single.call('fire',{side:-1});single.call('fire',{side:1});assert.equal(single.call('status').voyage.projectiles.length,1);single.tick(7);single.call('fire',{side:1});assert(single.call('status').voyage.projectiles.some(p=>p.side===1));
// The awareness envelope extends beyond every cannonball's reachable hit area.
const distant=fixture(()=>[{...beast()[0],x:ray.x+ray.dx*720,y:ray.y+ray.dy*720}]);distant.call('sail');let far=distant.tick();assert(far.entities[0].engaged,'Kraken responds before it can be peppered at maximum range');const startDist=Math.hypot(far.entities[0].x-far.x,far.entities[0].y-far.y);far=distant.tick(4);assert(Math.hypot(far.entities[0].x-far.x,far.entities[0].y-far.y)<startDist);
// Injected attacks repeat independently of the previous attack count.
v=slam.tick(46);assert.equal(v.entities[0].attack.type,'slap');assert.equal(v.entities[0].attack.targets.length,1);
// Melee is timed, front-facing and interrupts a defender's windup.
const duel=fixture(()=>[{...island()[0],recruit:null,guards:[{x:260,y:120,hp:75}]}]);duel.call('sail');duel.call('interact');v=duel.tick();assert(v.entities[0].guards[0].attack);const health0=v.hp;duel.call('fire');assert.equal(duel.call('status').voyage.entities[0].guards[0].hp,75);v=duel.tick(2);assert.equal(v.entities[0].guards[0].hp,40);assert.equal(v.entities[0].guards[0].attack,null);v=duel.tick(3);assert.equal(v.hp,health0,'Interrupted attacks do not deal damage');
const escape=fixture(()=>[{...island()[0],recruit:null,guards:[{x:260,y:120,hp:75}]}]);escape.call('sail');escape.call('interact');v=escape.tick();const h0=v.hp;v=escape.tick(7,{forward:true,walkAngle:Math.PI/2});assert.equal(v.hp,h0,'Walking out of a guard tell avoids the hit');
// Shared movement is independent of the render frame rate and slides at shore.
const base={x:1000,y:1000,a:0,speed:0,turnVelocity:0,magic:60,hp:700,wind:.4,stats:S.stats({ship:'sailboat'})},a={...base},b={...base};for(let i=0;i<10;i++)S.moveShip(a,{forward:true,right:true},.1);for(let i=0;i<60;i++)S.moveShip(b,{forward:true,right:true},1/60);assert(Math.hypot(a.x-b.x,a.y-b.y)<1e-7);assert(Math.abs(a.a-b.a)<1e-7);
const landmass={id:'walk',x:0,y:0,r:180},walker={x:0,y:0};S.moveFoot(walker,{forward:true,walkAngle:0},.1,landmass);assert.equal(walker.x,14);assert.equal(walker.y,0);walker.x=158;S.moveFoot(walker,{forward:true,right:true,walkAngle:0},.1,landmass);assert(walker.y>0);assert(Math.hypot(walker.x,walker.y)<=158.001);
console.log('PASS single-side authority, Kraken awareness and paired strikes, timed melee, interruption/dodge, frame-independent steering and camera-relative shore sliding');
