'use strict';
const assert=require('node:assert/strict'),S=require('../js/shared/sea'),create=require('./crew-sea'),C=require('./sea-companions')(S);
const island=(seed='fort-test')=>S.expeditionIsland({id:'fort-island',kind:'island',name:'Fort Isle',x:2400,y:120,r:1800,tier:1,phase:Math.PI,lobes:4,recruits:[],guards:[],biome:'ruins',looted:false},S.random(seed));
let forts=0;for(let i=0;i<1000;i++){const e=island('fort-'+i);if(e.fort){forts++;assert(e.chests.filter(c=>c.fort).length>=9);assert(e.chests.filter(c=>!c.cave&&Math.abs(c.x-e.fort.x)<=e.fort.r&&Math.abs(c.y-e.fort.y)<=e.fort.r).length<=12);assert(e.guards.filter(g=>g.fort).length>=16);assert(e.guards.filter(g=>g.fort&&g.weapon==='gun').length>=10);}assert(e.guards.length>=e.chests.filter(c=>!c.fort).length/2,'Several soldiers guard the same cache');}assert(forts>230&&forts<330);assert.deepEqual(island(),island());
const e=island();S.addFort(e,S.random('force'));const f=e.fort;
assert(S.landShotBlocked(e,{x:f.x-250,y:f.y},{x:f.x,y:f.y}),'Walls stop shots');assert(!S.landShotBlocked(e,{x:f.x,y:f.y+220},{x:f.x,y:f.y+110}),'The fort gate remains open');let body={x:f.x-300,y:f.y};for(let i=0;i<1000&&Math.hypot(body.x-f.x,body.y-f.y)>15;i++){const goal=S.landWaypoint(e,body,f),a=Math.atan2(goal.y-body.y,goal.x-body.x);body.x+=Math.cos(a)*5;body.y+=Math.sin(a)*5;S.constrainFoot(body,e);}assert(Math.hypot(body.x-f.x,body.y-f.y)<20,'NPC route enters the fort through the gate');
const boat={x:600,y:600},anchor=S.islandAnchor(e,boat);assert(Math.abs(Math.hypot(anchor.x-e.x,anchor.y-e.y)/(e.r*S.shoreFactor(e,Math.atan2(anchor.y-e.y,anchor.x-e.x)))-.9)<1e-6);const radialA=Math.atan2(boat.y-e.y,boat.x-e.x),radial={x:e.x+Math.cos(radialA)*e.r*.9*S.shoreFactor(e,radialA),y:e.y+Math.sin(radialA)*e.r*.9*S.shoreFactor(e,radialA)};assert(Math.hypot(anchor.x-boat.x,anchor.y-boat.y)<=Math.hypot(radial.x-boat.x,radial.y-boat.y)+.02);
let time=1000;const user={money:1e6,sea:{crewVersion:2,ship:'brig',owned:['brig'],gems:0,roster:[],upgrades:{},reputation:0}},land={id:'cay',kind:'island',x:350,y:120,r:160,tier:0,guards:[],looted:false};const sea=create({rules:{...S,sector:(seed,x,y)=>x||y?[]:[land]},getUser:()=>user,save:(_,p)=>user.sea=p,pay:()=>{},now:()=>time,seed:()=>12});const call=(action,extra={})=>sea.handle('a',{action,...extra}),view=()=>call('status').voyage;call('sail');call('lasso');const link=view().boarding[0];assert(link.permanent&&link.until===null&&link.anchor);for(let i=0;i<650;i++){time+=100;call('input',{input:{}});sea.tick();}assert.equal(view().boarding.length,1,'Island rope survives beyond 45 seconds');call('lasso');assert.equal(view().boarding.length,0);
function walk(x,y){for(let i=0;i<400;i++){const p=view().me;if(Math.hypot(x-p.x,y-p.y)<2)break;call('input',{input:{forward:true,walkAngle:Math.atan2(y-p.y,x-p.x)+(p.place==='island'?0:view().shipA)}});time+=20;sea.tick();}call('input',{input:{}});}
walk(-29,0);call('interact');const before=view();call('fire');assert.equal(view().notice,before.notice,'Captain attack is quiet');assert.equal(view().projectiles.length,before.projectiles.length);call('interact');call('board');call('weapon',{weapon:'gun'});assert.equal(view().me.weapon,'gun');let p=view().me;land.guards=[{id:'target',x:p.x+90,y:p.y,hp:200,weapon:'gun',a:Math.PI}];call('input',{input:{walkAngle:0}});call('fire');assert.equal(land.guards[0].hp,135);call('fire');assert.equal(land.guards[0].hp,135,'Reload prevents repeated shots');assert(view().landShots.length);assert.throws(()=>call('weapon',{weapon:'invalid'}),/Choose/);
time+=500;sea.tick();assert.equal(land.guards[0].attack.type,'gun');const hp=view().me.hp;for(let i=0;i<25;i++){time+=50;call('input',{input:{}});sea.tick();}assert(view().me.hp<hp,'Enemy musket can damage a stationary player');call('weapon',{weapon:'sword'});assert.equal(view().me.weapon,'sword');
// Looters deploy despite living defenders, and keep their load while fleeing toward help.
const room={code:'LOOT',mission:'loot',links:[{id:'loot',permanent:true}],helpers:[]},ship={x:0,y:0,a:0,ship:'brig',roster:['looter_1','fighter_1'],cargo:[],stats:{cargo:20}},loot={id:'loot',kind:'island',x:300,y:0,r:300,tier:0,guards:[{x:390,y:0,hp:200}],chests:[{id:'chest',x:300,y:0,tier:0,taken:false}],looted:false};C.sync(room,ship);const looter=room.helpers.find(h=>h.kind==='looter'),fighter=room.helpers.find(h=>h.kind==='fighter');fighter.state='recovering';fighter.hp=0;let deployed=false;for(let i=0;i<1200&&!looter.load.length;i++){time+=100;C.tick(room,ship,[loot],time,.1);deployed||=looter.place==='island';}assert(deployed);assert(looter.load.length,'Living guards no longer prohibit looter pickup');const ally={place:'island',island:'loot',boarded:null,x:looter.x-100,y:looter.y,hp:100};C.hurt(looter,20,time);const distance=Math.hypot(looter.x-ally.x,looter.y-ally.y);C.tick(room,ship,[loot],time+100,.1,[ally]);assert.equal(looter.state,'fleeing');assert(Math.hypot(looter.x-ally.x,looter.y-ally.y)<distance);assert.equal(looter.load.length,1,'Fleeing keeps carried treasure');
console.log('PASS fort chance, clustered gunners, fort gate navigation and cover, nearest shore anchor, permanent island ropes, quiet captain, player flintlock/reload, enemy musket damage and looter retreat with loot');

