'use strict';
const assert=require('node:assert/strict'),S=require('../js/shared/sea'),create=require('./crew-sea'),C=require('./sea-companions')(S);
let islands=0,recruits=0;const tiers=[0,0,0,0],roles={};
for(let i=0;i<20000;i++){const e=S.sector('camp-odds-'+i,1,1)[0];if(e?.kind!=='island')continue;islands++;const camps=S.recruitCamps(e);assert(camps.length<=1);for(const c of camps){recruits++;tiers[c.tier-1]++;const role=S.RECRUITS[c.id].role;roles[role]=(roles[role]||0)+1;assert.equal(c.cave,null);assert(S.terrainHeight(e,c.x,c.y)>0);assert(e.caves.every(v=>Math.hypot(v.x-c.x,v.y-c.y)>160),'Camp stays away from cave entrances');}}
assert(islands/20000>.33&&islands/20000<.37);assert(Math.abs(recruits/islands-.5)<.025);[.55,.28,.13,.04].forEach((p,i)=>assert(Math.abs(tiers[i]/recruits-p)<.025));assert(Math.abs(roles.sailor/recruits-.06)<.015);assert(Math.abs(roles.mechanic/recruits-.06)<.015);
for(let seed=0;seed<10;seed++)for(let bx=-3;bx<=3;bx++)for(let by=-3;by<=3;by++){let count=0;for(let dx=0;dx<2;dx++)for(let dy=0;dy<2;dy++)count+=S.sector(seed,bx*2+dx,by*2+dy)[0]?.kind==='island'?1:0;assert(count>=1,'Every four-sector area contains an island, including the harbor region');}
let time=1000;const user={money:1e6,sea:{crewVersion:2,ship:'brig',owned:['brig'],roster:['looter_1'],gems:0,upgrades:{}}};
const camp={id:'camp',kind:'island',x:350,y:120,r:160,tier:0,guards:[{id:'enemy',x:215,y:120,hp:200}],recruits:[{id:'looter_1',x:215,y:120,cave:null,recruited:false}],chests:[]};
const sea=create({rules:{...S,sector:(_,x,y)=>!x&&!y?[camp]:[]},getUser:()=>user,save:(_,p)=>user.sea=p,pay:()=>{},now:()=>time,seed:()=>1});
const call=(action,args={})=>sea.handle('a',{action,...args});call('sail');Object.assign(sea.raw('a'),{x:120,y:120});assert(!camp.recruits[0].recruited,'Ownership cannot hide a camp shared with other players');call('board');call('recruit');assert.equal(camp.guards[0].hp,200);assert.deepEqual(user.sea.roster,['looter_1','looter_1']);assert.throws(()=>call('recruit'),/Approach/);const helpers=call('status').voyage.companions.filter(h=>h.kind==='looter');assert.equal(helpers.length,2);assert.equal(new Set(helpers.map(h=>h.user)).size,2);assert.deepEqual(helpers.map(h=>h.rosterIndex),[0,1]);call('crew_dismiss',{crew:'looter_1',rosterIndex:0});assert.equal(call('status').voyage.companions.filter(h=>h.kind==='looter').length,1);
// Stream thousands of sectors, keeping only tiny progress markers and nine live sectors.
const saved=[];const traveler={money:0,sea:{crewVersion:2,ship:'brig',owned:['brig'],roster:[],gems:0,upgrades:{}}};
const ocean=create({rules:{...S,sector:(_,x,y)=>y===0&&x%4===0?[{id:'i'+x,kind:'island',x:x*S.SECTOR+3000,y:3000,r:100,tier:0,guards:[],recruits:[],chests:Array.from({length:70},(_,i)=>({id:'i'+x+':chest:'+i,x:x*S.SECTOR+3000,y:3000,tier:0,taken:false}))}]:[]},getUser:()=>traveler,save:(_,p)=>saved.push(JSON.stringify(p)),pay:()=>{},now:()=>time,seed:()=>1});
ocean.handle('t',{action:'sail'});const boat=ocean.raw('t');for(let i=1;i<=4105;i++){boat.x=i*4*S.SECTOR;boat.y=120;boat.hp=boat.stats.durability;time+=5;boat.lastInput=time;ocean.tick();const e=[...boat.sectors.values()].flat().find(e=>e.kind==='island');e.chests[69].taken=true;const stats=ocean.diagnostics('t');assert(stats.worldSectors<=9&&stats.progressIslands<=4096&&stats.spentEntities<=4096);}
const lastX=boat.x;boat.x+=4*S.SECTOR;time+=5;ocean.tick();boat.x=lastX;time+=5;ocean.tick();assert([...boat.sectors.values()].flat().find(e=>e.kind==='island').chests[69].taken,'Progress beyond bit 32 survives unloading');ocean.disconnect('t');ocean.tick();assert.equal(ocean.diagnostics('t').worldSectors,0);assert(saved.every(s=>!s.includes('chest:')&&!s.includes('sectors')&&!s.includes('hills')),'World geometry and explored map are never saved to profiles');
console.log(`PASS ${(recruits/islands*100).toFixed(1)}% recruit rate, unchanged rarity, surface-safe camps, guaranteed island distribution, recruitment beside live enemies and duplicate companions. 4,105 sector transitions remain bounded and unload all world geometry on disconnect.`);
