'use strict';
const assert=require('node:assert/strict'),S=require('../js/shared/sea'),create=require('./crew-sea');
const generate=()=>S.expeditionIsland({id:'highlands',kind:'island',name:'Highlands',x:2400,y:120,r:1800,tier:1,phase:Math.PI,lobes:4,recruits:[],guards:[],biome:'ruins',looted:false},S.random('playtest-highlands'));
const template=generate();assert.deepEqual(template,generate());assert(template.chests.length>=20);assert(template.caves.length>=2);assert(template.hills.length===9);assert(template.chests.some(c=>c.cave));assert(template.chests.some(c=>!c.cave));assert(Math.max(...template.hills.map(h=>S.terrainHeight(template,h.x,h.y)))>150);
for(const cave of template.caves){const p={x:cave.x+10000,y:cave.y-10000};S.constrainCave(p,cave);const fixed={...p};S.constrainCave(p,cave);assert(Math.hypot(p.x-fixed.x,p.y-fixed.y)<.001,'Cave boundary projection is stable');for(let i=1;i<cave.rooms.length;i++){const a=cave.rooms[i-1],b=cave.rooms[i],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};const start={...mid};S.constrainCave(mid,cave);assert.deepEqual(mid,start,'Connected chamber paths remain traversable');}}
for(const ship of Object.keys(S.SHIPS)){const v={ship,x:0,y:0,a:0,siege:true,roster:['sailor_1']};assert.equal(S.nearestStation({x:-29,y:0},v).id,'wheel');assert.equal(S.nearestStation({x:-18,y:0},v).id,'sailor');assert.equal(S.nearestStation({x:0,y:0},v).id,'hatch');}
let time=1000;const user={money:1e6,sea:{crewVersion:2,ship:'brig',owned:['brig'],gems:0,roster:['sailor_4'],upgrades:{},reputation:0}};
const sea=create({rules:{...S,sector:(seed,x,y)=>{if(x||y)return[];const e=generate();e.guards=[];return[e];}},getUser:()=>user,save:(_,p)=>user.sea=p,pay:(_,n)=>user.money-=n,now:()=>time,seed:()=>17});
const call=(action,extra={})=>sea.handle('a',{action,...extra}),view=()=>call('status').voyage;
call('sail');const ship=sea.raw('a');ship.x=682;ship.y=120;ship.a=0;
let sawHop=false,maxHeight=0;function walk(x,y,tolerance=12){for(let i=0;i<1400;i++){const p=view().me;if(Math.hypot(p.x-x,p.y-y)<tolerance)break;call('input',{input:{forward:true,walkAngle:Math.atan2(y-p.y,x-p.x)+(p.place==='island'?0:ship.a)}});time+=50;sea.tick();const q=view().me;sawHop||=q.hopAt>0;maxHeight=Math.max(maxHeight,q.groundHeight);}call('input',{input:{}});}
call('board');assert.equal(view().me.place,'island');const cave=template.caves[0];walk(cave.x,cave.y);call('interact');assert.equal(view().me.cave,cave.id);assert.equal(view().me.groundHeight,5);assert.throws(()=>call('board'),/Exit the cave/);
const cache=template.chests.find(c=>c.cave===cave.id);walk(cache.x,cache.y);call('interact');assert(view().me.carrying);assert(!view().entities[0].looted,'One chest never clears the whole island');assert(view().entities[0].chests.find(c=>c.id===cache.id).taken);walk(cave.x,cave.y);call('interact');assert.equal(view().me.cave,null);assert(view().me.carrying,'Cave exit preserves carried loot');walk(925.8,120);call('board');assert.equal(view().me.place,'deck');walk(0,0,2);call('interact');walk(24,0,2);call('interact');assert.equal(ship.cargo.length,1);
walk(0,0,2);call('interact');call('board');const hill=template.hills[0];walk(hill.x,hill.y,30);assert(sawHop,'Walking uphill automatically triggers climbing hops');assert(maxHeight>80,'The player ascends actual elevated terrain');
// A voyage can stream sectors without respawning collected treasure.
ship.x=50000;ship.y=50000;time+=100;sea.tick();ship.x=682;ship.y=120;time+=100;sea.tick();assert(view().entities.find(e=>e.id===template.id).chests.find(c=>c.id===cache.id).taken);
// No rendered enemies: the sailor leaves the current area and keeps searching.
const base=create({rules:{...S,sector:()=>[]},getUser:()=>user,save:()=>{},pay:()=>{},now:()=>time,seed:()=>123});base.handle('p',{action:'sail'});const patrol=base.raw('p');patrol.x=10000;patrol.y=10000;patrol.hp=1e6;base.handle('p',{action:'sailor',mode:'patrol'});const start={x:patrol.x,y:patrol.y};for(let i=0;i<1000;i++){base.handle('p',{action:'input',input:{}});time+=100;base.tick();}assert(Math.hypot(patrol.x-start.x,patrol.y-start.y)>S.SECTOR/2);assert(patrol.autopilot.searchStep>=2);assert.equal(patrol.autopilot.state,'Searching new waters');
console.log('PASS deterministic highlands, connected caves, nearest stations, cave loot/exit/stow, giant shore return, automatic hill climbing, streamed loot retention and sailor exploration');

