'use strict';
const assert=require('node:assert/strict'),S=require('../js/shared/sea'),Mechanic=require('./sea-mechanic')(S);
const ship={x:0,y:0,a:0,roster:['mechanic_1'],hp:500,stats:{durability:1000}},room={code:'TEST',holes:[{id:'one',x:-26,y:-9},{id:'two',x:25,y:8}],flood:30};
Mechanic.tick(room,ship,1000,.1);assert.equal(room.mechanic.state,'repairing');assert.equal(room.holes.length,2);Mechanic.tick(room,ship,25999,.1);assert.equal(room.holes.length,2);Mechanic.tick(room,ship,26000,.1);assert.equal(room.holes.length,1);assert.equal(ship.hp,550);assert.equal(room.flood,20);
Mechanic.tick(room,ship,26100,.1);assert(room.mechanic.moving);assert(room.mechanic.x>-26);ship.roster=[];Mechanic.tick(room,ship,50000,.1);assert.equal(room.mechanic,null);assert.equal(room.holes.length,1,'Dismissed mechanic cannot finish queued repairs');
ship.roster=['mechanic_1','mechanic_4'];Mechanic.tick(room,ship,51000,.1);assert.equal(room.mechanic.tier,4);assert(!S.cannonAssignments({ship:'brig',roster:ship.roster}).length);
let islands=0,pirates=0,krakens=0,camps=0,sailors=0,mechanics=0,occupied=0;for(let i=0;i<60000;i++){const e=S.sector('refresh-'+i,1,1)[0];if(!e)continue;if(e.kind==='pirate')pirates++;if(e.kind==='kraken')krakens++;if(e.kind!=='island')continue;islands++;assert(e.r>=1300&&e.r<=2300);assert.equal(e.campSites.length,4);const recruits=S.recruitCamps(e);assert(recruits.length<=1,'Only one recruit can spawn on an island');if(recruits.length)occupied++;camps+=recruits.length;for(const c of recruits){assert(Math.hypot(c.x-e.x,c.y-e.y)<e.r*.6);if(c.id.startsWith('sailor'))sailors++;if(c.id.startsWith('mechanic'))mechanics++;}}
assert(Math.abs(islands/60000-.4375*.8)<.012);assert(Math.abs(pirates/60000-.5625*.258*1.15)<.009);assert(Math.abs(krakens/60000-.5625*.026*1.05*1.2)<.002);assert(occupied/islands>.48&&occupied/islands<.52);assert(mechanics>80&&Math.abs(mechanics-sailors)<4*Math.sqrt(mechanics+sailors),'Mechanics and sailors share the same rarity');
// Multiple physical camps can be rescued independently from the same island.
const create=require('./sea'),user={money:1e5,sea:{crewVersion:2,roster:[],ship:'sailboat',owned:['sailboat'],gems:0,upgrades:{},reputation:0}},island={id:'multi',kind:'island',x:400,y:120,r:300,tier:0,guards:[],recruits:[{id:'mechanic_1',tier:1,x:220,y:120},{id:'sailor_1',tier:1,x:520,y:120}]};
const sea=create({rules:{...S,sector:(s,x,y)=>x===0&&y===0?[island]:[]},getUser:()=>user,save:()=>{},pay:()=>{},now:()=>1000});sea.handle('x',{action:'sail'});const v=sea.raw('x');v.onFoot='multi';v.x=220;v.y=120;sea.handle('x',{action:'recruit'});assert.equal(island.recruits[0].recruited,true);assert(!island.recruits[1].recruited);v.x=520;sea.handle('x',{action:'recruit'});assert.deepEqual(user.sea.roster,['mechanic_1','sailor_1']);assert.equal(user.sea.activeCrew,undefined,'Automatic roles do not consume specialist slots');
console.log('PASS slow sequential mechanic repairs, dismissal cancellation, strongest mechanic, independent camp rescue, equal sailor/mechanic rarity, larger islands, 50% camps and stable naval density');
