/* Bounded per-player voyages. Only banked progression is persisted. */
'use strict';
const crypto=require('node:crypto');
module.exports=function createSea({rules:S,getUser,save,pay,now=Date.now,seed=()=>crypto.randomBytes(12).toString('hex'),maxSessions=64,externalTargets=()=>[],combatants=()=>[],hurtPlayer=()=>{},independentTentacles=false,attackRandom=Math.random}){
 const leviathanRewards=require('./sea-leviathan-rewards')(),voyages=new Map(),navigation=require('./sea-navigation')(S),ordnance=require('./sea-ordnance')(S),leviathanAttack=require('./sea-leviathan')(S,attackRandom),tentacles=require('./sea-tentacles')(S,attackRandom);
 const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
 function profile(user){const u=getUser(user);let changed=false;if(!u.sea){u.sea={gems:0,reputation:0,ship:null,owned:[],upgrades:{hull:0,sails:0,cannons:0},deliveries:0,kills:0};changed=true;}const p=u.sea;ordnance.initialize(p);const live=voyages.get(user);if(live)p.ammo=live.ammo;if(p.crewVersion!==2){p.roster=Number(p.crew)>0?['gunner_'+Math.min(4,Number(p.crew)+1)]:[];p.activeCrew=p.roster[0]||null;p.crewVersion=2;delete p.crew;changed=true;}p.extraCrew=(p.extraCrew||[]).filter(id=>p.roster.includes(id)&&id!==p.activeCrew).slice(0,p.ship==='brig'?1:0);if(changed)save(user,p);return p;}
 function persist(user,p){save(user,p);}
 function nearby(v){const cx=Math.floor(v.x/S.SECTOR),cy=Math.floor(v.y/S.SECTOR);if(v.sectorX===cx&&v.sectorY===cy)return;v.sectorX=cx;v.sectorY=cy;const wanted=new Set();
  for(let y=cy-1;y<=cy+1;y++)for(let x=cx-1;x<=cx+1;x++){const key=x+':'+y;wanted.add(key);if(!v.sectors.has(key))v.sectors.set(key,v.completed.size>=S.MAX_SEEN?[]:S.sector(v.seed,x,y).filter(e=>e.kind==='island'||!v.completed.has(e.id)).map(e=>{if(e.kind==='island'&&v.completed.has(e.id)){e.looted=true;S.treasureCaches(e).forEach(c=>c.taken=true);e.guards.forEach(g=>g.hp=0);}return e;}));}
  for(const key of v.sectors.keys())if(!wanted.has(key))v.sectors.delete(key);
  const land=S.obstacles(entities(v));for(const e of entities(v))if(e.kind!=='island')S.clearWater(e,e.kind==='kraken'?S.KRAKEN_RADIUS:S.hullRadius(e.ship),land);
 }
 const entities=v=>[...v.sectors.values()].flat();
 function emit(v,fx){v.fx.push(fx);if(v.fx.length>12)v.fx.splice(0,v.fx.length-12);}
 function notice(v,text){v.notice=text;}
 function chest(v,tier,source){if(v.cargo.length>=v.stats.cargo){notice(v,'Hold full. Return home to unload.');return;}v.cargo.push(S.treasureReward(v.seed,source,tier));}
 function complete(v,e){if(v.completed.size<S.MAX_SEEN)v.completed.add(e.id);if(v.completed.size>=S.MAX_SEEN)notice(v,'Your chart is full. Return to the neighborhood.');}
 function sink(user,v){persist(user,profile(user));voyages.delete(user);return {ended:true,reason:'Your ship sank. Unbanked cargo was lost; your owned ship is safe at the Shipwright.',profile:profile(user),money:getUser(user).money};}
 function defeated(v,e){if(e.playerShip||!e.kind||e.kind==='island')return;if(e.hp>0||v.completed.has(e.id))return;e.deathAt=now();complete(v,e);if(e.kind==='kraken'){for(const allocation of leviathanRewards.settle(e,voyages.values())){const b=allocation.ship;complete(b,e);for(let i=0;i<allocation.count;i++){const reward=S.treasureReward(b.seed,e.id+':'+i,Math.min(3,(e.tier||0)+1));if(i===0)reward.gems+=Math.round((35+(e.tier||0)*15)*(e.great?3:1)*allocation.share);b.cargo.push(reward);}b.kills++;notice(b,e.name+' defeated. '+allocation.count+' sealed chests recovered ('+Math.round(allocation.share*100)+'% contribution).');}return;}if(e.kind==='pirate'){ordnance.supply(v.ammo,e.tier||0);v.ammoDirty=true;}const cargoBefore=v.cargo.length;chest(v,Math.min(3,e.tier+(e.kind==='kraken'?1:0)),e.id);if(e.kind==='kraken'&&v.cargo.length>cargoBefore){const reward=v.cargo[v.cargo.length-1];reward.gems+=(35+e.tier*15)*(e.great?3:1);}v.kills++;notice(v,e.name+' defeated. Sealed chest recovered.'+(e.kind==='pirate'?' Ammunition salvaged: '+(70+(e.tier||0)*15)+' balls.':''));}
 function attack(v,side=0,auto=false,aim=null){const time=now();if(v.onFoot){if(time<v.meleeAt)return;v.meleeAt=time+460;
  const island=entities(v).find(e=>e.id===v.onFoot),near=island?.guards.filter(g=>g.hp>0&&dist(g,v)<85).sort((a,b)=>dist(a,v)-dist(b,v));
  // A short aim assist faces nearby defenders; the swing still has a front arc.
  if(near?.length)v.walkA=Math.atan2(near[0].y-v.y,near[0].x-v.x);
  v.swing={start:time,impact:time+150,end:time+440,a:v.walkA||0};
  return;
 }
 if(!auto&&![-1,1].includes(side))throw Error('Choose Q (port) or E (starboard).');
 const manual=auto||aim&&Number.isFinite(aim.cannonX);if(!manual&&time<(v.volleyAt||0))return;v.fireCannons=v.fireCannons||{};
 const land=S.obstacles(entities(v)),targets=[...entities(v),...externalTargets(v)].filter(e=>e.hp>0&&e.kind!=='island'&&now()>=(e.protectedUntil||0));
 for(const flank of (auto?[-1,1]:[side])){if(!manual&&time<(v.fireSides[flank]||0))continue;let rays=S.cannonRays(v,flank);if(auto){const assigned=S.cannonAssignments(v);rays=rays.filter(ray=>assigned.some(n=>n.cannon===ray.key)&&!(v.occupiedCannons||[]).includes(ray.key));}if(aim&&Number.isFinite(aim.cannonX)){rays=[rays.reduce((best,ray)=>Math.abs((ray.x-v.x)*Math.cos(v.a)+(ray.y-v.y)*Math.sin(v.a)-aim.cannonX)<Math.abs((best.x-v.x)*Math.cos(v.a)+(best.y-v.y)*Math.sin(v.a)-aim.cannonX)?ray:best)];}rays=rays.filter(ray=>time>=(v.fireCannons[ray.key]||0));if(!rays.length)continue;if(aim){const turn=clamp(Number(aim.aim)||0,-.95,.95),elevation=clamp(Number.isFinite(aim.elevation)?aim.elevation:.12,-.2,.8);rays=rays.map(ray=>S.cannonMuzzle(v,ray,turn,elevation,time));}else rays=rays.map(ray=>S.cannonMuzzle(v,ray,0,.12,time));
  if(auto&&!rays.some(ray=>{const end={x:ray.x+ray.dx*S.CANNON_RANGE,y:ray.y+ray.dy*S.CANNON_RANGE};return targets.some(e=>S.segmentHit(ray,end,e,e.kind==='kraken'?S.KRAKEN_RADIUS*.37:S.hullRadius(e.ship))!==null&&!S.blockedSeaLine(ray,e,land));}))continue;
  const ammoId=aim?.ammo||v.selectedAmmo||'round',ammo=S.AMMO[ammoId];if(!ammo)throw Error('Unknown cannonball type.');rays=rays.slice(0,v.ammo[ammoId]||0);if(!rays.length){if(!auto)throw Error('Out of '+ammo.name+'. Buy supplies at the Shipwright.');continue;}if(v.projectiles.length+rays.length>80)continue;v.ammo[ammoId]-=rays.length;v.ammoDirty=true;if(!manual){v.volleyAt=time+650;v.fireSides[flank]=time+v.stats.reload*1000;}for(const ray of rays)v.fireCannons[ray.key]=time+v.stats.reload*1000;
  for(const ray of rays){v.projectiles.push({...ray,id:++v.shotId,born:time,updatedAt:time,x0:ray.x,y0:ray.y,travel:0,height:ray.height,barrelElevation:aim?.elevation??.12,elevation:ray.elevation??aim?.elevation??.12,range:aim&&Number.isFinite(aim.cannonX)?S.CANNON_RANGE*(.5+clamp(Number(aim.elevation)||0,-.2,.8)):S.CANNON_RANGE,damage:v.stats.damage*ammo.damage,ammo:ammoId});v.projectiles[v.projectiles.length-1].range*=ammo.range;emit(v,{kind:'muzzle',x:ray.x,y:ray.y,height:ray.height,side:flank,born:time,until:time+350});}
  if(!auto)return; // Each NPC can fire only its assigned cannon.
 }
 }
 function projectiles(v,dt,time){const land=S.obstacles(entities(v)),targets=[...entities(v),...externalTargets(v)].filter(e=>e.hp>0&&e.kind!=='island'&&now()>=(e.protectedUntil||0));v.projectiles=v.projectiles.filter(p=>{const step=Math.min(S.CANNON_SPEED*Math.exp(-.28*Math.max(0,(time-p.born)/1000))*Math.min(dt,Math.max(0,(time-p.updatedAt)/1000)),(p.range||S.CANNON_RANGE)-p.travel),end={x:p.x+p.dx*step,y:p.y+p.dy*step};let first=1,target=null,hit=false;
  for(const island of land){const t=S.segmentHit(p,end,island,island.r+5);if(t!==null&&t<=first){first=t;target=null;hit=true;}}
  for(const e of targets){if(e.hp<=0)continue;const t=S.segmentHit(p,end,e,e.kind==='kraken'?S.KRAKEN_RADIUS*.37:S.hullRadius(e.ship));if(t!==null&&t<first){first=t;target=e;hit=true;}}
  p.x+=(end.x-p.x)*first;p.y+=(end.y-p.y)*first;p.travel+=step*first;p.updatedAt=time;
  if(hit){if(target){leviathanRewards.record(target,v,Math.min(target.hp,p.damage));target.hp=Math.max(0,target.hp-p.damage);if(p.ammo==='chain')target.slowUntil=time+4000;target.aggroUntil=time+20000;target.engaged=true;target.hitAt=time;defeated(v,target);}emit(v,{kind:'hit',x:p.x,y:p.y,born:time,until:time+2800});return false;}
  if(p.travel>=(p.range||S.CANNON_RANGE)){emit(v,{kind:'splash',x:p.x,y:p.y,born:time,until:time+2800});return false;}return true;
 });}
 function recruit(user,v){const island=entities(v).find(e=>e.id===v.onFoot),offer=S.recruitCamps(island).filter(c=>!c.recruited).sort((a,b)=>dist(a,v)-dist(b,v))[0];if(!offer||offer.recruited)throw Error('No recruit here. Look for a signal camp on an island.');if(dist(v,offer)>65)throw Error('Walk closer to the recruit camp.');if(v.cave)throw Error('Recruit camps are above ground. Exit the cave first.');const p=profile(user),member=S.RECRUITS[offer.id];if(!member)throw Error('Unknown recruit.');p.roster.push(member.id);offer.recruited=true;v.roster=p.roster.slice();if(!p.activeCrew&&!['fighter','looter','mechanic','sailor'].includes(member.role)){p.activeCrew=member.id;const fraction=v.hp/v.stats.durability;v.stats=S.stats(p);v.hp=v.stats.durability*fraction;v.crewId=member.id;v.auto=true;}persist(user,p);notice(v,member.name+' rescued! '+member.description+'. Permanently added to your roster.');}
 function tick(){const time=now();for(const [user,v] of voyages){const dt=Math.min(.25,Math.max(0,(time-v.tickAt)/1000));v.tickAt=time;if(time-v.started>S.MAX_VOYAGE_MS||time-v.lastInput>600000){persist(user,profile(user));voyages.delete(user);continue;}if(v.sunk||time<(v.protectedUntil||0))continue;
  const active=time-v.lastInput<1000;let input=active?v.input:{};const s=v.stats;if(v.autopilot&&!v.helmOccupied&&!v.tethered){const pilot=v.roster.map(id=>S.RECRUITS[id]).filter(c=>c.role==='sailor').sort((a,b)=>b.tier-a.tier)[0];if(pilot){let goal=v.autopilot.goal;if(v.autopilot.mode==='patrol'){const enemy=entities(v).filter(e=>e.kind==='pirate'&&e.hp>0&&dist(e,v)<2600+pilot.tier*300).sort((a,b)=>{const score=e=>dist(e,v)+(pilot.tier>=3?250*e.hp/e.maxHp:0);return score(a)-score(b);})[0];if(enemy){v.autopilot.state='Engaging '+enemy.name;const lead=pilot.tier>=3?pilot.tier*.25:0,ex=enemy.x+Math.cos(enemy.a)*(enemy.speed||0)*lead,ey=enemy.y+Math.sin(enemy.a)*(enemy.speed||0)*lead,a=Math.atan2(v.y-ey,v.x-ex)+.45;goal={x:ex+Math.cos(a)*430,y:ey+Math.sin(a)*430};v.auto=true;}else if(!goal||dist(v,goal)<180||time>(v.autopilot.searchAt||0)+65000){const step=v.autopilot.searchStep=(v.autopilot.searchStep||0)+1,a=S.random(v.seed+'|search-course')()*Math.PI*2+Math.sin(step*2.399)*.6;goal=v.autopilot.goal={x:v.x+Math.cos(a)*S.SECTOR*.8,y:v.y+Math.sin(a)*S.SECTOR*.8};v.autopilot.searchAt=time;v.thinkAt=0;v.autopilot.state='Searching new waters';}}input=navigation.steer(v,goal,S.obstacles(entities(v)),time,pilot.tier);if(v.autopilot.mode!=='patrol'&&(v.autopilot.mode==='home'?Math.hypot(v.x,v.y)<230:dist(v,goal)<100)){v.autopilot=null;input={};notice(v,'Sailor: destination reached.');}}else v.autopilot=null;}
  if(v.onFoot){const island=entities(v).find(e=>e.id===v.onFoot);if(!island){v.onFoot=null;continue;}S.moveFoot(v,input,dt,island);
   if(v.swing&&!v.swing.resolved&&time>=v.swing.impact){v.swing.resolved=true;for(const g of island.guards)if(g.hp>0&&dist(g,v)<95&&Math.cos(Math.atan2(g.y-v.y,g.x-v.x)-v.swing.a)>.2){g.hp=Math.max(0,g.hp-35);g.hitAt=time;g.stunUntil=time+320;g.attack=null;emit(v,{kind:'hit',x:g.x,y:g.y,born:time,until:time+400});}}
   for(const g of island.guards)if(g.hp>0){g.a=Math.atan2(v.y-g.y,v.x-g.x);g.moving=false;
    if(g.attack&&!g.attack.resolved&&time>=g.attack.impact){g.attack.resolved=true;if(dist(g.attack.target,v)<43){v.hp-=18+island.tier*5;emit(v,{kind:'hurt',x:v.x,y:v.y,born:time,until:time+350});}}
    if(time<(g.stunUntil||0)||g.attack&&time<g.attack.end)continue;
    const d=dist(g,v);if(d>48){g.x+=Math.cos(g.a)*52*dt;g.y+=Math.sin(g.a)*52*dt;g.moving=true;}
    else if(time>=(g.attackAt||0)){g.attack={start:time,impact:time+650,end:time+1100,target:{x:v.x,y:v.y},a:g.a};g.attackAt=time+1550;}
   }
   const alive=island.guards.filter(g=>g.hp>0);for(let i=0;i<alive.length;i++)for(let j=i+1;j<alive.length;j++){const a=alive[i],b=alive[j],d=dist(a,b);if(d<30){const angle=d?Math.atan2(b.y-a.y,b.x-a.x):i*2.4,shift=(30-d)/2;a.x-=Math.cos(angle)*shift;a.y-=Math.sin(angle)*shift;b.x+=Math.cos(angle)*shift;b.y+=Math.sin(angle)*shift;}}for(const g of alive)S.constrainFoot(g,island);
  }else{
   const boost=input.boost&&v.magic>0;S.moveShip(v,input,dt);if(time<(v.slowUntil||0))v.speed*=Math.exp(-dt*2);nearby(v);
   const land=S.obstacles(entities(v));if(S.clearWater(v,S.hullRadius(v.ship),land))v.speed=0;
   for(const e of entities(v)){
    if(e.kind!=='island'&&(e.crewSimTime===time||externalTargets(v).some(b=>b.hp>0&&dist(b,e)<dist(v,e))))continue;if(e.kind!=='island')e.crewSimTime=time;if(e.kind==='kraken'&&independentTentacles){tentacles.tick(e,[v,...externalTargets(v)],combatants(),time,dt,f=>emit(v,f),hurtPlayer);S.clearWater(e,S.KRAKEN_RADIUS*(e.great?3:1),land);continue;}if(time<(e.protectedUntil||0))continue;
    if(e.kind!=='island')S.clearWater(e,e.kind==='kraken'?S.KRAKEN_RADIUS:S.hullRadius(e.ship),land);
    if(e.kind==='pirate'&&e.hp>0){pirateTick(v,e,land,time,dt);continue;}
    if(e.kind==='pirate'&&(time<(e.tetherUntil||0)||time<(e.boardingActiveUntil||0)||e.boarders&&!e.boarders.some(g=>g.cannon&&g.hp>0))){e.warning=0;e.attack=null;continue;}
    if(e.hp>0){if(e.warning&&time>=e.warning){const marks=e.attack?.targets||[e.target],hit=marks.some(p=>dist(p,v)<(e.attack?.radius||85));if(hit)v.hp-=e.kind==='kraken'?((['cross','sweep'].includes(e.attack?.type)?101:127)+e.tier*63)*(e.attack?.damageScale||1):35+e.tier*25;for(const p of marks)emit(v,{kind:e.kind==='kraken'?'slam':'splash',x:p.x,y:p.y,hit,born:time,until:time+1100});e.attackAt=time+4500;e.warning=0;}}
    if(e.hp>0&&(dist(e,v)<(e.kind==='kraken'?2600:800)||time<(e.aggroUntil||0)&&dist(e,v)<(e.kind==='kraken'?3200:1700))){const d=dist(e,v);e.engaged=true;e.a=Math.atan2(v.y-e.y,v.x-e.x);
     if(d>(e.kind==='kraken'?330:210)&&!e.warning&&time>=(e.tetherUntil||0)){let heading=e.a;const radius=e.kind==='kraken'?S.KRAKEN_RADIUS:S.hullRadius(e.ship);const ahead={x:e.x+Math.cos(heading)*(radius+90),y:e.y+Math.sin(heading)*(radius+90)};const obstacle=land.find(i=>Math.hypot(ahead.x-i.x,ahead.y-i.y)<i.r+radius+20);if(obstacle){const radial=Math.atan2(e.y-obstacle.y,e.x-obstacle.x);const cross=Math.sin(heading-radial);heading=radial+(cross>=0?1:-1)*Math.PI/2;}e.a=heading;e.x+=Math.cos(heading)*(e.kind==='kraken'?78:60)*dt;e.y+=Math.sin(heading)*(e.kind==='kraken'?78:60)*dt;S.clearWater(e,radius,land);}
     const contact=(e.kind==='kraken'?S.KRAKEN_RADIUS*.37:S.hullRadius(e.ship))+S.hullRadius(v.ship);if(d<contact){const a=Math.atan2(v.y-e.y,v.x-e.x);v.x=e.x+Math.cos(a)*(contact+1);v.y=e.y+Math.sin(a)*(contact+1);v.speed*=.4;}
     if(boost&&d<contact+12&&time>v.ramAt){v.ramAt=time+3500;leviathanRewards.record(e,v,Math.min(e.hp,s.ramStrength));e.hp=Math.max(0,e.hp-s.ramStrength);v.hp-=Math.max(0,s.ramStrength/2-s.ramDefense);if(!e.hp)defeated(v,e);}
     if(d<(e.kind==='kraken'?500:430)&&!S.blockedSeaLine(e,v,land.map(i=>({...i,r:i.r+25})))&&time>e.attackAt&&!e.warning){leviathanAttack(e,v,time);}
     
    }
   }
   S.clearWater(v,S.hullRadius(v.ship),land);if(v.auto&&v.roster.length)attack(v,0,true);
   v.storm=.58+.32*clamp((Math.hypot(v.x,v.y)-2600)/18000,0,1)+.08*Math.sin(time/28000)**2;
   v.hp-=Math.max(0,v.storm-.68)*7*(1-s.stability/100)*dt;
  }
  ordnance.tick(v,[...entities(v),...entities(v).flatMap(e=>(e.guards||[]).filter(g=>!g.cave)),...externalTargets(v)],time,(e,damage)=>{leviathanRewards.record(e,v,damage);defeated(v,e);},f=>emit(v,f));projectiles(v,dt,time);if(v.ammoDirty&&time>=(v.ammoSaveAt||0)){persist(user,profile(user));v.ammoDirty=false;v.ammoSaveAt=time+2000;}v.fx=v.fx.filter(f=>f.until>time).slice(-12);
  if(v.hp<=0){v.hp=0;v.sunk=true;v.input={};}
  if(!v.onFoot)for(const other of externalTargets(v)){if(other.hp<=0||other.onFoot||time<(other.protectedUntil||0))continue;if(dist(v,other)>S.hullRadius(v.ship)+S.hullRadius(other.ship)||!S.separateShips(v,other))continue;v.speed*=.35;other.speed*=.35;const land=S.obstacles(entities(v));S.clearWater(v,S.hullRadius(v.ship),land);S.clearWater(other,S.hullRadius(other.ship),land);}
 }}
 function pirateTick(v,e,land,time,dt){
  e.shots=e.shots||[];e.shotAmmo??=120+(e.tier||0)*60;e.mortarAmmo??=30+(e.tier||0)*10;const opponents=[v,...externalTargets(v)].filter(b=>b.hp>0&&time>=(b.protectedUntil||0)),target=opponents.sort((a,b)=>dist(a,e)-dist(b,e))[0];
  ordnance.tick(e,opponents,time,()=>{},f=>emit(v,f));
  e.shots=e.shots.filter(p=>{const step=S.CANNON_SPEED*dt,end={x:p.x+p.dx*step,y:p.y+p.dy*step};let first=Infinity,hit=null;for(const i of land){const t=S.segmentHit(p,end,i,i.r);if(t!==null&&t<first){first=t;hit=null;}}for(const b of opponents){const t=S.segmentHit(p,end,b,S.hullRadius(b.ship)*.65);if(t!==null&&t<first){first=t;hit=b;}}if(first!==Infinity){if(hit)hit.hp=Math.max(0,hit.hp-p.damage);emit(v,{kind:'hit',x:p.x+p.dx*step*first,y:p.y+p.dy*step*first,born:time,until:time+500});return false;}p.x=end.x;p.y=end.y;p.travel+=step;return p.travel<S.CANNON_RANGE;});
  if(!target||time<(e.tetherUntil||0)||time<(e.boardingActiveUntil||0))return;
  const captain=!e.boarders||e.boarders.some(g=>g.captain&&g.hp>0),d=dist(e,target);if(d>1700)return;
  if(captain){const bearing=Math.atan2(target.y-e.y,target.x-e.x),side=Math.sin(bearing-e.a)>=0?1:-1,orbit=Math.atan2(e.y-target.y,e.x-target.x)+side*.5,goal=d>650?{x:target.x,y:target.y}:{x:target.x+Math.cos(orbit)*430,y:target.y+Math.sin(orbit)*430};const i=navigation.steer(e,goal,land,time,Math.min(4,1+(e.tier||0)));e.stats={...S.SHIPS[e.ship],speed:S.SHIPS[e.ship].speed*.84};e.speed=e.speed||0;e.wind=.4;e.magic=0;S.moveShip(e,i,dt);if(time<(e.slowUntil||0))e.speed*=Math.exp(-dt*2);S.clearWater(e,S.hullRadius(e.ship),land);}
  const contact=(S.hullRadius(e.ship)+S.hullRadius(target.ship))*.65;if(dist(e,target)<contact){if(target===v&&v.input.boost&&time>v.ramAt){v.ramAt=time+3500;e.hp=Math.max(0,e.hp-v.stats.ramStrength);v.hp-=Math.max(0,v.stats.ramStrength/2-v.stats.ramDefense);if(!e.hp)defeated(v,e);}const a=Math.atan2(target.y-e.y,target.x-e.x);target.x=e.x+Math.cos(a)*(contact+1);target.y=e.y+Math.sin(a)*(contact+1);target.speed*=.4;}
  if(e.siege&&e.mortarAmmo>=(S.MORTARS[e.mortarTier]||S.MORTARS.medium).cost&&captain&&d>180&&d<(S.MORTARS[e.mortarTier]||S.MORTARS.medium).range&&time>=(e.mortarAt||0)){const aim=ordnance.intercept(e,target);if(dist(e,aim)<=(S.MORTARS[e.mortarTier]||S.MORTARS.medium).range&&ordnance.launch(e,aim,time,true))e.mortarAmmo-=(S.MORTARS[e.mortarTier]||S.MORTARS.medium).cost;}
  if(e.hp<=0||time<(e.attackAt||0))return;const predicted=S.predictCourse(target,d/S.CANNON_SPEED);const rays=S.cannonRays(e).filter(ray=>(!e.boarders||e.boarders.some(g=>g.hp>0&&g.cannon===ray.key))&&S.segmentHit(ray,{x:ray.x+ray.dx*S.CANNON_RANGE,y:ray.y+ray.dy*S.CANNON_RANGE},predicted,S.hullRadius(target.ship)*.85)!==null&&!S.blockedSeaLine(ray,target,land));
  if(rays.length&&e.shotAmmo>0){const side=rays[0].side;for(const ray of rays.filter(r=>r.side===side).slice(0,e.shotAmmo)){e.shotAmmo--;e.shots.push({...S.cannonMuzzle(e,ray,0,.12,time),id:e.id+':'+time+':'+ray.key,born:time,travel:0,damage:38+(e.tier||0)*18});emit(v,{kind:'muzzle',x:ray.x,y:ray.y,born:time,until:time+350});}e.attackAt=time+2900;}
 }
 function view(user,v){return {profile:profile(user),money:getUser(user).money,voyage:v?{serverNow:now(),simTime:v.tickAt,ammo:{...v.ammo},selectedAmmo:v.selectedAmmo,siege:v.siege,mortarTier:v.mortarTier,mortarReload:Math.max(0,(v.mortarAt||0)-now()),mortarShots:[...(v.mortarShots||[]),...entities(v).flatMap(e=>e.mortarShots||[])].map(({damage,...p})=>p),walkA:v.walkA,walkSpeed:v.walkSpeed,swing:v.swing,x:v.x,y:v.y,a:v.a,turnVelocity:v.turnVelocity,speed:v.speed,hp:v.hp,magic:v.magic,stats:v.stats,ship:v.ship,onFoot:v.onFoot,boat:v.boat,cargo:v.cargo.map(c=>({rarity:c.rarity})),entities:entities(v),autopilot:v.autopilot,projectiles:[...v.projectiles,...entities(v).flatMap(e=>e.shots||[])].map(({damage,...p})=>p),crewId:v.crewId,reloadLeft:{port:Math.max(0,(v.fireSides[-1]||0)-now()),starboard:Math.max(0,(v.fireSides[1]||0)-now())},storm:v.storm,wind:v.wind,auto:v.auto,notice:v.notice,fx:v.fx,remaining:Math.max(0,S.MAX_VOYAGE_MS-(now()-v.started)),kills:v.kills}:null};}
 function handle(user,m){let p=profile(user),v=voyages.get(user);if(v?.sunk)return sink(user,v);const action=m.action||'status';
  if(action==='status')return view(user,v);
  if(action==='sail'){if(v)return view(user,v);if(!p.ship)throw Error('Buy your first sailboat at the Shipwright.');if(voyages.size>=maxSessions)throw Error('The harbor is busy. Try again shortly.');const s=S.stats(p),time=now();v={ammo:p.ammo,selectedAmmo:'round',siege:p.siegeEquipped,mortarTier:p.mortarTier,mortarShots:[],seed:seed(),started:time,tickAt:time,lastInput:time,x:120,y:120,a:-.7,turnVelocity:0,speed:0,hp:s.durability,magic:s.magicStorage,ship:p.ship,stats:s,crewId:p.activeCrew,extraCrew:p.extraCrew.slice(),roster:p.roster.slice(),auto:!!p.activeCrew,sectors:new Map(),completed:new Set(),cargo:[],kills:0,input:{},fireSides:{},projectiles:[],shotId:0,ramAt:0,meleeAt:0,repairAt:0,wind:.4,storm:.58,fx:[],notice:'Sail out. Find islands and pirates. Bring sealed chests home.'};nearby(v);const occupied=[...voyages.values(),...externalTargets(v)].filter(b=>b.hp>0),land=S.obstacles(entities(v));let berth=null;for(let ring=0;ring<7&&!berth;ring++)for(let i=0;i<24&&!berth;i++){const a=i*Math.PI/12,r=170+ring*210,c=ring===0&&i===0?{x:120,y:120,a:-.7,ship:v.ship}:{x:Math.cos(a)*r,y:Math.sin(a)*r,a:-.7,ship:v.ship};const original={...c};S.clearWater(c,S.hullRadius(c.ship),land);if(dist(c,original)<1&&occupied.every(b=>dist(b,c)>S.hullRadius(b.ship)+S.hullRadius(c.ship)+25)&&entities(v).filter(e=>e.hp>0&&e.kind!=='island'&&now()>=(e.protectedUntil||0)).every(e=>dist(e,c)>S.hullRadius(c.ship)+(e.kind==='kraken'?S.KRAKEN_RADIUS:S.hullRadius(e.ship))+25))berth=c;}if(!berth)throw Error('All harbor berths are occupied. Wait for a ship to depart.');Object.assign(v,berth);voyages.set(user,v);nearby(v);return view(user,v);}
  if(action==='crew')throw Error('Crews are found on rare island camps. Rescue recruits while exploring.');
  if(action==='crew_dismiss'){if(!p.roster.includes(m.crew))throw Error('Recruit not owned.');const index=m.rosterIndex===undefined?p.roster.indexOf(m.crew):m.rosterIndex;if(!Number.isInteger(index)||p.roster[index]!==m.crew)throw Error('Crew roster changed. Reopen the crew menu.');p.roster.splice(index,1);if(!p.roster.includes(m.crew)){if(p.activeCrew===m.crew)p.activeCrew=null;p.extraCrew=p.extraCrew.filter(id=>id!==m.crew);}if(v){const fraction=v.hp/v.stats.durability;v.roster=p.roster.slice();v.crewId=p.activeCrew;v.extraCrew=p.extraCrew.slice();v.stats=S.stats(p);v.hp=v.stats.durability*fraction;}persist(user,p);return view(user,v);}
  if(action==='buy'||action==='crew_equip'||action==='upgrade'||action==='equip'||action==='ammo_buy'||action==='siege_equip'){if(v)throw Error('Return to the Shipwright first.');
   if(action==='ammo_buy'){const a=Object.hasOwn(S.AMMO,m.ammo)&&S.AMMO[m.ammo];if(!a)throw Error('Unknown ammunition.');if(getUser(user).money<a.price)throw Error('Not enough coins.');if(p.ammo[m.ammo]+a.pack>9999)throw Error('Ammunition storage is full.');pay(user,a.price);p.ammo[m.ammo]+=a.pack;}
   if(action==='siege_equip'){if(!p.siegeOwned)throw Error('Find a mortar in a sealed chest first.');const tier=m.tier||p.mortarTier;if(!p.mortars.includes(tier))throw Error('Mortar tier not owned.');p.siegeEquipped=!(p.siegeEquipped&&p.mortarTier===tier);p.mortarTier=tier;}
   if(action==='buy'){const ship=Object.hasOwn(S.SHIPS,m.ship)&&S.SHIPS[m.ship];if(!ship)throw Error('Unknown ship.');if(p.owned.includes(m.ship))throw Error('You already own this ship.');if(p.gems<ship.gems)throw Error('Not enough gems.');if((+getUser(user).money||0)<ship.coins)throw Error('Not enough coins.');pay(user,ship.coins);p.gems-=ship.gems;p.owned.push(m.ship);p.ship=m.ship;}
   if(action==='equip'){if(!p.owned.includes(m.ship))throw Error('Ship not owned.');p.ship=m.ship;}
   if(action==='crew_equip'){if(['fighter','looter','mechanic','sailor'].includes(S.RECRUITS[m.crew]?.role))throw Error('Companions sail automatically; assign a sailing specialist here.');if(m.crew!==null&&!p.roster.includes(m.crew))throw Error('Recruit not owned.');if(m.crew===null){p.activeCrew=null;p.extraCrew=[];}else if(m.slot==='second'){if(p.ship!=='brig')throw Error('Only brigs have a second specialist slot.');if(p.activeCrew===m.crew)throw Error('Already assigned in slot 1.');p.extraCrew=[m.crew];}else{p.activeCrew=m.crew;p.extraCrew=p.extraCrew.filter(id=>id!==m.crew);}}
   if(action==='upgrade'){if(!['hull','sails','cannons','cargo','arcane'].includes(m.slot)||!p.ship)throw Error('Choose a valid refit.');const n=p.upgrades[m.slot]||0,cost=35*(n+1);if(n>=5)throw Error('Refit is at maximum level.');if(p.gems<cost)throw Error('Not enough gems.');p.gems-=cost;p.upgrades[m.slot]=n+1;}
   persist(user,p);return view(user,null);
  }
  if(!v)throw Error('No active voyage. Return to the Shipwright.');
  if(action==='input'){v.lastInput=now();const i=m.input||{};v.input={forward:i.forward===true,back:i.back===true,left:i.left===true,right:i.right===true,boost:i.boost===true,walkAngle:Number.isFinite(i.walkAngle)?Math.atan2(Math.sin(i.walkAngle),Math.cos(i.walkAngle)):-Math.PI/2};return view(user,v);}
  if(action==='ammo_select'){if(!Object.hasOwn(S.AMMO,m.ammo))throw Error('Unknown ammunition.');v.selectedAmmo=m.ammo;return view(user,v);}
  if(action==='mortar'){if(!v.siege)throw Error('Equip a mortar at the Shipwright first.');if(!Number.isFinite(m.x)||!Number.isFinite(m.y))throw Error('Choose a target.');const d=dist(v,m),spec=S.MORTARS[v.mortarTier]||S.MORTARS.medium;if(d<180||d>spec.range)throw Error('Mortar range: 180–'+spec.range+' m.');if(now()<(v.mortarAt||0))throw Error('Mortar is reloading.');if(v.ammo.heavy<spec.cost)throw Error('Mortar requires '+spec.cost+' heavy cannonballs.');if(ordnance.launch(v,m,now())){v.ammo.heavy-=spec.cost;persist(user,p);}return view(user,v);}
  if(action==='fire'){if(m.magic===true)throw Error('Arcane Volley has been removed. Use a port or starboard broadside.');attack(v,[-1,1].includes(m.side)?m.side:0,false,m);return view(user,v);}
  if(action==='auto'){v.auto=!!S.cannonAssignments(v).length&&!v.auto;return view(user,v);}
  if(action==='repair'){if(v.hp>=v.stats.durability)throw Error('Your hull is already fully repaired.');if(now()<v.repairAt)throw Error('Repair crew is still working.');if((+getUser(user).money||0)<500)throw Error('Repairs need 500 coins.');pay(user,500);v.hp=Math.min(v.stats.durability,v.hp+v.stats.durability*.3);v.repairAt=now()+20000;notice(v,'Repaired 30% hull for 500 coins.');return view(user,v);}
  if(action==='recruit'){recruit(user,v);return view(user,v);}
  if(action==='board'&&v.onFoot){if(dist(v,v.boat)>S.hullRadius(v.ship)+100)throw Error('Move closer to the ship at the shore.');v.onFoot=null;v.swing=null;v.x=v.boat.x;v.y=v.boat.y;notice(v,'Back aboard.');return view(user,v);}
  if(action==='board'&&!v.onFoot)return handle(user,{action:'interact'});
  if(action==='interact'){
   if(v.onFoot){const e=entities(v).find(e=>e.id===v.onFoot);if(S.recruitCamps(e).some(c=>!c.recruited&&dist(c,v)<65)&&e.guards.every(g=>g.hp<=0)){recruit(user,v);return view(user,v);}if(dist(e,v)<85){if(e.guards.some(g=>g.hp>0))throw Error('Defeat the island defenders first.');if(e.looted)throw Error('This island has been looted.');if(v.cargo.length>=v.stats.cargo)throw Error('Your cargo hold is full.');e.looted=true;e.deathAt=now();complete(v,e);if(e.kind==='pirate'){ordnance.supply(v.ammo,e.tier||0);v.ammoDirty=true;}chest(v,e.tier,e.id);notice(v,'Sealed chest stowed. Return to your ship at the shore.');}
    else notice(v,'Chest is at the island center. Your ship waits at the shore.');
   }else{const e=entities(v).find(e=>e.kind==='island'&&dist(e,v)<e.r+105);if(!e)throw Error('Sail alongside an island to disembark.');const a=Math.atan2(v.y-e.y,v.x-e.x);v.boat={x:e.x+Math.cos(a)*(e.r+S.hullRadius(v.ship)+12),y:e.y+Math.sin(a)*(e.r+S.hullRadius(v.ship)+12)};v.onFoot=e.id;v.walkA=a+Math.PI;v.walkSpeed=0;v.swing=null;v.x=e.x+Math.cos(a)*(e.r>250?e.r*.84*S.shoreFactor(e,a):e.r-35);v.y=e.y+Math.sin(a)*(e.r>250?e.r*.84*S.shoreFactor(e,a):e.r-35);v.speed=0;for(const threat of entities(v)){threat.warning=0;threat.attack=null;threat.attackAt=now()+1500;}notice(v,'Explore on foot. Space attacks; F loots the central chest; B boards at shore.');}return view(user,v);
  }
  if(action==='return'){if(v.onFoot||Math.hypot(v.x,v.y)>260)throw Error('Follow the home compass to the harbor before unloading.');let coins=0,gems=0,rep=0;for(const c of v.cargo){coins+=c.coins;gems+=c.gems;rep+=c.rep;}const mortarFound=ordnance.bank(p,v.cargo);pay(user,-coins);p.gems+=gems;p.reputation+=rep;p.deliveries+=v.cargo.length;p.kills+=v.kills;persist(user,p);voyages.delete(user);return{...view(user,null),ended:true,reason:`Unloaded ${v.cargo.length} sealed chests: ${coins} coins, ${gems} gems, ${rep} reputation.${mortarFound?' Mortar discovered! Equip it at the Shipwright.':''}`};}
  if(action==='rescue'){voyages.delete(user);return{...view(user,null),ended:true,reason:'Rescued to the neighborhood. All unbanked cargo was abandoned.'};}
  throw Error('Unknown sea action.');
 }
 return{raw:user=>voyages.get(user),handle,tick,disconnect:user=>{if(voyages.has(user))persist(user,profile(user));voyages.delete(user);},sessionCount:()=>voyages.size,diagnostics:user=>{const v=voyages.get(user);return v?{sectors:v.sectors.size,completed:v.completed.size}:null;}};
};
