"""Rebuild the Dark Sea mesh library in Blender; preserve Three.js local coordinates."""
import bpy,bmesh,json,math,os
from mathutils import Matrix,Vector
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
data=json.loads((ROOT/'tools/blender/source-models.json').read_text())
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
assets={};native={};counts={}
for number,(key,src) in enumerate(data['geometries'].items()):
    pts=src['position'];verts=[pts[i:i+3] for i in range(0,len(pts),3)];idx=src['index'] or list(range(len(verts)))
    faces=[idx[i:i+3] for i in range(0,len(idx),3)]
    mesh=bpy.data.meshes.new(key);mesh.from_pydata(verts,[],faces);mesh.update()
    obj=bpy.data.objects.new(key,mesh);bpy.context.collection.objects.link(obj)
    bm=bmesh.new();bm.from_mesh(mesh);bmesh.ops.remove_doubles(bm,verts=list(bm.verts),dist=.00001);bm.to_mesh(mesh);bm.free()
    dims=[max(v[i] for v in verts)-min(v[i] for v in verts) for i in range(3)];typ=src['type']
    bpy.context.view_layer.objects.active=obj;obj.select_set(True)
    if typ in ['BoxGeometry','CylinderGeometry','ConeGeometry','ExtrudeGeometry'] and min(dims)>.025:
        bevel=obj.modifiers.new('Crafted edge bevels','BEVEL');bevel.width=min(.065,min(dims)*.12);bevel.segments=2;bevel.limit_method='ANGLE';bevel.angle_limit=.5
        bpy.ops.object.modifier_apply(modifier=bevel.name)
    if typ in ['CapsuleGeometry','DodecahedronGeometry','IcosahedronGeometry']:
        sub=obj.modifiers.new('Organic contour refinement','SUBSURF');sub.levels=1;sub.subdivision_type='CATMULL_CLARK';bpy.ops.object.modifier_apply(modifier=sub.name)
        if typ in ['DodecahedronGeometry','IcosahedronGeometry']:
            for v in obj.data.vertices:
                p=v.co;factor=1+.07*math.sin(p.x*3.7+p.z*2.1)*math.cos(p.y*4.1);p*=factor
    # Give the creature shell a subtle sculpted ridge pattern rather than a plain sphere.
    if typ=='SphereGeometry' and src['parameters'].get('widthSegments')==40:
        for v in obj.data.vertices:
            p=v.co;p*=1+.028*math.cos(math.atan2(p.x,p.z)*10)*max(0,1-abs(p.y))
    mesh=obj.data
    for poly in mesh.polygons:poly.use_smooth=typ not in ['BoxGeometry','ExtrudeGeometry']
    if typ in ['BoxGeometry','CylinderGeometry','ConeGeometry','ExtrudeGeometry']:
        for poly in mesh.polygons:poly.use_smooth=True
        norm=obj.modifiers.new('Weighted artisan normals','WEIGHTED_NORMAL');norm.keep_sharp=True;norm.weight=40
        bpy.ops.object.modifier_apply(modifier=norm.name)
    mesh.calc_loop_triangles();position=[];normal=[];uv=[]
    for tri in mesh.loop_triangles:
        for li,vi in zip(tri.loops,tri.vertices):
            v=mesh.vertices[vi].co;n=mesh.corner_normals[li].vector
            position.extend(round(c,5) for c in v);normal.extend(round(c,5) for c in n)
            axis=max(range(3),key=lambda k:abs(n[k]));axes=[k for k in range(3) if k!=axis];uv.extend(round(v[k]/max(.1,dims[k])+.5,5) for k in axes)
    assets[key]={'p':position,'n':normal,'u':uv};native[key]=mesh;counts[typ]=counts.get(typ,0)+1
    bpy.data.objects.remove(obj,do_unlink=True)
    if number%100==0:print('REFINED',number,flush=True)
(ROOT/'assets/dark-sea/blender-meshes.js').write_text('/* Generated by Blender 5.2.1; rebuild with tools/blender/build-assets.py. */\nwindow.DarkSeaBlenderMeshes='+json.dumps(assets,separators=(',',':'))+';\n')
# Store complete editable model assemblies, retaining named collections and original pivots.
materials={}
for model in data['scenes']:
    col=bpy.data.collections.new(model['name']);bpy.context.scene.collection.children.link(col)
    for i,part in enumerate(model['objects']):
        geo=native.get(part['key'])
        if geo is None:
            p=part['position'];verts=[p[j:j+3] for j in range(0,len(p),3)];idx=part['index'] or list(range(len(verts)));geo=bpy.data.meshes.new('animated-source');geo.from_pydata(verts,[],[idx[j:j+3] for j in range(0,len(idx),3)]);geo.update()
        color=tuple(round(c,3) for c in part['color']);mat=materials.get(color)
        if mat is None:mat=bpy.data.materials.new('pigment');mat.diffuse_color=(*color,1);mat.use_nodes=True;bs=mat.node_tree.nodes.get('Principled BSDF');bs.inputs['Base Color'].default_value=(*color,1);bs.inputs['Roughness'].default_value=.55;materials[color]=mat
        o=bpy.data.objects.new(model['name']+'-'+str(i),geo);col.objects.link(o);o.matrix_world=Matrix([part['matrix'][j:j+4] for j in range(0,16,4)]).transposed();o.data.materials.append(mat);o.material_slots[0].link='OBJECT';o.material_slots[0].material=mat
    col.hide_render=model['name'] not in ['brig','great-leviathan'];col.hide_viewport=col.hide_render
# Stage shared gameplay models for a useful native Blender review render.
convert=Matrix.Rotation(math.pi/2,4,'X')
for o in bpy.data.collections['brig'].objects:o.matrix_world=convert @ Matrix.Translation((-20,0,0)) @ o.matrix_world
for o in bpy.data.collections['great-leviathan'].objects:o.matrix_world=convert @ Matrix.Translation((22,0,0)) @ Matrix.Scale(.16,4) @ o.matrix_world
world=bpy.context.scene.world;world.use_nodes=True;world.node_tree.nodes['Background'].inputs[0].default_value=(.035,.065,.095,1);world.node_tree.nodes['Background'].inputs[1].default_value=.5
bpy.ops.object.camera_add(location=(55,-95,55));cam=bpy.context.object;cam.rotation_euler=(Vector((0,0,4))-cam.location).to_track_quat('-Z','Y').to_euler();cam.data.type='ORTHO';cam.data.ortho_scale=90;bpy.context.scene.camera=cam
for loc,power,size in [((-35,-40,70),70000,60),((30,40,60),90000,50)]:
    bpy.ops.object.light_add(type='AREA',location=loc);light=bpy.context.object;light.data.energy=power;light.data.shape='DISK';light.data.size=size;light.rotation_euler=(Vector((0,0,4))-light.location).to_track_quat('-Z','Y').to_euler()
scene=bpy.context.scene;scene.render.engine='CYCLES';scene.cycles.samples=16;scene.render.resolution_x=1280;scene.render.resolution_y=800;scene.render.resolution_percentage=100;scene.render.image_settings.file_format='PNG';scene.render.filepath=str(ROOT/'assets/dark-sea/blender-review.png')
bpy.ops.wm.save_as_mainfile(filepath=str(ROOT/'assets/dark-sea/dark-sea-models.blend'),compress=True)
(ROOT/'assets/dark-sea/manifest.json').write_text(json.dumps({'generator':bpy.app.version_string,'geometries':len(assets),'families':counts,'models':[m['name'] for m in data['scenes']]},indent=2))
bpy.ops.render.render(write_still=True)
print('FINISHED',len(assets),flush=True)
