'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path'),THREE=require('../../js/vendor/three.min'),S=require('../../js/shared/sea');
const root=path.resolve(__dirname,'../..'),geometries={};
function key(g){if(!['BoxGeometry','CylinderGeometry','ConeGeometry','DodecahedronGeometry','IcosahedronGeometry','CapsuleGeometry','SphereGeometry','ExtrudeGeometry'].includes(g.type))return null;const p=g.attributes.position;if(p.count>6000)return null;let hash=2166136261;for(const n of p.array){hash^=Math.round(n*10000);hash=Math.imul(hash,16777619);}return g.type+':'+(hash>>>0).toString(16);}
function capture(g){const k=key(g);if(!k||geometries[k])return;const a=g.attributes;geometries[k]={type:g.type,parameters:g.type==='ExtrudeGeometry'?{}:g.parameters,position:[...a.position.array],index:g.index?[...g.index.array]:null};}
const env={THREE,DARK_SEA:S,console,window:{addEventListener(){}},document:{addEventListener(){}},performance:{now:()=>1000},capture};vm.createContext(env);let source=fs.readFileSync(path.join(root,'js/sea3d.js'),'utf8').replace('const m=new THREE.Mesh(geo,mat);','capture(geo);const m=new THREE.Mesh(geo,mat);').replace('function batchStatic(g){','function batchStatic(g){return;').replace('window.SeaGL={','window.authoring={boat,kraken,person,chestModel,island,caveModel,holdModel,initializeMaterials,animateKraken,setScene:()=>scene=new THREE.Group()};window.SeaGL={');vm.runInContext(source,env);const a=env.window.authoring;a.initializeMaterials();a.setScene();const scenes=[];
function collect(name,g){g.updateMatrixWorld(true);const objects=[];g.traverse(o=>{if(!o.isMesh)return;for(let p=o;p;p=p.parent)if(!p.visible)return;const k=key(o.geometry);capture(o.geometry);objects.push({key:k,position:k?null:[...o.geometry.attributes.position.array],index:!k&&o.geometry.index?[...o.geometry.index.array]:null,matrix:o.matrixWorld.toArray(),color:o.material.color?.toArray()||[.5,.5,.5]});});scenes.push({name,objects});}
for(const type of Object.keys(S.SHIPS)){collect(type,a.boat(type));collect('pirate-'+type,a.boat(type,true));}
for(const great of [false,true]){const g=a.kraken(great);a.animateKraken(g,{hp:1,great,arms:[]},1000,1);collect(great?'great-leviathan':'leviathan',g);}
for(const hostile of [false,true]){const g=new THREE.Group();a.person(g,0,0,hostile);collect(hostile?'pirate-crew':'crew',g);}const chest=new THREE.Group();a.chestModel(chest,0,0,0);collect('treasure',chest);collect('hold',a.holdModel());
for(let n=1;n<=12;n++){for(const e of S.sector('blender-art',n,2).filter(e=>e.kind==='island')){collect('island-'+n,a.island(e));for(const cave of e.caves||[])collect('cave-'+n,a.caveModel(e,cave));}}
capture(new THREE.BoxGeometry(1,1,1));for(const n of [4,5,6,7,8,10,12,16,32,48]){capture(new THREE.ConeGeometry(1,1,n));capture(new THREE.CylinderGeometry(.85,1,1,n));}
fs.writeFileSync(path.join(__dirname,'source-models.json'),JSON.stringify({geometries,scenes}));fs.writeFileSync(path.join(__dirname,'geometry-key.txt'),key.toString());console.log(Object.keys(geometries).length+' geometries; '+scenes.length+' model scenes');
